// Generated by CIRCT firtool-1.75.0
module ChipTop(	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
  output         uart_0_txd,	// @[fpga/src/main/scala/taihang_soc/IOBinders.scala:47:22]
  input          uart_0_rxd,	// @[fpga/src/main/scala/taihang_soc/IOBinders.scala:47:22]
  output         axi4_fbus_0_clock,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:440:22]
  output         axi4_fbus_0_bits_aw_ready,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:440:22]
  input          axi4_fbus_0_bits_aw_valid,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:440:22]
  input  [4:0]   axi4_fbus_0_bits_aw_bits_id,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:440:22]
  input  [32:0]  axi4_fbus_0_bits_aw_bits_addr,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:440:22]
  input  [7:0]   axi4_fbus_0_bits_aw_bits_len,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:440:22]
  input  [2:0]   axi4_fbus_0_bits_aw_bits_size,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:440:22]
  input  [1:0]   axi4_fbus_0_bits_aw_bits_burst,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:440:22]
  input          axi4_fbus_0_bits_aw_bits_lock,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:440:22]
  input  [3:0]   axi4_fbus_0_bits_aw_bits_cache,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:440:22]
  input  [2:0]   axi4_fbus_0_bits_aw_bits_prot,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:440:22]
  input  [3:0]   axi4_fbus_0_bits_aw_bits_qos,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:440:22]
  output         axi4_fbus_0_bits_w_ready,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:440:22]
  input          axi4_fbus_0_bits_w_valid,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:440:22]
  input  [255:0] axi4_fbus_0_bits_w_bits_data,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:440:22]
  input  [31:0]  axi4_fbus_0_bits_w_bits_strb,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:440:22]
  input          axi4_fbus_0_bits_w_bits_last,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:440:22]
  input          axi4_fbus_0_bits_b_ready,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:440:22]
  output         axi4_fbus_0_bits_b_valid,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:440:22]
  output [4:0]   axi4_fbus_0_bits_b_bits_id,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:440:22]
  output [1:0]   axi4_fbus_0_bits_b_bits_resp,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:440:22]
  output         axi4_fbus_0_bits_ar_ready,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:440:22]
  input          axi4_fbus_0_bits_ar_valid,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:440:22]
  input  [4:0]   axi4_fbus_0_bits_ar_bits_id,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:440:22]
  input  [32:0]  axi4_fbus_0_bits_ar_bits_addr,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:440:22]
  input  [7:0]   axi4_fbus_0_bits_ar_bits_len,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:440:22]
  input  [2:0]   axi4_fbus_0_bits_ar_bits_size,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:440:22]
  input  [1:0]   axi4_fbus_0_bits_ar_bits_burst,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:440:22]
  input          axi4_fbus_0_bits_ar_bits_lock,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:440:22]
  input  [3:0]   axi4_fbus_0_bits_ar_bits_cache,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:440:22]
  input  [2:0]   axi4_fbus_0_bits_ar_bits_prot,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:440:22]
  input  [3:0]   axi4_fbus_0_bits_ar_bits_qos,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:440:22]
  input          axi4_fbus_0_bits_r_ready,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:440:22]
  output         axi4_fbus_0_bits_r_valid,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:440:22]
  output [4:0]   axi4_fbus_0_bits_r_bits_id,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:440:22]
  output [255:0] axi4_fbus_0_bits_r_bits_data,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:440:22]
  output [1:0]   axi4_fbus_0_bits_r_bits_resp,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:440:22]
  output         axi4_fbus_0_bits_r_bits_last,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:440:22]
  output         axi4_mem_0_clock,	// @[fpga/src/main/scala/taihang_soc/IOBinders.scala:30:22]
  input          axi4_mem_0_bits_aw_ready,	// @[fpga/src/main/scala/taihang_soc/IOBinders.scala:30:22]
  output         axi4_mem_0_bits_aw_valid,	// @[fpga/src/main/scala/taihang_soc/IOBinders.scala:30:22]
  output [3:0]   axi4_mem_0_bits_aw_bits_id,	// @[fpga/src/main/scala/taihang_soc/IOBinders.scala:30:22]
  output [32:0]  axi4_mem_0_bits_aw_bits_addr,	// @[fpga/src/main/scala/taihang_soc/IOBinders.scala:30:22]
  output [7:0]   axi4_mem_0_bits_aw_bits_len,	// @[fpga/src/main/scala/taihang_soc/IOBinders.scala:30:22]
  output [2:0]   axi4_mem_0_bits_aw_bits_size,	// @[fpga/src/main/scala/taihang_soc/IOBinders.scala:30:22]
  output [1:0]   axi4_mem_0_bits_aw_bits_burst,	// @[fpga/src/main/scala/taihang_soc/IOBinders.scala:30:22]
  output         axi4_mem_0_bits_aw_bits_lock,	// @[fpga/src/main/scala/taihang_soc/IOBinders.scala:30:22]
  output [3:0]   axi4_mem_0_bits_aw_bits_cache,	// @[fpga/src/main/scala/taihang_soc/IOBinders.scala:30:22]
  output [2:0]   axi4_mem_0_bits_aw_bits_prot,	// @[fpga/src/main/scala/taihang_soc/IOBinders.scala:30:22]
  output [3:0]   axi4_mem_0_bits_aw_bits_qos,	// @[fpga/src/main/scala/taihang_soc/IOBinders.scala:30:22]
  input          axi4_mem_0_bits_w_ready,	// @[fpga/src/main/scala/taihang_soc/IOBinders.scala:30:22]
  output         axi4_mem_0_bits_w_valid,	// @[fpga/src/main/scala/taihang_soc/IOBinders.scala:30:22]
  output [255:0] axi4_mem_0_bits_w_bits_data,	// @[fpga/src/main/scala/taihang_soc/IOBinders.scala:30:22]
  output [31:0]  axi4_mem_0_bits_w_bits_strb,	// @[fpga/src/main/scala/taihang_soc/IOBinders.scala:30:22]
  output         axi4_mem_0_bits_w_bits_last,	// @[fpga/src/main/scala/taihang_soc/IOBinders.scala:30:22]
  output         axi4_mem_0_bits_b_ready,	// @[fpga/src/main/scala/taihang_soc/IOBinders.scala:30:22]
  input          axi4_mem_0_bits_b_valid,	// @[fpga/src/main/scala/taihang_soc/IOBinders.scala:30:22]
  input  [3:0]   axi4_mem_0_bits_b_bits_id,	// @[fpga/src/main/scala/taihang_soc/IOBinders.scala:30:22]
  input  [1:0]   axi4_mem_0_bits_b_bits_resp,	// @[fpga/src/main/scala/taihang_soc/IOBinders.scala:30:22]
  input          axi4_mem_0_bits_ar_ready,	// @[fpga/src/main/scala/taihang_soc/IOBinders.scala:30:22]
  output         axi4_mem_0_bits_ar_valid,	// @[fpga/src/main/scala/taihang_soc/IOBinders.scala:30:22]
  output [3:0]   axi4_mem_0_bits_ar_bits_id,	// @[fpga/src/main/scala/taihang_soc/IOBinders.scala:30:22]
  output [32:0]  axi4_mem_0_bits_ar_bits_addr,	// @[fpga/src/main/scala/taihang_soc/IOBinders.scala:30:22]
  output [7:0]   axi4_mem_0_bits_ar_bits_len,	// @[fpga/src/main/scala/taihang_soc/IOBinders.scala:30:22]
  output [2:0]   axi4_mem_0_bits_ar_bits_size,	// @[fpga/src/main/scala/taihang_soc/IOBinders.scala:30:22]
  output [1:0]   axi4_mem_0_bits_ar_bits_burst,	// @[fpga/src/main/scala/taihang_soc/IOBinders.scala:30:22]
  output         axi4_mem_0_bits_ar_bits_lock,	// @[fpga/src/main/scala/taihang_soc/IOBinders.scala:30:22]
  output [3:0]   axi4_mem_0_bits_ar_bits_cache,	// @[fpga/src/main/scala/taihang_soc/IOBinders.scala:30:22]
  output [2:0]   axi4_mem_0_bits_ar_bits_prot,	// @[fpga/src/main/scala/taihang_soc/IOBinders.scala:30:22]
  output [3:0]   axi4_mem_0_bits_ar_bits_qos,	// @[fpga/src/main/scala/taihang_soc/IOBinders.scala:30:22]
  output         axi4_mem_0_bits_r_ready,	// @[fpga/src/main/scala/taihang_soc/IOBinders.scala:30:22]
  input          axi4_mem_0_bits_r_valid,	// @[fpga/src/main/scala/taihang_soc/IOBinders.scala:30:22]
  input  [3:0]   axi4_mem_0_bits_r_bits_id,	// @[fpga/src/main/scala/taihang_soc/IOBinders.scala:30:22]
  input  [255:0] axi4_mem_0_bits_r_bits_data,	// @[fpga/src/main/scala/taihang_soc/IOBinders.scala:30:22]
  input  [1:0]   axi4_mem_0_bits_r_bits_resp,	// @[fpga/src/main/scala/taihang_soc/IOBinders.scala:30:22]
  input          axi4_mem_0_bits_r_bits_last,	// @[fpga/src/main/scala/taihang_soc/IOBinders.scala:30:22]
  input          custom_boot,	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:196:23]
  output         axi4_mmio_0_clock,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:420:22]
  input          axi4_mmio_0_bits_aw_ready,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:420:22]
  output         axi4_mmio_0_bits_aw_valid,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:420:22]
  output [3:0]   axi4_mmio_0_bits_aw_bits_id,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:420:22]
  output [28:0]  axi4_mmio_0_bits_aw_bits_addr,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:420:22]
  output [7:0]   axi4_mmio_0_bits_aw_bits_len,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:420:22]
  output [2:0]   axi4_mmio_0_bits_aw_bits_size,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:420:22]
  output [1:0]   axi4_mmio_0_bits_aw_bits_burst,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:420:22]
  output         axi4_mmio_0_bits_aw_bits_lock,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:420:22]
  output [3:0]   axi4_mmio_0_bits_aw_bits_cache,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:420:22]
  output [2:0]   axi4_mmio_0_bits_aw_bits_prot,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:420:22]
  output [3:0]   axi4_mmio_0_bits_aw_bits_qos,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:420:22]
  input          axi4_mmio_0_bits_w_ready,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:420:22]
  output         axi4_mmio_0_bits_w_valid,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:420:22]
  output [63:0]  axi4_mmio_0_bits_w_bits_data,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:420:22]
  output [7:0]   axi4_mmio_0_bits_w_bits_strb,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:420:22]
  output         axi4_mmio_0_bits_w_bits_last,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:420:22]
  output         axi4_mmio_0_bits_b_ready,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:420:22]
  input          axi4_mmio_0_bits_b_valid,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:420:22]
  input  [3:0]   axi4_mmio_0_bits_b_bits_id,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:420:22]
  input  [1:0]   axi4_mmio_0_bits_b_bits_resp,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:420:22]
  input          axi4_mmio_0_bits_ar_ready,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:420:22]
  output         axi4_mmio_0_bits_ar_valid,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:420:22]
  output [3:0]   axi4_mmio_0_bits_ar_bits_id,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:420:22]
  output [28:0]  axi4_mmio_0_bits_ar_bits_addr,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:420:22]
  output [7:0]   axi4_mmio_0_bits_ar_bits_len,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:420:22]
  output [2:0]   axi4_mmio_0_bits_ar_bits_size,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:420:22]
  output [1:0]   axi4_mmio_0_bits_ar_bits_burst,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:420:22]
  output         axi4_mmio_0_bits_ar_bits_lock,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:420:22]
  output [3:0]   axi4_mmio_0_bits_ar_bits_cache,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:420:22]
  output [2:0]   axi4_mmio_0_bits_ar_bits_prot,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:420:22]
  output [3:0]   axi4_mmio_0_bits_ar_bits_qos,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:420:22]
  output         axi4_mmio_0_bits_r_ready,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:420:22]
  input          axi4_mmio_0_bits_r_valid,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:420:22]
  input  [3:0]   axi4_mmio_0_bits_r_bits_id,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:420:22]
  input  [63:0]  axi4_mmio_0_bits_r_bits_data,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:420:22]
  input  [1:0]   axi4_mmio_0_bits_r_bits_resp,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:420:22]
  input          axi4_mmio_0_bits_r_bits_last,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:420:22]
  input          reset_io,	// @[generators/chipyard/src/main/scala/clocking/ClockBinders.scala:87:24]
  input          clock_uncore,	// @[generators/chipyard/src/main/scala/clocking/ClockBinders.scala:95:26]
  output         clock_tap	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:196:23]
);

  wire _system_debug_systemjtag_reset_catcher_io_sync_reset;	// @[generators/rocket-chip/src/main/scala/util/ResetCatchAndSync.scala:39:28]
  wire _inst_jtag_tunnel_jtag_tck;	// @[fpga/fpga-shells/src/main/scala/ip/xilinx/bscan/bscan.scala:8:34]
  wire _inst_jtag_tunnel_jtag_tms;	// @[fpga/fpga-shells/src/main/scala/ip/xilinx/bscan/bscan.scala:8:34]
  wire _inst_jtag_tunnel_jtag_tdi;	// @[fpga/fpga-shells/src/main/scala/ip/xilinx/bscan/bscan.scala:8:34]
  wire _dmactiveAck_dmactiveAck_io_q;	// @[generators/rocket-chip/src/main/scala/util/ShiftReg.scala:45:23]
  wire _debug_reset_syncd_debug_reset_sync_io_q;	// @[generators/rocket-chip/src/main/scala/util/ShiftReg.scala:45:23]
  wire _iocell_custom_boot_i;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  wire _system_auto_cbus_fixedClockNode_anon_out_clock;	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35]
  wire _system_auto_cbus_fixedClockNode_anon_out_reset;	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35]
  wire _system_debug_systemjtag_jtag_TDO_data;	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35]
  wire _system_debug_systemjtag_jtag_TDO_driven;	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35]
  wire _system_debug_dmactive;	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35]
  wire _system_clock_tap;	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35]
  DigitalTop system (	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35]
    .auto_chipyard_prcictrl_domain_reset_setter_clock_in_member_allClocks_uncore_clock (clock_uncore),
    .auto_chipyard_prcictrl_domain_reset_setter_clock_in_member_allClocks_uncore_reset (reset_io),
    .auto_mbus_fixedClockNode_anon_out_clock                                           (axi4_mem_0_clock),
    .auto_cbus_fixedClockNode_anon_out_clock                                           (_system_auto_cbus_fixedClockNode_anon_out_clock),
    .auto_cbus_fixedClockNode_anon_out_reset                                           (_system_auto_cbus_fixedClockNode_anon_out_reset),
    .auto_fbus_fixedClockNode_anon_out_clock                                           (axi4_fbus_0_clock),
    .auto_sbus_fixedClockNode_anon_out_clock                                           (axi4_mmio_0_clock),
    .resetctrl_hartIsInReset_0                                                         (_system_auto_cbus_fixedClockNode_anon_out_reset),	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35]
    .debug_clock                                                                       (_system_auto_cbus_fixedClockNode_anon_out_clock),	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35]
    .debug_reset                                                                       (~_debug_reset_syncd_debug_reset_sync_io_q),	// @[generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:292:40, generators/rocket-chip/src/main/scala/util/ShiftReg.scala:45:23]
    .debug_systemjtag_jtag_TCK                                                         (_inst_jtag_tunnel_jtag_tck),	// @[fpga/fpga-shells/src/main/scala/ip/xilinx/bscan/bscan.scala:8:34]
    .debug_systemjtag_jtag_TMS                                                         (_inst_jtag_tunnel_jtag_tms),	// @[fpga/fpga-shells/src/main/scala/ip/xilinx/bscan/bscan.scala:8:34]
    .debug_systemjtag_jtag_TDI                                                         (_inst_jtag_tunnel_jtag_tdi),	// @[fpga/fpga-shells/src/main/scala/ip/xilinx/bscan/bscan.scala:8:34]
    .debug_systemjtag_jtag_TDO_data                                                    (_system_debug_systemjtag_jtag_TDO_data),
    .debug_systemjtag_jtag_TDO_driven                                                  (_system_debug_systemjtag_jtag_TDO_driven),
    .debug_systemjtag_reset                                                            (_system_debug_systemjtag_reset_catcher_io_sync_reset),	// @[generators/rocket-chip/src/main/scala/util/ResetCatchAndSync.scala:39:28]
    .debug_dmactive                                                                    (_system_debug_dmactive),
    .debug_dmactiveAck                                                                 (_dmactiveAck_dmactiveAck_io_q),	// @[generators/rocket-chip/src/main/scala/util/ShiftReg.scala:45:23]
    .mem_axi4_0_aw_ready                                                               (axi4_mem_0_bits_aw_ready),
    .mem_axi4_0_aw_valid                                                               (axi4_mem_0_bits_aw_valid),
    .mem_axi4_0_aw_bits_id                                                             (axi4_mem_0_bits_aw_bits_id),
    .mem_axi4_0_aw_bits_addr                                                           (axi4_mem_0_bits_aw_bits_addr),
    .mem_axi4_0_aw_bits_len                                                            (axi4_mem_0_bits_aw_bits_len),
    .mem_axi4_0_aw_bits_size                                                           (axi4_mem_0_bits_aw_bits_size),
    .mem_axi4_0_aw_bits_burst                                                          (axi4_mem_0_bits_aw_bits_burst),
    .mem_axi4_0_aw_bits_lock                                                           (axi4_mem_0_bits_aw_bits_lock),
    .mem_axi4_0_aw_bits_cache                                                          (axi4_mem_0_bits_aw_bits_cache),
    .mem_axi4_0_aw_bits_prot                                                           (axi4_mem_0_bits_aw_bits_prot),
    .mem_axi4_0_aw_bits_qos                                                            (axi4_mem_0_bits_aw_bits_qos),
    .mem_axi4_0_w_ready                                                                (axi4_mem_0_bits_w_ready),
    .mem_axi4_0_w_valid                                                                (axi4_mem_0_bits_w_valid),
    .mem_axi4_0_w_bits_data                                                            (axi4_mem_0_bits_w_bits_data),
    .mem_axi4_0_w_bits_strb                                                            (axi4_mem_0_bits_w_bits_strb),
    .mem_axi4_0_w_bits_last                                                            (axi4_mem_0_bits_w_bits_last),
    .mem_axi4_0_b_ready                                                                (axi4_mem_0_bits_b_ready),
    .mem_axi4_0_b_valid                                                                (axi4_mem_0_bits_b_valid),
    .mem_axi4_0_b_bits_id                                                              (axi4_mem_0_bits_b_bits_id),
    .mem_axi4_0_b_bits_resp                                                            (axi4_mem_0_bits_b_bits_resp),
    .mem_axi4_0_ar_ready                                                               (axi4_mem_0_bits_ar_ready),
    .mem_axi4_0_ar_valid                                                               (axi4_mem_0_bits_ar_valid),
    .mem_axi4_0_ar_bits_id                                                             (axi4_mem_0_bits_ar_bits_id),
    .mem_axi4_0_ar_bits_addr                                                           (axi4_mem_0_bits_ar_bits_addr),
    .mem_axi4_0_ar_bits_len                                                            (axi4_mem_0_bits_ar_bits_len),
    .mem_axi4_0_ar_bits_size                                                           (axi4_mem_0_bits_ar_bits_size),
    .mem_axi4_0_ar_bits_burst                                                          (axi4_mem_0_bits_ar_bits_burst),
    .mem_axi4_0_ar_bits_lock                                                           (axi4_mem_0_bits_ar_bits_lock),
    .mem_axi4_0_ar_bits_cache                                                          (axi4_mem_0_bits_ar_bits_cache),
    .mem_axi4_0_ar_bits_prot                                                           (axi4_mem_0_bits_ar_bits_prot),
    .mem_axi4_0_ar_bits_qos                                                            (axi4_mem_0_bits_ar_bits_qos),
    .mem_axi4_0_r_ready                                                                (axi4_mem_0_bits_r_ready),
    .mem_axi4_0_r_valid                                                                (axi4_mem_0_bits_r_valid),
    .mem_axi4_0_r_bits_id                                                              (axi4_mem_0_bits_r_bits_id),
    .mem_axi4_0_r_bits_data                                                            (axi4_mem_0_bits_r_bits_data),
    .mem_axi4_0_r_bits_resp                                                            (axi4_mem_0_bits_r_bits_resp),
    .mem_axi4_0_r_bits_last                                                            (axi4_mem_0_bits_r_bits_last),
    .mmio_axi4_0_aw_ready                                                              (axi4_mmio_0_bits_aw_ready),
    .mmio_axi4_0_aw_valid                                                              (axi4_mmio_0_bits_aw_valid),
    .mmio_axi4_0_aw_bits_id                                                            (axi4_mmio_0_bits_aw_bits_id),
    .mmio_axi4_0_aw_bits_addr                                                          (axi4_mmio_0_bits_aw_bits_addr),
    .mmio_axi4_0_aw_bits_len                                                           (axi4_mmio_0_bits_aw_bits_len),
    .mmio_axi4_0_aw_bits_size                                                          (axi4_mmio_0_bits_aw_bits_size),
    .mmio_axi4_0_aw_bits_burst                                                         (axi4_mmio_0_bits_aw_bits_burst),
    .mmio_axi4_0_aw_bits_lock                                                          (axi4_mmio_0_bits_aw_bits_lock),
    .mmio_axi4_0_aw_bits_cache                                                         (axi4_mmio_0_bits_aw_bits_cache),
    .mmio_axi4_0_aw_bits_prot                                                          (axi4_mmio_0_bits_aw_bits_prot),
    .mmio_axi4_0_aw_bits_qos                                                           (axi4_mmio_0_bits_aw_bits_qos),
    .mmio_axi4_0_w_ready                                                               (axi4_mmio_0_bits_w_ready),
    .mmio_axi4_0_w_valid                                                               (axi4_mmio_0_bits_w_valid),
    .mmio_axi4_0_w_bits_data                                                           (axi4_mmio_0_bits_w_bits_data),
    .mmio_axi4_0_w_bits_strb                                                           (axi4_mmio_0_bits_w_bits_strb),
    .mmio_axi4_0_w_bits_last                                                           (axi4_mmio_0_bits_w_bits_last),
    .mmio_axi4_0_b_ready                                                               (axi4_mmio_0_bits_b_ready),
    .mmio_axi4_0_b_valid                                                               (axi4_mmio_0_bits_b_valid),
    .mmio_axi4_0_b_bits_id                                                             (axi4_mmio_0_bits_b_bits_id),
    .mmio_axi4_0_b_bits_resp                                                           (axi4_mmio_0_bits_b_bits_resp),
    .mmio_axi4_0_ar_ready                                                              (axi4_mmio_0_bits_ar_ready),
    .mmio_axi4_0_ar_valid                                                              (axi4_mmio_0_bits_ar_valid),
    .mmio_axi4_0_ar_bits_id                                                            (axi4_mmio_0_bits_ar_bits_id),
    .mmio_axi4_0_ar_bits_addr                                                          (axi4_mmio_0_bits_ar_bits_addr),
    .mmio_axi4_0_ar_bits_len                                                           (axi4_mmio_0_bits_ar_bits_len),
    .mmio_axi4_0_ar_bits_size                                                          (axi4_mmio_0_bits_ar_bits_size),
    .mmio_axi4_0_ar_bits_burst                                                         (axi4_mmio_0_bits_ar_bits_burst),
    .mmio_axi4_0_ar_bits_lock                                                          (axi4_mmio_0_bits_ar_bits_lock),
    .mmio_axi4_0_ar_bits_cache                                                         (axi4_mmio_0_bits_ar_bits_cache),
    .mmio_axi4_0_ar_bits_prot                                                          (axi4_mmio_0_bits_ar_bits_prot),
    .mmio_axi4_0_ar_bits_qos                                                           (axi4_mmio_0_bits_ar_bits_qos),
    .mmio_axi4_0_r_ready                                                               (axi4_mmio_0_bits_r_ready),
    .mmio_axi4_0_r_valid                                                               (axi4_mmio_0_bits_r_valid),
    .mmio_axi4_0_r_bits_id                                                             (axi4_mmio_0_bits_r_bits_id),
    .mmio_axi4_0_r_bits_data                                                           (axi4_mmio_0_bits_r_bits_data),
    .mmio_axi4_0_r_bits_resp                                                           (axi4_mmio_0_bits_r_bits_resp),
    .mmio_axi4_0_r_bits_last                                                           (axi4_mmio_0_bits_r_bits_last),
    .l2_frontend_bus_axi4_0_aw_ready                                                   (axi4_fbus_0_bits_aw_ready),
    .l2_frontend_bus_axi4_0_aw_valid                                                   (axi4_fbus_0_bits_aw_valid),
    .l2_frontend_bus_axi4_0_aw_bits_id                                                 (axi4_fbus_0_bits_aw_bits_id),
    .l2_frontend_bus_axi4_0_aw_bits_addr                                               (axi4_fbus_0_bits_aw_bits_addr),
    .l2_frontend_bus_axi4_0_aw_bits_len                                                (axi4_fbus_0_bits_aw_bits_len),
    .l2_frontend_bus_axi4_0_aw_bits_size                                               (axi4_fbus_0_bits_aw_bits_size),
    .l2_frontend_bus_axi4_0_aw_bits_burst                                              (axi4_fbus_0_bits_aw_bits_burst),
    .l2_frontend_bus_axi4_0_aw_bits_lock                                               (axi4_fbus_0_bits_aw_bits_lock),
    .l2_frontend_bus_axi4_0_aw_bits_cache                                              (axi4_fbus_0_bits_aw_bits_cache),
    .l2_frontend_bus_axi4_0_aw_bits_prot                                               (axi4_fbus_0_bits_aw_bits_prot),
    .l2_frontend_bus_axi4_0_aw_bits_qos                                                (axi4_fbus_0_bits_aw_bits_qos),
    .l2_frontend_bus_axi4_0_w_ready                                                    (axi4_fbus_0_bits_w_ready),
    .l2_frontend_bus_axi4_0_w_valid                                                    (axi4_fbus_0_bits_w_valid),
    .l2_frontend_bus_axi4_0_w_bits_data                                                (axi4_fbus_0_bits_w_bits_data),
    .l2_frontend_bus_axi4_0_w_bits_strb                                                (axi4_fbus_0_bits_w_bits_strb),
    .l2_frontend_bus_axi4_0_w_bits_last                                                (axi4_fbus_0_bits_w_bits_last),
    .l2_frontend_bus_axi4_0_b_ready                                                    (axi4_fbus_0_bits_b_ready),
    .l2_frontend_bus_axi4_0_b_valid                                                    (axi4_fbus_0_bits_b_valid),
    .l2_frontend_bus_axi4_0_b_bits_id                                                  (axi4_fbus_0_bits_b_bits_id),
    .l2_frontend_bus_axi4_0_b_bits_resp                                                (axi4_fbus_0_bits_b_bits_resp),
    .l2_frontend_bus_axi4_0_ar_ready                                                   (axi4_fbus_0_bits_ar_ready),
    .l2_frontend_bus_axi4_0_ar_valid                                                   (axi4_fbus_0_bits_ar_valid),
    .l2_frontend_bus_axi4_0_ar_bits_id                                                 (axi4_fbus_0_bits_ar_bits_id),
    .l2_frontend_bus_axi4_0_ar_bits_addr                                               (axi4_fbus_0_bits_ar_bits_addr),
    .l2_frontend_bus_axi4_0_ar_bits_len                                                (axi4_fbus_0_bits_ar_bits_len),
    .l2_frontend_bus_axi4_0_ar_bits_size                                               (axi4_fbus_0_bits_ar_bits_size),
    .l2_frontend_bus_axi4_0_ar_bits_burst                                              (axi4_fbus_0_bits_ar_bits_burst),
    .l2_frontend_bus_axi4_0_ar_bits_lock                                               (axi4_fbus_0_bits_ar_bits_lock),
    .l2_frontend_bus_axi4_0_ar_bits_cache                                              (axi4_fbus_0_bits_ar_bits_cache),
    .l2_frontend_bus_axi4_0_ar_bits_prot                                               (axi4_fbus_0_bits_ar_bits_prot),
    .l2_frontend_bus_axi4_0_ar_bits_qos                                                (axi4_fbus_0_bits_ar_bits_qos),
    .l2_frontend_bus_axi4_0_r_ready                                                    (axi4_fbus_0_bits_r_ready),
    .l2_frontend_bus_axi4_0_r_valid                                                    (axi4_fbus_0_bits_r_valid),
    .l2_frontend_bus_axi4_0_r_bits_id                                                  (axi4_fbus_0_bits_r_bits_id),
    .l2_frontend_bus_axi4_0_r_bits_data                                                (axi4_fbus_0_bits_r_bits_data),
    .l2_frontend_bus_axi4_0_r_bits_resp                                                (axi4_fbus_0_bits_r_bits_resp),
    .l2_frontend_bus_axi4_0_r_bits_last                                                (axi4_fbus_0_bits_r_bits_last),
    .custom_boot                                                                       (_iocell_custom_boot_i),	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .uart_0_txd                                                                        (uart_0_txd),
    .uart_0_rxd                                                                        (uart_0_rxd),
    .clock_tap                                                                         (_system_clock_tap)
  );	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35]
  GenericDigitalInIOCell iocell_custom_boot (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .pad (custom_boot),
    .i   (_iocell_custom_boot_i),
    .ie  (1'h1)
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  AsyncResetSynchronizerShiftReg_w1_d3_i0 debug_reset_syncd_debug_reset_sync (	// @[generators/rocket-chip/src/main/scala/util/ShiftReg.scala:45:23]
    .clock (_system_auto_cbus_fixedClockNode_anon_out_clock),	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35]
    .reset (_system_debug_systemjtag_reset_catcher_io_sync_reset),	// @[generators/rocket-chip/src/main/scala/util/ResetCatchAndSync.scala:39:28]
    .io_d  (1'h1),
    .io_q  (_debug_reset_syncd_debug_reset_sync_io_q)
  );	// @[generators/rocket-chip/src/main/scala/util/ShiftReg.scala:45:23]
  ResetSynchronizerShiftReg_w1_d3_i0 dmactiveAck_dmactiveAck (	// @[generators/rocket-chip/src/main/scala/util/ShiftReg.scala:45:23]
    .clock (_system_auto_cbus_fixedClockNode_anon_out_clock),	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35]
    .reset (~_debug_reset_syncd_debug_reset_sync_io_q),	// @[generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:292:40, generators/rocket-chip/src/main/scala/util/ShiftReg.scala:45:23]
    .io_d  (_system_debug_dmactive),	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35]
    .io_q  (_dmactiveAck_dmactiveAck_io_q)
  );	// @[generators/rocket-chip/src/main/scala/util/ShiftReg.scala:45:23]
  JTAGTUNNEL inst_jtag_tunnel (	// @[fpga/fpga-shells/src/main/scala/ip/xilinx/bscan/bscan.scala:8:34]
    .jtag_tck    (_inst_jtag_tunnel_jtag_tck),
    .jtag_tms    (_inst_jtag_tunnel_jtag_tms),
    .jtag_tdi    (_inst_jtag_tunnel_jtag_tdi),
    .jtag_tdo    (_system_debug_systemjtag_jtag_TDO_data),	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35]
    .jtag_tdo_en (_system_debug_systemjtag_jtag_TDO_driven)	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35]
  );	// @[fpga/fpga-shells/src/main/scala/ip/xilinx/bscan/bscan.scala:8:34]
  ResetCatchAndSync_d3 system_debug_systemjtag_reset_catcher (	// @[generators/rocket-chip/src/main/scala/util/ResetCatchAndSync.scala:39:28]
    .clock         (_inst_jtag_tunnel_jtag_tck),	// @[fpga/fpga-shells/src/main/scala/ip/xilinx/bscan/bscan.scala:8:34]
    .reset         (_system_auto_cbus_fixedClockNode_anon_out_reset),	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35]
    .io_sync_reset (_system_debug_systemjtag_reset_catcher_io_sync_reset)
  );	// @[generators/rocket-chip/src/main/scala/util/ResetCatchAndSync.scala:39:28]
  GenericDigitalOutIOCell iocell_clock_tap (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
    .pad (clock_tap),
    .o   (_system_clock_tap),	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35]
    .oe  (1'h1)
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
endmodule

