// Generated by CIRCT firtool-1.75.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module LoopConvExecute(	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:615:7]
  input         clock,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:615:7]
  input         reset,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:615:7]
  output        io_req_ready,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:619:14]
  input         io_req_valid,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:619:14]
  input  [15:0] io_req_bits_outer_bounds_stride,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:619:14]
  input  [15:0] io_req_bits_outer_bounds_kernel_dilation,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:619:14]
  input  [15:0] io_req_bits_inner_bounds_batches,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:619:14]
  input  [15:0] io_req_bits_inner_bounds_krows,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:619:14]
  input  [15:0] io_req_bits_inner_bounds_kcols,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:619:14]
  input  [15:0] io_req_bits_inner_bounds_kchs,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:619:14]
  input  [15:0] io_req_bits_inner_bounds_lpad,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:619:14]
  input  [15:0] io_req_bits_inner_bounds_upad,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:619:14]
  input  [15:0] io_req_bits_inner_bounds_orows,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:619:14]
  input  [15:0] io_req_bits_inner_bounds_ocols,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:619:14]
  input  [15:0] io_req_bits_derived_params_ochs,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:619:14]
  input  [15:0] io_req_bits_derived_params_irows,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:619:14]
  input  [15:0] io_req_bits_derived_params_icols,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:619:14]
  input  [15:0] io_req_bits_derived_params_out_channels_per_bank,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:619:14]
  input  [15:0] io_req_bits_derived_params_in_channels_per_bank,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:619:14]
  input  [15:0] io_req_bits_derived_params_input_spad_stride,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:619:14]
  input         io_req_bits_viEligible,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:619:14]
  input         io_req_bits_viCrossRow,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:619:14]
  input  [15:0] io_req_bits_viGeneration,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:619:14]
  input  [14:0] io_req_bits_a_addr_start,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:619:14]
  input  [15:0] io_req_bits_b_addr_end,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:619:14]
  input  [11:0] io_req_bits_c_addr_start,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:619:14]
  input         io_req_bits_wrot180,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:619:14]
  input         io_req_bits_downsample,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:619:14]
  input  [15:0] io_req_bits_max_pixels_per_row,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:619:14]
  input         io_req_bits_input_dilated,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:619:14]
  input         io_req_bits_trans_weight_0132,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:619:14]
  input         io_req_bits_trans_input_3120,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:619:14]
  input         io_req_bits_loop_id,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:619:14]
  input         io_cmd_ready,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:619:14]
  output        io_cmd_valid,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:619:14]
  output [6:0]  io_cmd_bits_inst_funct,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:619:14]
  output [63:0] io_cmd_bits_rs1,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:619:14]
  output [63:0] io_cmd_bits_rs2,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:619:14]
  output        io_virtualI_valid,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:619:14]
  output [31:0] io_virtualI_desc_input_base,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:619:14]
  output [31:0] io_virtualI_desc_input_limit,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:619:14]
  output [31:0] io_virtualI_desc_input_channelStride,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:619:14]
  output [31:0] io_virtualI_desc_input_batchStride,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:619:14]
  output [31:0] io_virtualI_desc_input_rowStride,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:619:14]
  output [15:0] io_virtualI_desc_input_residentH,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:619:14]
  output [15:0] io_virtualI_desc_input_residentW,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:619:14]
  output [15:0] io_virtualI_desc_input_batches,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:619:14]
  output [15:0] io_virtualI_desc_input_channelBlocks,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:619:14]
  output [31:0] io_virtualI_desc_output_base,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:619:14]
  output [15:0] io_virtualI_desc_output_groups,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:619:14]
  output [15:0] io_virtualI_desc_owner,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:619:14]
  output [15:0] io_virtualI_desc_generation,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:619:14]
  output        io_virtualI_desc_segment,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:619:14]
  output [15:0] io_virtualI_desc_startB,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:619:14]
  output [15:0] io_virtualI_desc_startR,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:619:14]
  output [15:0] io_virtualI_desc_startC,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:619:14]
  output [6:0]  io_virtualI_desc_segmentRows,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:619:14]
  output [15:0] io_virtualI_desc_batches,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:619:14]
  output [15:0] io_virtualI_desc_tileRows,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:619:14]
  output [15:0] io_virtualI_desc_tileCols,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:619:14]
  output [15:0] io_virtualI_desc_batchStart,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:619:14]
  output [15:0] io_virtualI_desc_outputY,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:619:14]
  output [15:0] io_virtualI_desc_outputX,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:619:14]
  output [15:0] io_virtualI_desc_inputH,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:619:14]
  output [15:0] io_virtualI_desc_inputW,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:619:14]
  output [15:0] io_virtualI_desc_kernelY,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:619:14]
  output [15:0] io_virtualI_desc_kernelX,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:619:14]
  output [15:0] io_virtualI_desc_dilationY,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:619:14]
  output [15:0] io_virtualI_desc_dilationX,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:619:14]
  output [15:0] io_virtualI_desc_channelBlock,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:619:14]
  output [15:0] io_virtualI_desc_outputGroup,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:619:14]
  output [6:0]  io_virtualI_desc_kValid,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:619:14]
  output [6:0]  io_virtualI_desc_jValid,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:619:14]
  input         io_lda_completed,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:619:14]
  input         io_ldb_completed,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:619:14]
  input         io_ldd_completed,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:619:14]
  output        io_idle,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:619:14]
  input         io_rob_overloaded,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:619:14]
  output        io_loop_id	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:619:14]
);

  wire        _command_p_io_in_ready;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:741:25]
  wire        _command_p_io_out_valid;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:741:25]
  wire [6:0]  _command_p_io_out_bits_cmd_inst_funct;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:741:25]
  wire [63:0] _command_p_io_out_bits_cmd_rs1;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:741:25]
  wire [63:0] _command_p_io_out_bits_cmd_rs2;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:741:25]
  wire [51:0] _command_p_io_out_bits_a_addr;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:741:25]
  wire [67:0] _command_p_io_out_bits_b_addr;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:741:25]
  wire [67:0] _command_p_io_out_bits_c_addr;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:741:25]
  wire [32:0] _command_p_io_out_bits_I;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:741:25]
  wire [15:0] _command_p_io_out_bits_J;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:741:25]
  wire [31:0] _command_p_io_out_bits_K;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:741:25]
  wire        _command_p_io_out_bits_new_weights;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:741:25]
  wire        _command_p_io_busy;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:741:25]
  reg  [1:0]  state;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:638:22]
  reg  [15:0] req_outer_bounds_stride;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16]
  reg  [15:0] req_outer_bounds_kernel_dilation;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16]
  reg  [15:0] req_inner_bounds_batches;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16]
  reg  [15:0] req_inner_bounds_krows;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16]
  reg  [15:0] req_inner_bounds_kcols;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16]
  reg  [15:0] req_inner_bounds_kchs;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16]
  reg  [15:0] req_inner_bounds_lpad;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16]
  reg  [15:0] req_inner_bounds_upad;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16]
  reg  [15:0] req_inner_bounds_orows;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16]
  reg  [15:0] req_inner_bounds_ocols;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16]
  reg  [15:0] req_derived_params_ochs;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16]
  reg  [15:0] req_derived_params_irows;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16]
  reg  [15:0] req_derived_params_icols;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16]
  reg  [15:0] req_derived_params_out_channels_per_bank;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16]
  reg  [15:0] req_derived_params_in_channels_per_bank;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16]
  reg  [15:0] req_derived_params_input_spad_stride;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16]
  reg         req_viEligible;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16]
  reg  [15:0] req_viGeneration;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16]
  reg  [14:0] req_a_addr_start;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16]
  reg  [15:0] req_b_addr_end;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16]
  reg  [11:0] req_c_addr_start;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16]
  reg         req_wrot180;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16]
  reg         req_downsample;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16]
  reg  [15:0] req_max_pixels_per_row;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16]
  reg         req_input_dilated;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16]
  reg         req_trans_weight_0132;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16]
  reg         req_trans_input_3120;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16]
  reg         req_loop_id;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16]
  wire [31:0] _GEN = {16'h0, req_derived_params_in_channels_per_bank};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16, :649:64]
  wire [31:0] _GEN_0 = {16'h0, req_inner_bounds_kcols};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16, :649:64]
  wire [47:0] _GEN_1 = {32'h0, req_inner_bounds_krows};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16, :649:72, :823:7]
  wire [63:0] _GEN_2 = {48'h0, req_derived_params_ochs};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16, :649:80]
  wire [63:0] _GEN_3 = {48'h0, req_inner_bounds_kchs};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16, :650:43]
  reg         crossRows;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:661:26]
  reg  [15:0] och;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:677:16]
  reg  [15:0] krow;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:678:17]
  reg  [15:0] kcol;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:679:17]
  reg  [15:0] kch;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:680:16]
  reg  [15:0] b;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:681:14]
  reg  [15:0] orow;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:682:17]
  reg  [15:0] ocol;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:683:17]
  wire [31:0] _GEN_4 = {16'h0, req_outer_bounds_kernel_dilation};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16, :686:69]
  wire [31:0] _irow_T_1 = {16'h0, krow} * _GEN_4;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:678:17, :686:69]
  wire [31:0] _icol_T_1 = {16'h0, kcol} * _GEN_4;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:679:17, :686:69, :687:12]
  wire        skip_iteration = state[1] & req_input_dilated & (_irow_T_1[0] + orow[0] - req_inner_bounds_upad[0] & req_input_dilated | _icol_T_1[0] + ocol[0] - req_inner_bounds_lpad[0] & req_input_dilated);	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:638:22, :640:16, :682:17, :683:17, :686:{30,37,58,69,87,95,107,135}, :687:{12,30,38,50}]
  wire [15:0] _kcol_rot_T = req_inner_bounds_kcols - kcol;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16, :679:17, :689:26]
  wire [31:0] _GEN_5 = {16'h0, orow};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:682:17, :691:29]
  wire [31:0] _GEN_6 = {16'h0, req_outer_bounds_stride};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16, :691:29]
  wire [33:0] _GEN_7 = {33'h0, req_input_dilated};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16, :646:37]
  wire [33:0] irow = {1'h0, {1'h0, _GEN_5 * _GEN_6} + {1'h0, _irow_T_1}} + _GEN_7 >> _GEN_7;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:646:{37,59}, :686:{69,87}, :691:{29,38}]
  wire [33:0] icol = {1'h0, {1'h0, {16'h0, ocol} * _GEN_6} + {1'h0, _icol_T_1}} + _GEN_7 >> _GEN_7;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:646:{37,59}, :683:17, :687:{12,30}, :691:29, :692:{29,38}]
  wire [15:0] _legacyI_T_3 = req_inner_bounds_batches - b;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16, :681:14, :695:17]
  wire [15:0] _legacyI_T_11 = req_inner_bounds_ocols - ocol;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16, :683:17, :696:25]
  wire [5:0]  _ocol_it_T_1 = 6'h10 << req_input_dilated;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16, :696:48]
  wire [15:0] _GEN_8 = {10'h0, _ocol_it_T_1};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:696:{32,48}]
  wire [16:0] _GEN_9 = {16'h0, req_input_dilated};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16, :646:37]
  wire [31:0] _GEN_10 = {16'h0, req_inner_bounds_orows};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16, :704:36]
  wire [31:0] _GEN_11 = {16'h0, req_inner_bounds_ocols};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16, :704:36]
  wire [31:0] _config_cmd_rs2_c_stride_T = _GEN_10 * _GEN_11;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:704:36]
  wire [31:0] _c_addr_T_8 = _GEN_5 * _GEN_11;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:691:29, :704:{36,52}]
  wire [32:0] _imagePixelsRemaining_T_3 = {1'h0, _config_cmd_rs2_c_stride_T} - ({1'h0, _c_addr_T_8} + {17'h0, ocol});	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:683:17, :687:30, :704:{36,44,52,60}]
  wire [32:0] I = crossRows ? (_imagePixelsRemaining_T_3 > 33'h10 ? 33'h10 : _imagePixelsRemaining_T_3) : {16'h0, req_trans_input_3120 ? {1'h0, _legacyI_T_3 > 16'h10 ? 16'h10 : _legacyI_T_3} : {1'h0, _legacyI_T_11 > _GEN_8 ? _GEN_8 : _legacyI_T_11} + _GEN_9 >> _GEN_9};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16, :646:{37,59}, :661:26, :694:20, :695:{8,17,21}, :696:{18,25,32}, :704:44, :705:{14,29,51}]
  wire [15:0] _J_T_3 = req_derived_params_ochs - och;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16, :677:16, :706:20]
  wire [15:0] J = _J_T_3 > 16'h10 ? 16'h10 : _J_T_3;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:695:21, :706:{14,20,26}]
  wire [15:0] _K_T_3 = req_inner_bounds_kchs - kch;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16, :680:16, :707:29]
  wire [31:0] K = {16'h0, _kcol_rot_T > req_max_pixels_per_row ? req_max_pixels_per_row : _kcol_rot_T} * {16'h0, _K_T_3 > 16'h10 ? 16'h10 : _K_T_3};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16, :689:{19,26,33}, :695:21, :707:{18,23,29,35}]
  wire [31:0] vi_desc_input_channelStride = {16'h0, req_derived_params_input_spad_stride};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16, :711:40]
  wire [32:0] _GEN_12 = {18'h0, req_a_addr_start};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16, :711:18]
  wire [15:0] _GEN_13 = {15'h0, req_downsample};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16, :711:76]
  wire [31:0] _GEN_14 = {16'h0, req_derived_params_irows >> _GEN_13};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16, :711:{67,76}]
  wire [15:0] _a_addr_T_23 = req_derived_params_icols >> _GEN_13;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16, :711:{76,104}]
  wire [47:0] _GEN_15 = {32'h0, _a_addr_T_23};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:711:{95,104}, :823:7]
  wire [33:0] _GEN_16 = {33'h0, req_downsample};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16, :646:37, :711:132]
  wire [49:0] _GEN_17 = {16'h0, irow >> _GEN_16};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:646:59, :711:{132,151}]
  wire [49:0] _GEN_18 = {34'h0, _a_addr_T_23};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:711:{104,151}]
  wire [51:0] _GEN_19 = {18'h0, icol >> _GEN_16};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:646:59, :711:{132,179,188}]
  wire [31:0] _GEN_20 = {16'h0, kch / 16'h10};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:680:16, :695:21, :712:{26,58}]
  wire [31:0] _GEN_21 = {16'h0, b};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:681:14, :712:83]
  wire [31:0] _GEN_22 = {16'h0, och / 16'h10};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:677:16, :695:21, :719:{10,42}]
  wire [67:0] c_addr = {1'h0, {1'h0, {1'h0, {53'h0, req_c_addr_start} + {1'h0, {16'h0, {16'h0, _GEN_22 * {16'h0, req_inner_bounds_batches}} * {32'h0, req_inner_bounds_orows}} * {48'h0, req_inner_bounds_ocols}}} + {18'h0, {16'h0, _GEN_21 * _GEN_10} * {32'h0, req_inner_bounds_ocols}}} + {35'h0, _c_addr_T_8}} + {52'h0, ocol};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16, :666:51, :669:61, :683:17, :704:{36,52}, :712:83, :718:29, :719:{42,52,60,68,73,81,89,105}, :823:7]
  reg         new_weights;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:722:24]
  wire [31:0] _GEN_23 = {16'h0, req_inner_bounds_krows};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16, :727:58]
  wire [47:0] _GEN_24 = {32'h0, req_inner_bounds_kcols};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16, :727:66, :823:7]
  wire [64:0] _GEN_25 = {1'h0, {48'h0, req_b_addr_end} - (req_trans_weight_0132 ? {16'h0, {16'h0, _GEN * _GEN_0} * _GEN_1} * _GEN_2 : {16'h0, {16'h0, {16'h0, req_derived_params_out_channels_per_bank} * _GEN_0} * _GEN_1} * _GEN_3)};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16, :649:{19,64,72,80}, :650:{27,35,43}, :673:37, :727:18]
  wire [47:0] _GEN_26 = {16'h0, {16'h0, req_wrot180 ? req_inner_bounds_krows - krow - 16'h1 : krow} * _GEN_0};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16, :649:64, :678:17, :723:{21,41,48}, :727:{93,101}]
  wire [31:0] _GEN_27 = {16'h0, req_wrot180 ? _kcol_rot_T - 16'h1 : kcol};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16, :679:17, :689:26, :724:{21,48}, :727:120]
  wire [31:0] vi_desc_input_rowStride = {16'h0, req_derived_params_icols};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16, :754:37]
  wire [31:0] vi_desc_input_batchStride = {16'h0, req_derived_params_irows} * vi_desc_input_rowStride;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16, :754:37]
  wire        _io_idle_T = state == 2'h0;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:638:22, :780:25]
  wire        io_req_ready_0 = _io_idle_T & ~_command_p_io_busy;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:741:25, :780:{25,34,37}]
  wire        command_p_io_in_valid = (|state) & ~skip_iteration & io_lda_completed & io_ldb_completed & io_ldd_completed;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:638:22, :686:{37,58}, :777:{35,55}, :784:{34,43,46,62}]
  wire        _command_p_io_in_bits_cmd_T = state == 2'h2;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:638:22, :785:62]
  wire        _GEN_28 = _command_p_io_in_bits_cmd_T | (&state);	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:638:22, :785:{62,90}, src/main/scala/chisel3/util/Mux.scala:126:16]
  wire [31:0] _vi_valid_T_4 = vi_desc_input_channelStride * _GEN;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:649:64, :711:40, :810:59]
  wire [15:0] vi_desc_dilationX = crossRows ? req_outer_bounds_kernel_dilation : 16'h1;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16, :661:26, :801:14, :806:16, :831:19, :839:18]
  wire        _GEN_29 = _command_p_io_out_bits_cmd_inst_funct == 7'h6;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:741:25, :767:22, :850:46]
  wire        _GEN_30 = io_req_ready_0 & io_req_valid;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:780:34, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire        _GEN_31 = _command_p_io_in_ready & command_p_io_in_valid;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:741:25, :777:{35,55}, :784:{43,62}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire        _GEN_32 = _GEN_31 | skip_iteration;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:686:{37,58}, :895:30, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire        _GEN_33 = state == 2'h1;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:638:22, :896:17]
  wire [33:0] remainder = {18'h0, ocol} + {1'h0, I};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:683:17, :705:14, generators/gemmini/src/main/scala/gemmini/VirtualIRowAdvance.scala:16:32]
  wire [33:0] _GEN_34 = {12'h0, req_inner_bounds_ocols, 6'h0};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16, generators/gemmini/src/main/scala/gemmini/VirtualIRowAdvance.scala:19:34, :20:45]
  wire        take = (|req_inner_bounds_ocols) & remainder >= _GEN_34;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16, generators/gemmini/src/main/scala/gemmini/VirtualIRowAdvance.scala:16:32, :20:{24,32,45}]
  wire [33:0] _GEN_35 = take ? remainder - _GEN_34 : remainder;	// @[generators/gemmini/src/main/scala/gemmini/VirtualIRowAdvance.scala:16:32, :20:{32,45}, :21:{22,39}]
  wire [33:0] _GEN_36 = {13'h0, req_inner_bounds_ocols, 5'h0};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:615:7, :640:16, generators/gemmini/src/main/scala/gemmini/VirtualIRowAdvance.scala:20:45]
  wire        take_1 = (|req_inner_bounds_ocols) & _GEN_35 >= _GEN_36;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16, generators/gemmini/src/main/scala/gemmini/VirtualIRowAdvance.scala:20:{24,32,45}, :21:22]
  wire [33:0] _GEN_37 = take_1 ? _GEN_35 - _GEN_36 : _GEN_35;	// @[generators/gemmini/src/main/scala/gemmini/VirtualIRowAdvance.scala:20:{32,45}, :21:{22,39}]
  wire [33:0] _GEN_38 = {14'h0, req_inner_bounds_ocols, 4'h0};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16, :773:23, generators/gemmini/src/main/scala/gemmini/VirtualIRowAdvance.scala:20:45]
  wire        take_2 = (|req_inner_bounds_ocols) & _GEN_37 >= _GEN_38;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16, generators/gemmini/src/main/scala/gemmini/VirtualIRowAdvance.scala:20:{24,32,45}, :21:22]
  wire [33:0] _GEN_39 = take_2 ? _GEN_37 - _GEN_38 : _GEN_37;	// @[generators/gemmini/src/main/scala/gemmini/VirtualIRowAdvance.scala:20:{32,45}, :21:{22,39}]
  wire [33:0] _GEN_40 = {15'h0, req_inner_bounds_ocols, 3'h0};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16, generators/gemmini/src/main/scala/gemmini/VirtualIRowAdvance.scala:20:45]
  wire        take_3 = (|req_inner_bounds_ocols) & _GEN_39 >= _GEN_40;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16, generators/gemmini/src/main/scala/gemmini/VirtualIRowAdvance.scala:20:{24,32,45}, :21:22]
  wire [33:0] _GEN_41 = take_3 ? _GEN_39 - _GEN_40 : _GEN_39;	// @[generators/gemmini/src/main/scala/gemmini/VirtualIRowAdvance.scala:20:{32,45}, :21:{22,39}]
  wire [33:0] _GEN_42 = {16'h0, req_inner_bounds_ocols, 2'h0};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:638:22, :640:16, generators/gemmini/src/main/scala/gemmini/VirtualIRowAdvance.scala:20:45]
  wire        take_4 = (|req_inner_bounds_ocols) & _GEN_41 >= _GEN_42;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16, generators/gemmini/src/main/scala/gemmini/VirtualIRowAdvance.scala:20:{24,32,45}, :21:22]
  wire [33:0] _GEN_43 = take_4 ? _GEN_41 - _GEN_42 : _GEN_41;	// @[generators/gemmini/src/main/scala/gemmini/VirtualIRowAdvance.scala:20:{32,45}, :21:{22,39}]
  wire [33:0] _GEN_44 = {17'h0, req_inner_bounds_ocols, 1'h0};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16, generators/gemmini/src/main/scala/gemmini/VirtualIRowAdvance.scala:20:45]
  wire        take_5 = (|req_inner_bounds_ocols) & _GEN_43 >= _GEN_44;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16, generators/gemmini/src/main/scala/gemmini/VirtualIRowAdvance.scala:20:{24,32,45}, :21:22]
  wire [33:0] _GEN_45 = take_5 ? _GEN_43 - _GEN_44 : _GEN_43;	// @[generators/gemmini/src/main/scala/gemmini/VirtualIRowAdvance.scala:20:{32,45}, :21:{22,39}]
  wire [33:0] _GEN_46 = {18'h0, req_inner_bounds_ocols};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16, generators/gemmini/src/main/scala/gemmini/VirtualIRowAdvance.scala:20:45]
  wire        take_6 = (|req_inner_bounds_ocols) & _GEN_45 >= _GEN_46;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16, generators/gemmini/src/main/scala/gemmini/VirtualIRowAdvance.scala:20:{24,32,45}, :21:22]
  wire        imageEnd = I == _imagePixelsRemaining_T_3;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:704:44, :705:14, :912:24]
  wire [16:0] _next_ocol_T_4 = {1'h0, ocol} + {11'h0, skip_iteration | req_trans_input_3120 ? 6'h1 : _ocol_it_T_1};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16, :683:17, :686:{37,58}, :696:{25,48}, :902:{24,40}, generators/gemmini/src/main/scala/gemmini/Util.scala:41:15]
  wire [33:0] next_ocol = crossRows ? (imageEnd ? 34'h0 : take_6 ? _GEN_45 - _GEN_46 : _GEN_45) : {18'h0, _next_ocol_T_4 > {1'h0, req_inner_bounds_ocols - 16'h1} ? 16'h0 : _next_ocol_T_4[15:0]};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16, :661:26, :912:24, :913:{26,41}, generators/gemmini/src/main/scala/gemmini/Util.scala:39:28, :41:15, :43:17, generators/gemmini/src/main/scala/gemmini/VirtualIRowAdvance.scala:19:29, :20:{32,45}, :21:{22,39}, src/main/scala/chisel3/util/Mux.scala:126:16]
  wire [16:0] _GEN_47 = {1'h0, orow};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:682:17, :914:62]
  wire [16:0] _next_orow_T_6 = _GEN_47 + 17'h1;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:914:62, generators/gemmini/src/main/scala/gemmini/Util.scala:41:15]
  wire [16:0] next_orow = crossRows ? (imageEnd ? 17'h0 : _GEN_47 + {10'h0, take, take_1, take_2, take_3, take_4, take_5, take_6}) : {1'h0, (|next_ocol) ? orow : _next_orow_T_6 > {1'h0, req_inner_bounds_orows - 16'h1} ? 16'h0 : _next_orow_T_6[15:0]};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16, :661:26, :682:17, :912:24, :913:26, :914:{26,41,62,114}, generators/gemmini/src/main/scala/gemmini/Util.scala:39:28, :41:15, :43:17, generators/gemmini/src/main/scala/gemmini/VirtualIRowAdvance.scala:20:32, src/main/scala/chisel3/util/Mux.scala:126:16]
  wire        _state_T_9 = next_orow == 17'h0;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:914:26, :915:57]
  wire        _next_b_T_2 = _state_T_9 & ~(|next_ocol);	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:913:26, :914:114, :915:{57,65}]
  wire [16:0] _next_b_T_6 = {1'h0, b} + {12'h0, req_trans_input_3120 ? 5'h10 : 5'h1};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:615:7, :640:16, :681:14, :695:17, :901:21, generators/gemmini/src/main/scala/gemmini/Util.scala:41:15]
  wire [15:0] _next_b_T_8 = _next_b_T_6 > {1'h0, req_inner_bounds_batches - 16'h1} ? 16'h0 : _next_b_T_6[15:0];	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16, generators/gemmini/src/main/scala/gemmini/Util.scala:39:28, :41:15, :43:17, src/main/scala/chisel3/util/Mux.scala:126:16]
  wire        _state_T_7 = (_next_b_T_2 ? _next_b_T_8 : b) == 16'h0;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:681:14, :915:65, :917:16, src/main/scala/chisel3/util/Mux.scala:126:16]
  wire        _next_kch_T_4 = _state_T_7 & _state_T_9 & ~(|next_ocol);	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:913:26, :914:114, :915:57, :917:{16,24,45}]
  wire [16:0] _next_kch_T_8 = {1'h0, kch} + 17'h10;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:680:16, :707:29, generators/gemmini/src/main/scala/gemmini/Util.scala:41:15]
  wire [15:0] _next_kch_T_10 = _next_kch_T_8 > {1'h0, req_inner_bounds_kchs - 16'h1} ? 16'h0 : _next_kch_T_8[15:0];	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16, generators/gemmini/src/main/scala/gemmini/Util.scala:39:28, :41:15, :43:17, src/main/scala/chisel3/util/Mux.scala:126:16]
  wire        _state_T_5 = (_next_kch_T_4 ? _next_kch_T_10 : kch) == 16'h0;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:680:16, :917:{24,45}, :919:18, src/main/scala/chisel3/util/Mux.scala:126:16]
  wire        _next_kcol_T_6 = _state_T_5 & _state_T_7 & _state_T_9 & ~(|next_ocol);	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:913:26, :914:114, :915:57, :917:16, :919:{18,26,44,65}]
  wire [16:0] _next_kcol_T_10 = {1'h0, kcol} + {1'h0, req_max_pixels_per_row};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16, :679:17, :689:26, generators/gemmini/src/main/scala/gemmini/Util.scala:41:15]
  wire [15:0] _next_kcol_T_12 = _next_kcol_T_10 > {1'h0, req_inner_bounds_kcols - 16'h1} ? 16'h0 : _next_kcol_T_10[15:0];	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16, generators/gemmini/src/main/scala/gemmini/Util.scala:39:28, :41:15, :43:17, src/main/scala/chisel3/util/Mux.scala:126:16]
  wire        _state_T_3 = (_next_kcol_T_6 ? _next_kcol_T_12 : kcol) == 16'h0;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:679:17, :919:{26,44,65}, :921:19, src/main/scala/chisel3/util/Mux.scala:126:16]
  wire        _next_krow_T_8 = _state_T_3 & _state_T_5 & _state_T_7 & _state_T_9 & ~(|next_ocol);	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:913:26, :914:114, :915:57, :917:16, :919:18, :921:{19,27,47,65,86}]
  wire [16:0] _next_krow_T_12 = {1'h0, krow} + 17'h1;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:678:17, :723:41, generators/gemmini/src/main/scala/gemmini/Util.scala:41:15]
  wire [15:0] _next_krow_T_14 = _next_krow_T_12 > {1'h0, req_inner_bounds_krows - 16'h1} ? 16'h0 : _next_krow_T_12[15:0];	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16, generators/gemmini/src/main/scala/gemmini/Util.scala:39:28, :41:15, :43:17, src/main/scala/chisel3/util/Mux.scala:126:16]
  wire        _state_T_1 = (_next_krow_T_8 ? _next_krow_T_14 : krow) == 16'h0;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:678:17, :921:{27,47,65,86}, :922:66, src/main/scala/chisel3/util/Mux.scala:126:16]
  wire        _next_och_T_10 = _state_T_1 & _state_T_3 & _state_T_5 & _state_T_7 & _state_T_9 & ~(|next_ocol);	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:913:26, :914:114, :915:57, :917:16, :919:18, :921:19, :922:{66,74}, :923:{27,47,65,86}]
  wire [16:0] _next_och_T_14 = {1'h0, och} + 17'h10;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:677:16, :706:20, generators/gemmini/src/main/scala/gemmini/Util.scala:41:15]
  wire [15:0] _next_och_T_16 = _next_och_T_14 > {1'h0, req_derived_params_ochs - 16'h1} ? 16'h0 : _next_och_T_14[15:0];	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16, generators/gemmini/src/main/scala/gemmini/Util.scala:39:28, :41:15, :43:17, src/main/scala/chisel3/util/Mux.scala:126:16]
  wire        _GEN_48 = _GEN_33 | _command_p_io_in_bits_cmd_T;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:683:17, :785:62, :896:{17,29}, :898:32, :925:12]
  always @(posedge clock) begin	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:615:7]
    if (reset) begin	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:615:7]
      state <= 2'h0;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:638:22]
      crossRows <= 1'h0;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:661:26]
    end
    else if (_GEN_30) begin	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35]
      state <= io_req_bits_trans_input_3120 ? 2'h1 : 2'h2;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:638:22, :896:17, :946:17]
      crossRows <= io_req_bits_viEligible & io_req_bits_viCrossRow & {18'h0, io_req_bits_a_addr_start} + {1'h0, {16'h0, io_req_bits_derived_params_input_spad_stride} * {16'h0, io_req_bits_derived_params_in_channels_per_bank}} < 33'h8001 & {53'h0, io_req_bits_c_addr_start} + {1'h0, {16'h0, {16'h0, {16'h0, io_req_bits_inner_bounds_batches} * {16'h0, io_req_bits_inner_bounds_orows}} * {32'h0, io_req_bits_inner_bounds_ocols}} * {48'h0, io_req_bits_derived_params_out_channels_per_bank}} < 65'h1001 & (|io_req_bits_inner_bounds_orows) & (|io_req_bits_inner_bounds_ocols);	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:661:26, :663:{56,87}, :664:50, :665:48, :666:{51,70}, :668:{39,63}, :669:{25,39,61,79}, :670:{36,44,76}, :823:7]
    end
    else if (_GEN_32)	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:895:30]
      state <= _GEN_33 ? 2'h2 : _command_p_io_in_bits_cmd_T ? 2'h3 : {~((_next_och_T_10 ? _next_och_T_16 : och) == 16'h0 & _state_T_1 & _state_T_3 & _state_T_5 & _state_T_7 & _state_T_9 & ~(|next_ocol)), 1'h0};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:638:22, :677:16, :785:62, :896:{17,29}, :897:13, :898:32, :899:13, :913:26, :914:114, :915:57, :917:16, :919:18, :921:19, :922:{66,74}, :923:{27,47,65,86}, :937:{13,19,29,37,58,79,99,117}, :938:27, src/main/scala/chisel3/util/Mux.scala:126:16]
    if (_GEN_30) begin	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35]
      req_outer_bounds_stride <= io_req_bits_outer_bounds_stride;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16]
      req_outer_bounds_kernel_dilation <= io_req_bits_outer_bounds_kernel_dilation;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16]
      req_inner_bounds_batches <= io_req_bits_inner_bounds_batches;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16]
      req_inner_bounds_krows <= io_req_bits_inner_bounds_krows;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16]
      req_inner_bounds_kcols <= io_req_bits_inner_bounds_kcols;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16]
      req_inner_bounds_kchs <= io_req_bits_inner_bounds_kchs;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16]
      req_inner_bounds_lpad <= io_req_bits_inner_bounds_lpad;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16]
      req_inner_bounds_upad <= io_req_bits_inner_bounds_upad;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16]
      req_inner_bounds_orows <= io_req_bits_inner_bounds_orows;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16]
      req_inner_bounds_ocols <= io_req_bits_inner_bounds_ocols;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16]
      req_derived_params_ochs <= io_req_bits_derived_params_ochs;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16]
      req_derived_params_irows <= io_req_bits_derived_params_irows;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16]
      req_derived_params_icols <= io_req_bits_derived_params_icols;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16]
      req_derived_params_out_channels_per_bank <= io_req_bits_derived_params_out_channels_per_bank;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16]
      req_derived_params_in_channels_per_bank <= io_req_bits_derived_params_in_channels_per_bank;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16]
      req_derived_params_input_spad_stride <= io_req_bits_derived_params_input_spad_stride;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16]
      req_viEligible <= io_req_bits_viEligible;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16]
      req_viGeneration <= io_req_bits_viGeneration;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16]
      req_a_addr_start <= io_req_bits_a_addr_start;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16]
      req_b_addr_end <= io_req_bits_b_addr_end;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16]
      req_c_addr_start <= io_req_bits_c_addr_start;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16]
      req_wrot180 <= io_req_bits_wrot180;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16]
      req_downsample <= io_req_bits_downsample;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16]
      req_max_pixels_per_row <= io_req_bits_max_pixels_per_row;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16]
      req_input_dilated <= io_req_bits_input_dilated;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16]
      req_trans_weight_0132 <= io_req_bits_trans_weight_0132;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16]
      req_trans_input_3120 <= io_req_bits_trans_input_3120;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16]
      req_loop_id <= io_req_bits_loop_id;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16]
      och <= 16'h0;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:677:16]
      krow <= 16'h0;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:678:17]
      kcol <= 16'h0;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:679:17]
      kch <= 16'h0;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:680:16]
      b <= 16'h0;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:681:14]
      orow <= 16'h0;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:682:17]
      ocol <= 16'h0;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:683:17]
    end
    else begin	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35]
      if (~_GEN_32 | _GEN_33 | _command_p_io_in_bits_cmd_T | ~_next_och_T_10) begin	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:677:16, :683:17, :785:62, :895:{30,49}, :896:{17,29}, :898:32, :922:74, :923:{27,47,65,86}, :931:11, generators/gemmini/src/main/scala/gemmini/Util.scala:42:8, src/main/scala/chisel3/util/Mux.scala:126:16]
      end
      else	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:677:16, :895:49, :896:29, :898:32, :931:11, src/main/scala/chisel3/util/Mux.scala:126:16]
        och <= _next_och_T_16;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:677:16, src/main/scala/chisel3/util/Mux.scala:126:16]
      if (~_GEN_32 | _GEN_33 | _command_p_io_in_bits_cmd_T | ~_next_krow_T_8) begin	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:678:17, :683:17, :785:62, :895:{30,49}, :896:{17,29}, :898:32, :921:{27,47,65,86}, :930:12, generators/gemmini/src/main/scala/gemmini/Util.scala:42:8, src/main/scala/chisel3/util/Mux.scala:126:16]
      end
      else	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:678:17, :895:49, :896:29, :898:32, :930:12, src/main/scala/chisel3/util/Mux.scala:126:16]
        krow <= _next_krow_T_14;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:678:17, src/main/scala/chisel3/util/Mux.scala:126:16]
      if (~_GEN_32 | _GEN_33 | _command_p_io_in_bits_cmd_T | ~_next_kcol_T_6) begin	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:679:17, :683:17, :785:62, :895:{30,49}, :896:{17,29}, :898:32, :919:{26,44,65}, :929:12, generators/gemmini/src/main/scala/gemmini/Util.scala:42:8, src/main/scala/chisel3/util/Mux.scala:126:16]
      end
      else	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:679:17, :895:49, :896:29, :898:32, :929:12, src/main/scala/chisel3/util/Mux.scala:126:16]
        kcol <= _next_kcol_T_12;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:679:17, src/main/scala/chisel3/util/Mux.scala:126:16]
      if (~_GEN_32 | _GEN_33 | _command_p_io_in_bits_cmd_T | ~_next_kch_T_4) begin	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:680:16, :683:17, :785:62, :895:{30,49}, :896:{17,29}, :898:32, :917:{24,45}, :928:11, generators/gemmini/src/main/scala/gemmini/Util.scala:42:8, src/main/scala/chisel3/util/Mux.scala:126:16]
      end
      else	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:680:16, :895:49, :896:29, :898:32, :928:11, src/main/scala/chisel3/util/Mux.scala:126:16]
        kch <= _next_kch_T_10;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:680:16, src/main/scala/chisel3/util/Mux.scala:126:16]
      if (~_GEN_32 | _GEN_33 | _command_p_io_in_bits_cmd_T | ~_next_b_T_2) begin	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:681:14, :683:17, :785:62, :895:{30,49}, :896:{17,29}, :898:32, :915:65, :927:9, generators/gemmini/src/main/scala/gemmini/Util.scala:42:8, src/main/scala/chisel3/util/Mux.scala:126:16]
      end
      else	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:681:14, :895:49, :896:29, :898:32, :927:9, src/main/scala/chisel3/util/Mux.scala:126:16]
        b <= _next_b_T_8;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:681:14, src/main/scala/chisel3/util/Mux.scala:126:16]
      if (~_GEN_32 | _GEN_48) begin	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:683:17, :895:{30,49}, :896:29, :898:32, :925:12]
      end
      else begin	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:683:17, :895:49, :896:29]
        orow <= next_orow[15:0];	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:682:17, :914:26, :926:12]
        ocol <= next_ocol[15:0];	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:683:17, :913:26, :925:12]
      end
    end
    new_weights <= _GEN_30 | _GEN_32 & ~_GEN_48 & _state_T_7 & _state_T_9 & ~(|next_ocol) | ~((&state) & _GEN_31) & new_weights;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:638:22, :683:17, :722:24, :785:90, :887:{24,49}, :888:17, :895:{30,49}, :896:29, :898:32, :913:26, :914:114, :915:57, :917:16, :925:12, :933:{28,49,71}, :944:22, :956:17, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:615:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:615:7]
      `FIRRTL_BEFORE_INITIAL	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:615:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:29];	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:615:7]
    initial begin	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:615:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:615:7]
        `INIT_RANDOM_PROLOG_	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:615:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:615:7]
        for (logic [4:0] i = 5'h0; i < 5'h1E; i += 5'h1) begin
          _RANDOM[i] = `RANDOM;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:615:7]
        end	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:615:7]
        state = _RANDOM[5'h0][1:0];	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:615:7, :638:22]
        req_outer_bounds_stride = _RANDOM[5'h6][17:2];	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:615:7, :640:16]
        req_outer_bounds_kernel_dilation = {_RANDOM[5'h7][31:18], _RANDOM[5'h8][1:0]};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:615:7, :640:16]
        req_inner_bounds_batches = {_RANDOM[5'h9][31:18], _RANDOM[5'hA][1:0]};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:615:7, :640:16]
        req_inner_bounds_krows = {_RANDOM[5'hB][31:18], _RANDOM[5'hC][1:0]};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:615:7, :640:16]
        req_inner_bounds_kcols = _RANDOM[5'hC][17:2];	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:615:7, :640:16]
        req_inner_bounds_kchs = {_RANDOM[5'hC][31:18], _RANDOM[5'hD][1:0]};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:615:7, :640:16]
        req_inner_bounds_lpad = _RANDOM[5'hD][17:2];	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:615:7, :640:16]
        req_inner_bounds_upad = _RANDOM[5'hE][17:2];	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:615:7, :640:16]
        req_inner_bounds_orows = _RANDOM[5'h11][17:2];	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:615:7, :640:16]
        req_inner_bounds_ocols = {_RANDOM[5'h11][31:18], _RANDOM[5'h12][1:0]};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:615:7, :640:16]
        req_derived_params_ochs = _RANDOM[5'h12][17:2];	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:615:7, :640:16]
        req_derived_params_irows = {_RANDOM[5'h12][31:18], _RANDOM[5'h13][1:0]};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:615:7, :640:16]
        req_derived_params_icols = _RANDOM[5'h13][17:2];	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:615:7, :640:16]
        req_derived_params_out_channels_per_bank = _RANDOM[5'h15][17:2];	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:615:7, :640:16]
        req_derived_params_in_channels_per_bank = {_RANDOM[5'h15][31:18], _RANDOM[5'h16][1:0]};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:615:7, :640:16]
        req_derived_params_input_spad_stride = {_RANDOM[5'h16][31:18], _RANDOM[5'h17][1:0]};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:615:7, :640:16]
        req_viEligible = _RANDOM[5'h17][18];	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:615:7, :640:16]
        req_viGeneration = {_RANDOM[5'h17][31:20], _RANDOM[5'h18][3:0]};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:615:7, :640:16]
        req_a_addr_start = _RANDOM[5'h18][18:4];	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:615:7, :640:16]
        req_b_addr_end = {_RANDOM[5'h18][31:19], _RANDOM[5'h19][2:0]};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:615:7, :640:16]
        req_c_addr_start = _RANDOM[5'h19][14:3];	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:615:7, :640:16]
        req_wrot180 = _RANDOM[5'h19][15];	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:615:7, :640:16]
        req_downsample = _RANDOM[5'h19][16];	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:615:7, :640:16]
        req_max_pixels_per_row = {_RANDOM[5'h19][31:17], _RANDOM[5'h1A][0]};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:615:7, :640:16]
        req_input_dilated = _RANDOM[5'h1A][1];	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:615:7, :640:16]
        req_trans_weight_0132 = _RANDOM[5'h1A][2];	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:615:7, :640:16]
        req_trans_input_3120 = _RANDOM[5'h1A][3];	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:615:7, :640:16]
        req_loop_id = _RANDOM[5'h1A][4];	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:615:7, :640:16]
        crossRows = _RANDOM[5'h1A][5];	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:615:7, :640:16, :661:26]
        och = _RANDOM[5'h1A][21:6];	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:615:7, :640:16, :677:16]
        krow = {_RANDOM[5'h1A][31:22], _RANDOM[5'h1B][5:0]};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:615:7, :640:16, :678:17]
        kcol = _RANDOM[5'h1B][21:6];	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:615:7, :678:17, :679:17]
        kch = {_RANDOM[5'h1B][31:22], _RANDOM[5'h1C][5:0]};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:615:7, :678:17, :680:16]
        b = _RANDOM[5'h1C][21:6];	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:615:7, :680:16, :681:14]
        orow = {_RANDOM[5'h1C][31:22], _RANDOM[5'h1D][5:0]};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:615:7, :680:16, :682:17]
        ocol = _RANDOM[5'h1D][21:6];	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:615:7, :682:17, :683:17]
        new_weights = _RANDOM[5'h1D][22];	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:615:7, :682:17, :722:24]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:615:7]
      `FIRRTL_AFTER_INITIAL	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:615:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  Pipeline_4 command_p (	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:741:25]
    .clock                                         (clock),
    .reset                                         (reset),
    .io_in_ready                                   (_command_p_io_in_ready),
    .io_in_valid                                   (command_p_io_in_valid),	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:777:{35,55}, :784:{43,62}]
    .io_in_bits_cmd_inst_funct                     (_command_p_io_in_bits_cmd_T ? 7'h6 : (&state) ? {6'h2, ~new_weights} : 7'h0),	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:638:22, :722:24, :767:22, :773:{23,29}, :785:{62,90}, src/main/scala/chisel3/util/Mux.scala:126:16]
    .io_in_bits_cmd_rs1                            (_GEN_28 ? 64'h0 : {32'h0, vi_desc_input_batchStride[15:0], 16'h80}),	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:754:{27,37}, :762:36, :768:15, :823:7, src/main/scala/chisel3/util/Mux.scala:126:16]
    .io_in_bits_cmd_rs2                            (_GEN_28 ? 64'h0 : {_config_cmd_rs2_c_stride_T[15:0], 48'h0}),	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:704:36, :760:27, :763:36, :768:15, src/main/scala/chisel3/util/Mux.scala:126:16]
    .io_in_bits_virtualI_valid                     ((crossRows | req_viEligible & _GEN_12 + {1'h0, _vi_valid_T_4} < 33'h8001 & {1'h0, c_addr} + {36'h0, I} < 69'h1001 & irow < {18'h0, req_derived_params_irows} & {1'h0, icol} + {2'h0, I} <= {19'h0, req_derived_params_icols} & (|K) & K < 32'h11 & (|J) & J < 16'h11) & (&state)),	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:638:22, :640:16, :646:59, :661:26, :705:14, :706:14, :707:18, :711:18, :719:105, :785:90, :810:{38,59}, :820:{12,30,48}, :821:{23,68,82}, :822:{13,19,37,45,53,62,68,77}, :823:{7,13,18,34,39,45,50}, :831:19, :832:14]
    .io_in_bits_virtualI_desc_input_base           ({17'h0, req_a_addr_start}),	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16, :809:17]
    .io_in_bits_virtualI_desc_input_limit          ({17'h0, req_a_addr_start} + _vi_valid_T_4),	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16, :711:18, :810:{38,59}]
    .io_in_bits_virtualI_desc_input_channelStride  (vi_desc_input_channelStride),	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:711:40]
    .io_in_bits_virtualI_desc_input_batchStride    (vi_desc_input_batchStride),	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:754:37]
    .io_in_bits_virtualI_desc_input_rowStride      (vi_desc_input_rowStride),	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:754:37]
    .io_in_bits_virtualI_desc_input_residentH      (req_derived_params_irows),	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16]
    .io_in_bits_virtualI_desc_input_residentW      (req_derived_params_icols),	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16]
    .io_in_bits_virtualI_desc_input_batches        (req_inner_bounds_batches),	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16]
    .io_in_bits_virtualI_desc_input_channelBlocks  (req_derived_params_in_channels_per_bank),	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16]
    .io_in_bits_virtualI_desc_output_base          (crossRows ? {20'h0, req_c_addr_start} : c_addr[31:0]),	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16, :661:26, :719:105, :817:18, :831:19, :840:20]
    .io_in_bits_virtualI_desc_output_groups        (crossRows ? req_derived_params_out_channels_per_bank : 16'h1),	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16, :661:26, :801:14, :819:20, :831:19, :841:22]
    .io_in_bits_virtualI_desc_owner                ({15'h0, req_loop_id}),	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16, :799:12]
    .io_in_bits_virtualI_desc_generation           (req_viGeneration),	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16]
    .io_in_bits_virtualI_desc_segment              (crossRows),	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:661:26]
    .io_in_bits_virtualI_desc_startB               (crossRows ? b : 16'h0),	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:661:26, :681:14, :793:20, :831:19, :834:15]
    .io_in_bits_virtualI_desc_startR               (crossRows ? orow : 16'h0),	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:661:26, :682:17, :793:20, :831:19, :834:31]
    .io_in_bits_virtualI_desc_startC               (crossRows ? ocol : 16'h0),	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:661:26, :683:17, :793:20, :831:19, :834:50]
    .io_in_bits_virtualI_desc_segmentRows          (crossRows ? I[6:0] : 7'h0),	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:661:26, :705:14, :793:20, :831:19, :834:74]
    .io_in_bits_virtualI_desc_batches              (crossRows ? req_inner_bounds_batches : 16'h1),	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16, :661:26, :801:14, :831:19, :835:16]
    .io_in_bits_virtualI_desc_tileRows             (crossRows ? req_inner_bounds_orows : 16'h1),	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16, :661:26, :801:{14,34}, :831:19, :835:40]
    .io_in_bits_virtualI_desc_tileCols             (crossRows ? req_inner_bounds_ocols : I[15:0]),	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16, :661:26, :705:14, :801:54, :831:19, :835:62]
    .io_in_bits_virtualI_desc_batchStart           (crossRows ? 16'h0 : b),	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:661:26, :681:14, :802:17, :831:19, :836:19]
    .io_in_bits_virtualI_desc_outputY              (crossRows ? 16'h0 : irow[15:0]),	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:646:59, :661:26, :804:14, :831:19, :837:16]
    .io_in_bits_virtualI_desc_outputX              (crossRows ? 16'h0 : icol[15:0]),	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:646:59, :661:26, :804:34, :831:19, :837:35]
    .io_in_bits_virtualI_desc_inputH               (req_derived_params_irows),	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16]
    .io_in_bits_virtualI_desc_inputW               (req_derived_params_icols),	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16]
    .io_in_bits_virtualI_desc_kernelY              (crossRows ? krow : 16'h0),	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:661:26, :678:17, :793:20, :831:19, :838:16]
    .io_in_bits_virtualI_desc_kernelX              (crossRows ? kcol : 16'h0),	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:661:26, :679:17, :793:20, :831:19, :838:36]
    .io_in_bits_virtualI_desc_dilationY            (vi_desc_dilationX),	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:806:16, :831:19, :839:18]
    .io_in_bits_virtualI_desc_dilationX            (vi_desc_dilationX),	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:806:16, :831:19, :839:18]
    .io_in_bits_virtualI_desc_channelBlock         ({4'h0, kch[15:4]}),	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:680:16, :773:23, :807:{19,26}]
    .io_in_bits_virtualI_desc_outputGroup          (crossRows ? {4'h0, och[15:4]} : 16'h0),	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:661:26, :677:16, :773:23, :793:20, :831:19, :842:{20,27}]
    .io_in_bits_virtualI_desc_kValid               (K[6:0]),	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:707:18, :808:13]
    .io_in_bits_virtualI_desc_jValid               (J[6:0]),	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:706:14, :808:29]
    .io_in_bits_a_addr                             (req_trans_input_3120 ? {1'h0, {2'h0, {16'h0, _GEN_12 + {1'h0, {16'h0, b / 16'h10} * vi_desc_input_channelStride}} + {1'h0, {16'h0, {16'h0, kch} * _GEN_14} * _GEN_15}} + {1'h0, _GEN_17 * _GEN_18}} + _GEN_19 : {1'h0, {2'h0, {16'h0, _GEN_12 + {1'h0, _GEN_20 * vi_desc_input_channelStride}} + {1'h0, {16'h0, _GEN_21 * _GEN_14} * _GEN_15}} + {1'h0, _GEN_17 * _GEN_18}} + _GEN_19),	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:638:22, :640:16, :680:16, :681:14, :695:21, :710:19, :711:{18,24,40,60,67,95,123,151,179}, :712:{18,58,78,83,111,139,167,195}]
    .io_in_bits_b_addr                             (req_trans_weight_0132 ? {1'h0, {1'h0, {1'h0, _GEN_25 + {1'h0, {16'h0, {16'h0, _GEN_20 * _GEN_23} * _GEN_24} * _GEN_2}} + {18'h0, _GEN_26 * {32'h0, req_derived_params_ochs}}} + {35'h0, _GEN_27 * {16'h0, req_derived_params_ochs}}} + {52'h0, och} : {1'h0, {1'h0, {1'h0, _GEN_25 + {1'h0, {16'h0, {16'h0, _GEN_22 * _GEN_23} * _GEN_24} * _GEN_3}} + {18'h0, _GEN_26 * {32'h0, req_inner_bounds_kchs}}} + {35'h0, _GEN_27 * {16'h0, req_inner_bounds_kchs}}} + {52'h0, kch}),	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:640:16, :649:80, :650:43, :669:61, :677:16, :680:16, :712:58, :719:{42,89}, :726:19, :727:{18,58,66,74,81,101,108,120,127}, :728:{18,58,66,74,81,101,108,120,127}, :823:7]
    .io_in_bits_c_addr                             (c_addr),	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:719:105]
    .io_in_bits_I                                  (I),	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:705:14]
    .io_in_bits_J                                  (J),	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:706:14]
    .io_in_bits_K                                  (K),	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:707:18]
    .io_in_bits_new_weights                        (new_weights),	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:722:24]
    .io_out_ready                                  (io_cmd_ready & ~io_rob_overloaded),	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:847:{42,45}]
    .io_out_valid                                  (_command_p_io_out_valid),
    .io_out_bits_cmd_inst_funct                    (_command_p_io_out_bits_cmd_inst_funct),
    .io_out_bits_cmd_rs1                           (_command_p_io_out_bits_cmd_rs1),
    .io_out_bits_cmd_rs2                           (_command_p_io_out_bits_cmd_rs2),
    .io_out_bits_virtualI_valid                    (io_virtualI_valid),
    .io_out_bits_virtualI_desc_input_base          (io_virtualI_desc_input_base),
    .io_out_bits_virtualI_desc_input_limit         (io_virtualI_desc_input_limit),
    .io_out_bits_virtualI_desc_input_channelStride (io_virtualI_desc_input_channelStride),
    .io_out_bits_virtualI_desc_input_batchStride   (io_virtualI_desc_input_batchStride),
    .io_out_bits_virtualI_desc_input_rowStride     (io_virtualI_desc_input_rowStride),
    .io_out_bits_virtualI_desc_input_residentH     (io_virtualI_desc_input_residentH),
    .io_out_bits_virtualI_desc_input_residentW     (io_virtualI_desc_input_residentW),
    .io_out_bits_virtualI_desc_input_batches       (io_virtualI_desc_input_batches),
    .io_out_bits_virtualI_desc_input_channelBlocks (io_virtualI_desc_input_channelBlocks),
    .io_out_bits_virtualI_desc_output_base         (io_virtualI_desc_output_base),
    .io_out_bits_virtualI_desc_output_groups       (io_virtualI_desc_output_groups),
    .io_out_bits_virtualI_desc_owner               (io_virtualI_desc_owner),
    .io_out_bits_virtualI_desc_generation          (io_virtualI_desc_generation),
    .io_out_bits_virtualI_desc_segment             (io_virtualI_desc_segment),
    .io_out_bits_virtualI_desc_startB              (io_virtualI_desc_startB),
    .io_out_bits_virtualI_desc_startR              (io_virtualI_desc_startR),
    .io_out_bits_virtualI_desc_startC              (io_virtualI_desc_startC),
    .io_out_bits_virtualI_desc_segmentRows         (io_virtualI_desc_segmentRows),
    .io_out_bits_virtualI_desc_batches             (io_virtualI_desc_batches),
    .io_out_bits_virtualI_desc_tileRows            (io_virtualI_desc_tileRows),
    .io_out_bits_virtualI_desc_tileCols            (io_virtualI_desc_tileCols),
    .io_out_bits_virtualI_desc_batchStart          (io_virtualI_desc_batchStart),
    .io_out_bits_virtualI_desc_outputY             (io_virtualI_desc_outputY),
    .io_out_bits_virtualI_desc_outputX             (io_virtualI_desc_outputX),
    .io_out_bits_virtualI_desc_inputH              (io_virtualI_desc_inputH),
    .io_out_bits_virtualI_desc_inputW              (io_virtualI_desc_inputW),
    .io_out_bits_virtualI_desc_kernelY             (io_virtualI_desc_kernelY),
    .io_out_bits_virtualI_desc_kernelX             (io_virtualI_desc_kernelX),
    .io_out_bits_virtualI_desc_dilationY           (io_virtualI_desc_dilationY),
    .io_out_bits_virtualI_desc_dilationX           (io_virtualI_desc_dilationX),
    .io_out_bits_virtualI_desc_channelBlock        (io_virtualI_desc_channelBlock),
    .io_out_bits_virtualI_desc_outputGroup         (io_virtualI_desc_outputGroup),
    .io_out_bits_virtualI_desc_kValid              (io_virtualI_desc_kValid),
    .io_out_bits_virtualI_desc_jValid              (io_virtualI_desc_jValid),
    .io_out_bits_a_addr                            (_command_p_io_out_bits_a_addr),
    .io_out_bits_b_addr                            (_command_p_io_out_bits_b_addr),
    .io_out_bits_c_addr                            (_command_p_io_out_bits_c_addr),
    .io_out_bits_I                                 (_command_p_io_out_bits_I),
    .io_out_bits_J                                 (_command_p_io_out_bits_J),
    .io_out_bits_K                                 (_command_p_io_out_bits_K),
    .io_out_bits_new_weights                       (_command_p_io_out_bits_new_weights),
    .io_busy                                       (_command_p_io_busy)
  );	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:741:25]
  assign io_req_ready = io_req_ready_0;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:615:7, :780:34]
  assign io_cmd_valid = _command_p_io_out_valid & ~io_rob_overloaded;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:615:7, :741:25, :847:45, :848:42]
  assign io_cmd_bits_inst_funct = _command_p_io_out_bits_cmd_inst_funct;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:615:7, :741:25]
  assign io_cmd_bits_rs1 = _GEN_29 ? {11'h0, _command_p_io_out_bits_K[4:0], 9'h0, _command_p_io_out_bits_J[6:0], ~_command_p_io_out_bits_new_weights, ~_command_p_io_out_bits_new_weights, ~_command_p_io_out_bits_new_weights, _command_p_io_out_bits_new_weights ? _command_p_io_out_bits_b_addr[28:26] : 3'h0, 10'h0, ~_command_p_io_out_bits_new_weights | _command_p_io_out_bits_b_addr[15], _command_p_io_out_bits_new_weights ? _command_p_io_out_bits_b_addr[14:0] : 15'h7FFF} : (|_command_p_io_out_bits_cmd_inst_funct) ? {11'h0, _command_p_io_out_bits_I[4:0], 9'h0, _command_p_io_out_bits_K[6:0], 3'h0, _command_p_io_out_bits_a_addr[28:26], 10'h0, _command_p_io_out_bits_a_addr[15:0]} : _command_p_io_out_bits_cmd_rs1;	// @[generators/gemmini/src/main/scala/gemmini/LocalAddr.scala:99:13, :108:37, generators/gemmini/src/main/scala/gemmini/LoopConv.scala:615:7, :741:25, :849:15, :850:{46,63}, :855:26, :856:26, :857:34, :862:26, :866:{21,36}, :868:{51,67}, :873:27, :882:{21,37}]
  assign io_cmd_bits_rs2 = _GEN_29 ? {11'h0, _command_p_io_out_bits_I[4:0], 9'h0, _command_p_io_out_bits_J[6:0], 3'h6, _command_p_io_out_bits_c_addr[28:26], 10'h0, _command_p_io_out_bits_c_addr[15:0]} : (|_command_p_io_out_bits_cmd_inst_funct) ? {11'h0, _command_p_io_out_bits_I[4:0], 9'h0, _command_p_io_out_bits_J[6:0], 32'hE000FFFF} : _command_p_io_out_bits_cmd_rs2;	// @[generators/gemmini/src/main/scala/gemmini/LocalAddr.scala:108:37, generators/gemmini/src/main/scala/gemmini/LoopConv.scala:615:7, :741:25, :849:15, :850:{46,63}, :856:26, :862:26, :867:{21,36}, :868:{51,67}, :883:{21,37}]
  assign io_idle = _io_idle_T & ~_command_p_io_busy;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:615:7, :741:25, :780:{25,37}, :781:29]
  assign io_loop_id = req_loop_id;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:615:7, :640:16]
endmodule

