// Generated by CIRCT firtool-1.75.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module LoopConvSt(	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:869:7]
  input         clock,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:869:7]
  input         reset,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:869:7]
  output        io_req_ready,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:872:14]
  input         io_req_valid,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:872:14]
  input  [15:0] io_req_bits_outer_bounds_batch_size,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:872:14]
  input  [15:0] io_req_bits_outer_bounds_out_channels,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:872:14]
  input  [15:0] io_req_bits_outer_bounds_out_col_dim,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:872:14]
  input  [15:0] io_req_bits_outer_bounds_out_row_dim,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:872:14]
  input  [15:0] io_req_bits_outer_bounds_out_stride,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:872:14]
  input  [15:0] io_req_bits_outer_bounds_pool_out_row_dim,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:872:14]
  input  [15:0] io_req_bits_outer_bounds_pool_out_col_dim,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:872:14]
  input  [15:0] io_req_bits_outer_bounds_pool_size,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:872:14]
  input  [15:0] io_req_bits_outer_bounds_pool_stride,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:872:14]
  input  [15:0] io_req_bits_inner_bounds_batches,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:872:14]
  input  [15:0] io_req_bits_inner_bounds_porows,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:872:14]
  input  [15:0] io_req_bits_inner_bounds_pocols,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:872:14]
  input  [15:0] io_req_bits_inner_bounds_plpad,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:872:14]
  input  [15:0] io_req_bits_inner_bounds_pupad,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:872:14]
  input  [15:0] io_req_bits_inner_bounds_orows,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:872:14]
  input  [15:0] io_req_bits_inner_bounds_ocols,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:872:14]
  input  [15:0] io_req_bits_derived_params_ochs,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:872:14]
  input  [11:0] io_req_bits_addr_start,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:872:14]
  input  [39:0] io_req_bits_dram_addr,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:872:14]
  input         io_req_bits_no_pool,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:872:14]
  input  [2:0]  io_req_bits_activation,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:872:14]
  input         io_req_bits_trans_output_1203,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:872:14]
  input         io_req_bits_loop_id,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:872:14]
  input         io_cmd_ready,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:872:14]
  output        io_cmd_valid,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:872:14]
  output [6:0]  io_cmd_bits_inst_funct,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:872:14]
  output [63:0] io_cmd_bits_rs1,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:872:14]
  output [63:0] io_cmd_bits_rs2,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:872:14]
  input         io_ex_completed,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:872:14]
  output        io_idle,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:872:14]
  input         io_rob_overloaded,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:872:14]
  output        io_loop_id	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:872:14]
);

  wire        _command_p_io_in_ready;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:934:25]
  wire        _command_p_io_out_valid;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:934:25]
  wire [6:0]  _command_p_io_out_bits_cmd_inst_funct;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:934:25]
  wire [63:0] _command_p_io_out_bits_cmd_rs1;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:934:25]
  wire [63:0] _command_p_io_out_bits_cmd_rs2;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:934:25]
  wire [67:0] _command_p_io_out_bits_dram_addr;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:934:25]
  wire [67:0] _command_p_io_out_bits_spad_addr;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:934:25]
  wire [64:0] _command_p_io_out_bits_pool_dram_addr;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:934:25]
  wire [65:0] _command_p_io_out_bits_pool_spad_addr;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:934:25]
  wire [15:0] _command_p_io_out_bits_channels;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:934:25]
  wire        _command_p_io_out_bits_is_pool;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:934:25]
  wire [15:0] _command_p_io_out_bits_I;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:934:25]
  wire [15:0] _command_p_io_out_bits_J;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:934:25]
  wire        _command_p_io_busy;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:934:25]
  reg  [2:0]  state;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:888:22]
  reg  [15:0] req_outer_bounds_batch_size;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:891:16]
  reg  [15:0] req_outer_bounds_out_channels;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:891:16]
  reg  [15:0] req_outer_bounds_out_col_dim;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:891:16]
  reg  [15:0] req_outer_bounds_out_row_dim;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:891:16]
  reg  [15:0] req_outer_bounds_out_stride;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:891:16]
  reg  [15:0] req_outer_bounds_pool_out_row_dim;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:891:16]
  reg  [15:0] req_outer_bounds_pool_out_col_dim;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:891:16]
  reg  [15:0] req_outer_bounds_pool_size;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:891:16]
  reg  [15:0] req_outer_bounds_pool_stride;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:891:16]
  reg  [15:0] req_inner_bounds_batches;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:891:16]
  reg  [15:0] req_inner_bounds_porows;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:891:16]
  reg  [15:0] req_inner_bounds_pocols;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:891:16]
  reg  [15:0] req_inner_bounds_plpad;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:891:16]
  reg  [15:0] req_inner_bounds_pupad;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:891:16]
  reg  [15:0] req_inner_bounds_orows;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:891:16]
  reg  [15:0] req_inner_bounds_ocols;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:891:16]
  reg  [15:0] req_derived_params_ochs;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:891:16]
  reg  [11:0] req_addr_start;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:891:16]
  reg  [39:0] req_dram_addr;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:891:16]
  reg         req_no_pool;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:891:16]
  reg  [2:0]  req_activation;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:891:16]
  reg         req_trans_output_1203;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:891:16]
  reg         req_loop_id;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:891:16]
  reg  [15:0] b;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:902:14]
  reg  [15:0] orow;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:903:17]
  reg  [15:0] ocol;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:904:17]
  reg  [15:0] och;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:905:16]
  wire [31:0] _GEN = {16'h0, orow};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:903:17, :909:11]
  wire [31:0] _GEN_0 = {16'h0, req_outer_bounds_out_col_dim};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:891:16, :909:11]
  wire [31:0] _dram_offset_T_10 = _GEN * _GEN_0;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:909:11]
  wire [31:0] _GEN_1 = {16'h0, req_outer_bounds_batch_size};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:891:16, :909:23]
  wire [31:0] _GEN_2 = {16'h0, ocol};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:904:17, :909:42]
  wire [31:0] _GEN_3 = {16'h0, b};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:902:14, :909:54]
  wire [31:0] _GEN_4 = {16'h0, och};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:905:16, :909:75]
  wire [31:0] _GEN_5 = {16'h0, och / 16'h10};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:905:16, :912:{42,74}, :918:28]
  wire [31:0] _GEN_6 = {16'h0, req_inner_bounds_batches};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:891:16, :912:74]
  wire [47:0] _GEN_7 = {32'h0, req_inner_bounds_orows};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:891:16, :909:23, :912:84]
  wire [63:0] _GEN_8 = {48'h0, req_inner_bounds_ocols};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:891:16, :912:92]
  wire [64:0] _GEN_9 = {53'h0, req_addr_start};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:891:16, :912:34]
  wire [47:0] _GEN_10 = {16'h0, _GEN_3 * {16'h0, req_inner_bounds_orows}};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:891:16, :909:54, :912:{105,113}]
  wire [47:0] _GEN_11 = {32'h0, req_inner_bounds_ocols};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:891:16, :909:23, :912:113]
  wire [15:0] _I_T_3 = req_inner_bounds_ocols - ocol;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:891:16, :904:17, :918:21]
  wire [15:0] _J_T_3 = req_derived_params_ochs - och;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:891:16, :905:16, :919:20]
  wire [15:0] J = _J_T_3 > 16'h10 ? 16'h10 : _J_T_3;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:918:28, :919:{14,20,26}]
  wire        _io_idle_T = state == 3'h0;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:888:22, :989:25]
  wire        io_req_ready_0 = _io_idle_T & ~_command_p_io_busy;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:934:25, :989:{25,34,37}]
  wire        command_p_io_in_valid = (|state) & (|req_dram_addr) & io_ex_completed;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:888:22, :891:16, :899:28, :993:{34,43,52}]
  wire        _GEN_12 = state == 3'h3 | state != 3'h2;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:888:22, :994:65]
  wire        _command_p_io_in_bits_cmd_T_8 = state == 3'h4;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:888:22, :994:65]
  wire        _GEN_13 = _command_p_io_out_bits_cmd_inst_funct == 7'h3;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:934:25, :938:24, :1011:46]
  wire [16:0] _GEN_14 = {1'h0, och};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:905:16, :919:20]
  wire        _GEN_15 = _command_p_io_in_ready & command_p_io_in_valid;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:934:25, :993:{43,52}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire [16:0] _next_och_T_3 = _GEN_14 + 17'h10;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:919:20, generators/gemmini/src/main/scala/gemmini/Util.scala:41:15]
  wire [15:0] next_och = _next_och_T_3 > {1'h0, req_derived_params_ochs - 16'h1} ? 16'h0 : _next_och_T_3[15:0];	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:891:16, generators/gemmini/src/main/scala/gemmini/Util.scala:39:28, :41:15, :43:17, src/main/scala/chisel3/util/Mux.scala:126:16]
  wire [16:0] _next_ocol_T_4 = {1'h0, ocol} + 17'h10;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:904:17, :918:21, generators/gemmini/src/main/scala/gemmini/Util.scala:41:15]
  wire [15:0] _next_ocol_T_6 = _next_ocol_T_4 > {1'h0, req_inner_bounds_ocols - 16'h1} ? 16'h0 : _next_ocol_T_4[15:0];	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:891:16, generators/gemmini/src/main/scala/gemmini/Util.scala:39:28, :41:15, :43:17, src/main/scala/chisel3/util/Mux.scala:126:16]
  wire        _state_T_3 = ((|next_och) ? ocol : _next_ocol_T_6) == 16'h0;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:904:17, :1051:68, :1052:60, src/main/scala/chisel3/util/Mux.scala:126:16]
  wire        _next_orow_T_2 = _state_T_3 & ~(|next_och);	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:1051:68, :1052:{60,68}, src/main/scala/chisel3/util/Mux.scala:126:16]
  wire [16:0] _next_orow_T_6 = {1'h0, orow} + 17'h1;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:903:17, generators/gemmini/src/main/scala/gemmini/Util.scala:41:15]
  wire [15:0] _next_orow_T_8 = _next_orow_T_6 > {1'h0, req_inner_bounds_orows - 16'h1} ? 16'h0 : _next_orow_T_6[15:0];	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:891:16, generators/gemmini/src/main/scala/gemmini/Util.scala:39:28, :41:15, :43:17, src/main/scala/chisel3/util/Mux.scala:126:16]
  wire        _state_T_1 = (_next_orow_T_2 ? _next_orow_T_8 : orow) == 16'h0;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:903:17, :1052:68, :1053:56, src/main/scala/chisel3/util/Mux.scala:126:16]
  wire        _next_b_T_4 = _state_T_1 & _state_T_3 & ~(|next_och);	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:1051:68, :1052:60, :1053:{56,64,85}, src/main/scala/chisel3/util/Mux.scala:126:16]
  wire [16:0] _GEN_16 = {1'h0, b};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:902:14, generators/gemmini/src/main/scala/gemmini/Util.scala:41:15]
  wire [16:0] _next_b_T_8 = _GEN_16 + 17'h1;	// @[generators/gemmini/src/main/scala/gemmini/Util.scala:41:15]
  wire [15:0] _next_b_T_10 = _next_b_T_8 > {1'h0, req_inner_bounds_batches - 16'h1} ? 16'h0 : _next_b_T_8[15:0];	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:891:16, generators/gemmini/src/main/scala/gemmini/Util.scala:39:28, :41:15, :43:17, src/main/scala/chisel3/util/Mux.scala:126:16]
  wire        _GEN_17 = state == 3'h2;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:888:22, :1062:22]
  wire        _GEN_18 = state == 3'h4;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:888:22, :1064:22]
  wire [16:0] _next_och_T_9 = _GEN_14 + 17'h10;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:919:20, generators/gemmini/src/main/scala/gemmini/Util.scala:41:15]
  wire [15:0] next_och_1 = _next_och_T_9 > {1'h0, req_derived_params_ochs - 16'h1} ? 16'h0 : _next_och_T_9[15:0];	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:891:16, generators/gemmini/src/main/scala/gemmini/Util.scala:39:28, :41:15, :43:17, src/main/scala/chisel3/util/Mux.scala:126:16]
  wire [16:0] _next_b_T_15 = _GEN_16 + 17'h1;	// @[generators/gemmini/src/main/scala/gemmini/Util.scala:41:15]
  wire [15:0] _next_b_T_17 = _next_b_T_15 > {1'h0, req_inner_bounds_batches - 16'h1} ? 16'h0 : _next_b_T_15[15:0];	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:891:16, generators/gemmini/src/main/scala/gemmini/Util.scala:39:28, :41:15, :43:17, src/main/scala/chisel3/util/Mux.scala:126:16]
  wire        _GEN_19 = io_req_ready_0 & io_req_valid;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:989:34, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire        _GEN_20 = _GEN_15 & req_no_pool;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:891:16, :904:17, :1048:36, :1049:24, :1056:12, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  always @(posedge clock) begin	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:869:7]
    if (reset)	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:869:7]
      state <= 3'h0;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:888:22]
    else if (_GEN_19)	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35]
      state <= {1'h0, io_req_bits_no_pool ? 2'h1 : 2'h2};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:888:22, :1081:{11,17}]
    else if (|req_dram_addr) begin	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:891:16, :899:28]
      if (_GEN_15)	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35]
        state <= req_no_pool ? {2'h0, ~((_next_b_T_4 ? _next_b_T_10 : b) == 16'h0 & _state_T_1 & _state_T_3 & ~(|next_och))} : _GEN_17 ? 3'h3 : _GEN_18 ? 3'h0 : ((|next_och_1) ? b : _next_b_T_17) == 16'h0 & ~(|next_och_1) ? 3'h4 : 3'h3;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:888:22, :891:16, :902:14, :994:65, :1049:24, :1051:68, :1052:60, :1053:{56,64,85}, :1060:{13,19,27,35,56,77}, :1062:{22,43}, :1063:13, :1064:{22,44}, :1065:13, :1068:55, :1073:{13,19,27,35}, src/main/scala/chisel3/util/Mux.scala:126:16]
    end
    else	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:899:28]
      state <= 3'h0;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:888:22]
    if (_GEN_19) begin	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35]
      req_outer_bounds_batch_size <= io_req_bits_outer_bounds_batch_size;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:891:16]
      req_outer_bounds_out_channels <= io_req_bits_outer_bounds_out_channels;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:891:16]
      req_outer_bounds_out_col_dim <= io_req_bits_outer_bounds_out_col_dim;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:891:16]
      req_outer_bounds_out_row_dim <= io_req_bits_outer_bounds_out_row_dim;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:891:16]
      req_outer_bounds_out_stride <= io_req_bits_outer_bounds_out_stride;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:891:16]
      req_outer_bounds_pool_out_row_dim <= io_req_bits_outer_bounds_pool_out_row_dim;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:891:16]
      req_outer_bounds_pool_out_col_dim <= io_req_bits_outer_bounds_pool_out_col_dim;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:891:16]
      req_outer_bounds_pool_size <= io_req_bits_outer_bounds_pool_size;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:891:16]
      req_outer_bounds_pool_stride <= io_req_bits_outer_bounds_pool_stride;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:891:16]
      req_inner_bounds_batches <= io_req_bits_inner_bounds_batches;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:891:16]
      req_inner_bounds_porows <= io_req_bits_inner_bounds_porows;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:891:16]
      req_inner_bounds_pocols <= io_req_bits_inner_bounds_pocols;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:891:16]
      req_inner_bounds_plpad <= io_req_bits_inner_bounds_plpad;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:891:16]
      req_inner_bounds_pupad <= io_req_bits_inner_bounds_pupad;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:891:16]
      req_inner_bounds_orows <= io_req_bits_inner_bounds_orows;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:891:16]
      req_inner_bounds_ocols <= io_req_bits_inner_bounds_ocols;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:891:16]
      req_derived_params_ochs <= io_req_bits_derived_params_ochs;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:891:16]
      req_addr_start <= io_req_bits_addr_start;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:891:16]
      req_dram_addr <= io_req_bits_dram_addr;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:891:16]
      req_no_pool <= io_req_bits_no_pool;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:891:16]
      req_activation <= io_req_bits_activation;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:891:16]
      req_trans_output_1203 <= io_req_bits_trans_output_1203;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:891:16]
      req_loop_id <= io_req_bits_loop_id;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:891:16]
      b <= 16'h0;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:902:14]
      orow <= 16'h0;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:903:17]
      ocol <= 16'h0;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:904:17]
      och <= 16'h0;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:905:16]
    end
    else begin	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35]
      if (_GEN_15) begin	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35]
        if (req_no_pool) begin	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:891:16]
          if (_next_b_T_4)	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:1053:{64,85}]
            b <= _next_b_T_10;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:902:14, src/main/scala/chisel3/util/Mux.scala:126:16]
          och <= next_och;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:905:16, src/main/scala/chisel3/util/Mux.scala:126:16]
        end
        else begin	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:891:16]
          if (~(|{_GEN_17, _GEN_18, next_och_1}))	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:902:14, :1062:{22,43}, :1064:{22,44}, :1068:55, :1071:9, src/main/scala/chisel3/util/Mux.scala:126:16]
            b <= _next_b_T_17;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:902:14, src/main/scala/chisel3/util/Mux.scala:126:16]
          if (~(_GEN_17 | _GEN_18))	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:905:16, :1062:{22,43}, :1064:{22,44}, :1070:11]
            och <= next_och_1;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:905:16, src/main/scala/chisel3/util/Mux.scala:126:16]
        end
      end
      if (_GEN_20 & _next_orow_T_2)	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:903:17, :904:17, :1048:36, :1049:24, :1052:68, :1056:12, :1057:12]
        orow <= _next_orow_T_8;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:903:17, src/main/scala/chisel3/util/Mux.scala:126:16]
      if (~(|req_dram_addr) | ~_GEN_20 | (|next_och)) begin	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:891:16, :899:28, :904:17, :1046:15, :1048:36, :1049:24, :1051:68, :1056:12, src/main/scala/chisel3/util/Mux.scala:126:16]
      end
      else	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:904:17, :1046:15, :1048:36, :1049:24, :1056:12]
        ocol <= _next_ocol_T_6;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:904:17, src/main/scala/chisel3/util/Mux.scala:126:16]
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:869:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:869:7]
      `FIRRTL_BEFORE_INITIAL	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:869:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:27];	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:869:7]
    initial begin	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:869:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:869:7]
        `INIT_RANDOM_PROLOG_	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:869:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:869:7]
        for (logic [4:0] i = 5'h0; i < 5'h1C; i += 5'h1) begin
          _RANDOM[i] = `RANDOM;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:869:7]
        end	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:869:7]
        state = _RANDOM[5'h0][2:0];	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:869:7, :888:22]
        req_outer_bounds_batch_size = _RANDOM[5'h0][18:3];	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:869:7, :888:22, :891:16]
        req_outer_bounds_out_channels = _RANDOM[5'h2][18:3];	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:869:7, :891:16]
        req_outer_bounds_out_col_dim = {_RANDOM[5'h2][31:19], _RANDOM[5'h3][2:0]};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:869:7, :891:16]
        req_outer_bounds_out_row_dim = _RANDOM[5'h3][18:3];	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:869:7, :891:16]
        req_outer_bounds_out_stride = {_RANDOM[5'h3][31:19], _RANDOM[5'h4][2:0]};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:869:7, :891:16]
        req_outer_bounds_pool_out_row_dim = _RANDOM[5'h5][18:3];	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:869:7, :891:16]
        req_outer_bounds_pool_out_col_dim = {_RANDOM[5'h5][31:19], _RANDOM[5'h6][2:0]};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:869:7, :891:16]
        req_outer_bounds_pool_size = _RANDOM[5'h8][18:3];	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:869:7, :891:16]
        req_outer_bounds_pool_stride = {_RANDOM[5'h8][31:19], _RANDOM[5'h9][2:0]};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:869:7, :891:16]
        req_inner_bounds_batches = {_RANDOM[5'h9][31:19], _RANDOM[5'hA][2:0]};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:869:7, :891:16]
        req_inner_bounds_porows = _RANDOM[5'hA][18:3];	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:869:7, :891:16]
        req_inner_bounds_pocols = {_RANDOM[5'hA][31:19], _RANDOM[5'hB][2:0]};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:869:7, :891:16]
        req_inner_bounds_plpad = _RANDOM[5'hF][18:3];	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:869:7, :891:16]
        req_inner_bounds_pupad = _RANDOM[5'h10][18:3];	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:869:7, :891:16]
        req_inner_bounds_orows = _RANDOM[5'h11][18:3];	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:869:7, :891:16]
        req_inner_bounds_ocols = {_RANDOM[5'h11][31:19], _RANDOM[5'h12][2:0]};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:869:7, :891:16]
        req_derived_params_ochs = _RANDOM[5'h12][18:3];	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:869:7, :891:16]
        req_addr_start = _RANDOM[5'h17][30:19];	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:869:7, :891:16]
        req_dram_addr = {_RANDOM[5'h17][31], _RANDOM[5'h18], _RANDOM[5'h19][6:0]};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:869:7, :891:16]
        req_no_pool = _RANDOM[5'h19][7];	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:869:7, :891:16]
        req_activation = _RANDOM[5'h19][10:8];	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:869:7, :891:16]
        req_trans_output_1203 = _RANDOM[5'h19][11];	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:869:7, :891:16]
        req_loop_id = _RANDOM[5'h19][12];	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:869:7, :891:16]
        b = _RANDOM[5'h19][28:13];	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:869:7, :891:16, :902:14]
        orow = {_RANDOM[5'h19][31:29], _RANDOM[5'h1A][12:0]};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:869:7, :891:16, :903:17]
        ocol = _RANDOM[5'h1A][28:13];	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:869:7, :903:17, :904:17]
        och = {_RANDOM[5'h1A][31:29], _RANDOM[5'h1B][12:0]};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:869:7, :903:17, :905:16]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:869:7]
      `FIRRTL_AFTER_INITIAL	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:869:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  Pipeline_5 command_p (	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:934:25]
    .clock                      (clock),
    .reset                      (reset),
    .io_in_ready                (_command_p_io_in_ready),
    .io_in_valid                (command_p_io_in_valid),	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:993:{43,52}]
    .io_in_bits_cmd_inst_funct  (_command_p_io_in_bits_cmd_T_8 | ~_GEN_12 ? 7'h0 : 7'h3),	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:938:24, :994:65]
    .io_in_bits_cmd_rs1         (_command_p_io_in_bits_cmd_T_8 ? {59'h0, req_activation, 2'h2} : _GEN_12 ? 64'h0 : {req_inner_bounds_ocols[7:0], req_inner_bounds_orows[7:0], req_inner_bounds_pocols[7:0], req_inner_bounds_porows[7:0], req_outer_bounds_pool_out_col_dim[7:0], 11'h0, req_inner_bounds_plpad[1:0], req_inner_bounds_pupad[1:0], req_outer_bounds_pool_size[1:0], req_outer_bounds_pool_stride[1:0], req_activation, 2'h2}),	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:891:16, :939:17, :947:33, :948:33, :949:34, :950:34, :951:40, :952:32, :953:32, :954:37, :955:39, :958:54, :974:56, :994:65]
    .io_in_bits_cmd_rs2         (_command_p_io_in_bits_cmd_T_8 ? {48'hFFFFFFFF0000, req_outer_bounds_out_stride} : _GEN_12 ? 64'h0 : {48'hFFFFFFFF0000, req_outer_bounds_out_stride}),	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:891:16, :939:17, :964:54, :980:56, :994:65]
    .io_in_bits_dram_addr       ({27'h0, {9'h0, req_trans_output_1203 ? (_dram_offset_T_10 * _GEN_1 + _GEN_2 * _GEN_1 + _GEN_3) * {16'h0, req_outer_bounds_out_channels} + _GEN_4 : (_GEN_3 * {16'h0, req_outer_bounds_out_row_dim} * _GEN_0 + _dram_offset_T_10 + _GEN_2) * {16'h0, req_outer_bounds_out_stride} + _GEN_4} + {1'h0, req_dram_addr}}),	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:891:16, :908:24, :909:{11,23,35,42,54,60,75}, :910:{8,20,33,53,62,75}, :911:33, :1610:17]
    .io_in_bits_spad_addr       ({1'h0, {1'h0, {1'h0, _GEN_9 + {1'h0, {16'h0, {16'h0, _GEN_5 * _GEN_6} * _GEN_7} * _GEN_8}} + {18'h0, _GEN_10 * _GEN_11}} + {35'h0, _GEN * {16'h0, req_inner_bounds_ocols}}} + {52'h0, ocol}),	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:891:16, :904:17, :909:11, :912:{34,74,84,92,100,113,121,129,137}]
    .io_in_bits_pool_dram_addr  ({25'h0, req_dram_addr} + {1'h0, {16'h0, {16'h0, _GEN_3 * {16'h0, req_outer_bounds_pool_out_col_dim}} * {32'h0, req_outer_bounds_pool_out_row_dim}} * {48'h0, req_outer_bounds_out_stride} + {48'h0, och}}),	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:891:16, :905:16, :909:{23,54}, :914:{38,44,63,83,96}]
    .io_in_bits_pool_spad_addr  ({1'h0, _GEN_9 + {1'h0, {16'h0, {16'h0, _GEN_5 * _GEN_6} * _GEN_7} * _GEN_8}} + {18'h0, _GEN_10 * _GEN_11}),	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:912:{34,74,84,92,100,113}, :915:{39,79,89,97,105,118}]
    .io_in_bits_channels        (J),	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:919:14]
    .io_in_bits_is_pool         (state == 3'h3),	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:888:22, :994:65, :999:41]
    .io_in_bits_I               (_I_T_3 > 16'h10 ? 16'h10 : _I_T_3),	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:918:{14,21,28}]
    .io_in_bits_J               (J),	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:919:14]
    .io_out_ready               (io_cmd_ready & ~io_rob_overloaded),	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:1008:{42,45}]
    .io_out_valid               (_command_p_io_out_valid),
    .io_out_bits_cmd_inst_funct (_command_p_io_out_bits_cmd_inst_funct),
    .io_out_bits_cmd_rs1        (_command_p_io_out_bits_cmd_rs1),
    .io_out_bits_cmd_rs2        (_command_p_io_out_bits_cmd_rs2),
    .io_out_bits_dram_addr      (_command_p_io_out_bits_dram_addr),
    .io_out_bits_spad_addr      (_command_p_io_out_bits_spad_addr),
    .io_out_bits_pool_dram_addr (_command_p_io_out_bits_pool_dram_addr),
    .io_out_bits_pool_spad_addr (_command_p_io_out_bits_pool_spad_addr),
    .io_out_bits_channels       (_command_p_io_out_bits_channels),
    .io_out_bits_is_pool        (_command_p_io_out_bits_is_pool),
    .io_out_bits_I              (_command_p_io_out_bits_I),
    .io_out_bits_J              (_command_p_io_out_bits_J),
    .io_busy                    (_command_p_io_busy)
  );	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:934:25]
  assign io_req_ready = io_req_ready_0;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:869:7, :989:34]
  assign io_cmd_valid = _command_p_io_out_valid & ~io_rob_overloaded;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:869:7, :934:25, :1008:45, :1009:42]
  assign io_cmd_bits_inst_funct = _command_p_io_out_bits_cmd_inst_funct;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:869:7, :934:25]
  assign io_cmd_bits_rs1 = _GEN_13 ? (_command_p_io_out_bits_is_pool ? _command_p_io_out_bits_pool_dram_addr[63:0] : _command_p_io_out_bits_dram_addr[63:0]) : _command_p_io_out_bits_cmd_rs1;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:869:7, :934:25, :1010:15, :1011:{46,61}, :1013:22, :1019:23, :1028:23]
  assign io_cmd_bits_rs2 = _GEN_13 ? (_command_p_io_out_bits_is_pool ? {25'h0, _command_p_io_out_bits_channels[6:0], 3'h4, _command_p_io_out_bits_pool_spad_addr[28:26], 10'h0, _command_p_io_out_bits_pool_spad_addr[15:0]} : {11'h0, _command_p_io_out_bits_I[4:0], 9'h0, _command_p_io_out_bits_J[6:0], 3'h4, _command_p_io_out_bits_spad_addr[28:26], 10'h0, _command_p_io_out_bits_spad_addr[15:0]}) : _command_p_io_out_bits_cmd_rs2;	// @[generators/gemmini/src/main/scala/gemmini/LocalAddr.scala:108:37, generators/gemmini/src/main/scala/gemmini/LoopConv.scala:869:7, :934:25, :1010:15, :1011:{46,61}, :1013:22, :1016:35, :1020:{23,45}, :1024:30, :1025:30, :1029:{23,40}]
  assign io_idle = _io_idle_T & ~_command_p_io_busy;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:869:7, :934:25, :989:{25,37}, :990:29]
  assign io_loop_id = req_loop_id;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:869:7, :891:16]
endmodule

