// Generated by CIRCT firtool-1.75.0
// VCS coverage exclude_file
module ram_2x208(	// @[src/main/scala/chisel3/util/Decoupled.scala:256:91]
  input          R0_addr,
  input          R0_en,
  input          R0_clk,
  output [207:0] R0_data
);

  reg [207:0] Memory[0:1];	// @[src/main/scala/chisel3/util/Decoupled.scala:256:91]
  `ifdef ENABLE_INITIAL_MEM_	// @[src/main/scala/chisel3/util/Decoupled.scala:256:91]
    reg [223:0] _RANDOM_MEM;	// @[src/main/scala/chisel3/util/Decoupled.scala:256:91]
    initial begin	// @[src/main/scala/chisel3/util/Decoupled.scala:256:91]
      `INIT_RANDOM_PROLOG_	// @[src/main/scala/chisel3/util/Decoupled.scala:256:91]
      `ifdef RANDOMIZE_MEM_INIT	// @[src/main/scala/chisel3/util/Decoupled.scala:256:91]
        for (logic [1:0] i = 2'h0; i < 2'h2; i += 2'h1) begin
          for (logic [7:0] j = 8'h0; j < 8'hE0; j += 8'h20) begin
            _RANDOM_MEM[j +: 32] = `RANDOM;	// @[src/main/scala/chisel3/util/Decoupled.scala:256:91]
          end
          Memory[i[0]] = _RANDOM_MEM[207:0];	// @[src/main/scala/chisel3/util/Decoupled.scala:256:91]
        end
      `endif // RANDOMIZE_MEM_INIT
    end // initial
  `endif // ENABLE_INITIAL_MEM_
  assign R0_data = R0_en ? Memory[R0_addr] : 208'bx;	// @[src/main/scala/chisel3/util/Decoupled.scala:256:91]
endmodule

