// Generated by CIRCT firtool-1.75.0

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_
module RoccCommandRouter(	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:726:7]
  input         clock,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:726:7]
  input         reset,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:726:7]
  output        io_in_ready,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  input         io_in_valid,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  input  [6:0]  io_in_bits_inst_funct,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  input  [4:0]  io_in_bits_inst_rs2,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  input  [4:0]  io_in_bits_inst_rs1,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  input         io_in_bits_inst_xd,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  input         io_in_bits_inst_xs1,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  input         io_in_bits_inst_xs2,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  input  [4:0]  io_in_bits_inst_rd,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  input  [6:0]  io_in_bits_inst_opcode,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  input  [63:0] io_in_bits_rs1,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  input  [63:0] io_in_bits_rs2,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  input         io_in_bits_status_debug,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  input         io_in_bits_status_cease,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  input         io_in_bits_status_wfi,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  input  [31:0] io_in_bits_status_isa,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  input  [1:0]  io_in_bits_status_dprv,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  input         io_in_bits_status_dv,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  input  [1:0]  io_in_bits_status_prv,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  input         io_in_bits_status_v,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  input         io_in_bits_status_mpv,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  input         io_in_bits_status_gva,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  input         io_in_bits_status_tsr,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  input         io_in_bits_status_tw,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  input         io_in_bits_status_tvm,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  input         io_in_bits_status_mxr,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  input         io_in_bits_status_sum,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  input         io_in_bits_status_mprv,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  input  [1:0]  io_in_bits_status_fs,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  input  [1:0]  io_in_bits_status_mpp,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  input  [1:0]  io_in_bits_status_vs,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  input         io_in_bits_status_spp,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  input         io_in_bits_status_mpie,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  input         io_in_bits_status_spie,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  input         io_in_bits_status_mie,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  input         io_in_bits_status_sie,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  input         io_out_0_ready,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output        io_out_0_valid,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output [6:0]  io_out_0_bits_inst_funct,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output [4:0]  io_out_0_bits_inst_rs2,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output [4:0]  io_out_0_bits_inst_rs1,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output        io_out_0_bits_inst_xd,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output        io_out_0_bits_inst_xs1,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output        io_out_0_bits_inst_xs2,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output [4:0]  io_out_0_bits_inst_rd,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output [6:0]  io_out_0_bits_inst_opcode,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output [63:0] io_out_0_bits_rs1,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output [63:0] io_out_0_bits_rs2,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output        io_out_0_bits_status_debug,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output        io_out_0_bits_status_cease,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output        io_out_0_bits_status_wfi,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output [31:0] io_out_0_bits_status_isa,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output [1:0]  io_out_0_bits_status_dprv,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output        io_out_0_bits_status_dv,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output [1:0]  io_out_0_bits_status_prv,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output        io_out_0_bits_status_v,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output        io_out_0_bits_status_sd,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output [22:0] io_out_0_bits_status_zero2,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output        io_out_0_bits_status_mpv,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output        io_out_0_bits_status_gva,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output        io_out_0_bits_status_mbe,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output        io_out_0_bits_status_sbe,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output [1:0]  io_out_0_bits_status_sxl,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output [1:0]  io_out_0_bits_status_uxl,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output        io_out_0_bits_status_sd_rv32,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output [7:0]  io_out_0_bits_status_zero1,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output        io_out_0_bits_status_tsr,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output        io_out_0_bits_status_tw,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output        io_out_0_bits_status_tvm,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output        io_out_0_bits_status_mxr,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output        io_out_0_bits_status_sum,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output        io_out_0_bits_status_mprv,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output [1:0]  io_out_0_bits_status_xs,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output [1:0]  io_out_0_bits_status_fs,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output [1:0]  io_out_0_bits_status_mpp,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output [1:0]  io_out_0_bits_status_vs,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output        io_out_0_bits_status_spp,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output        io_out_0_bits_status_mpie,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output        io_out_0_bits_status_ube,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output        io_out_0_bits_status_spie,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output        io_out_0_bits_status_upie,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output        io_out_0_bits_status_mie,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output        io_out_0_bits_status_hie,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output        io_out_0_bits_status_sie,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output        io_out_0_bits_status_uie,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  input         io_out_1_ready,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output        io_out_1_valid,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output [6:0]  io_out_1_bits_inst_funct,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output [4:0]  io_out_1_bits_inst_rs2,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output [4:0]  io_out_1_bits_inst_rs1,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output        io_out_1_bits_inst_xd,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output        io_out_1_bits_inst_xs1,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output        io_out_1_bits_inst_xs2,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output [4:0]  io_out_1_bits_inst_rd,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output [6:0]  io_out_1_bits_inst_opcode,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output [63:0] io_out_1_bits_rs1,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output [63:0] io_out_1_bits_rs2,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output        io_out_1_bits_status_debug,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output        io_out_1_bits_status_cease,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output        io_out_1_bits_status_wfi,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output [31:0] io_out_1_bits_status_isa,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output [1:0]  io_out_1_bits_status_dprv,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output        io_out_1_bits_status_dv,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output [1:0]  io_out_1_bits_status_prv,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output        io_out_1_bits_status_v,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output        io_out_1_bits_status_sd,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output [22:0] io_out_1_bits_status_zero2,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output        io_out_1_bits_status_mpv,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output        io_out_1_bits_status_gva,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output        io_out_1_bits_status_mbe,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output        io_out_1_bits_status_sbe,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output [1:0]  io_out_1_bits_status_sxl,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output [1:0]  io_out_1_bits_status_uxl,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output        io_out_1_bits_status_sd_rv32,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output [7:0]  io_out_1_bits_status_zero1,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output        io_out_1_bits_status_tsr,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output        io_out_1_bits_status_tw,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output        io_out_1_bits_status_tvm,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output        io_out_1_bits_status_mxr,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output        io_out_1_bits_status_sum,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output        io_out_1_bits_status_mprv,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output [1:0]  io_out_1_bits_status_xs,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output [1:0]  io_out_1_bits_status_fs,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output [1:0]  io_out_1_bits_status_mpp,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output [1:0]  io_out_1_bits_status_vs,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output        io_out_1_bits_status_spp,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output        io_out_1_bits_status_mpie,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output        io_out_1_bits_status_ube,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output        io_out_1_bits_status_spie,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output        io_out_1_bits_status_upie,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output        io_out_1_bits_status_mie,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output        io_out_1_bits_status_hie,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output        io_out_1_bits_status_sie,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output        io_out_1_bits_status_uie,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output        io_busy,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output        io_loopconv_request_accept_0,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output        io_loopconv_request_accept_1,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output [7:0]  io_loopconv_request_queue_count_0,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output [7:0]  io_loopconv_request_queue_count_1,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output        io_loopconv_assembler_partial_0,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
  output        io_loopconv_assembler_partial_1	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:728:14]
);

  wire _paths_1_io_in_ready;	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:743:38]
  wire _paths_1_io_busy;	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:743:38]
  wire _paths_1_io_replay_release;	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:743:38]
  wire _paths_0_io_in_ready;	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:743:38]
  wire _paths_0_io_busy;	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:743:38]
  wire _paths_0_io_replay_release;	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:743:38]
  wire matches_0 = io_in_bits_inst_opcode == 7'h7B;	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:430:41]
  wire matches_1 = io_in_bits_inst_opcode == 7'h5B;	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:430:41]
  `ifndef SYNTHESIS	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:772:9]
    wire [1:0] _GEN = {1'h0, matches_0} + {1'h0, matches_1};	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:430:41, :772:18]
    always @(posedge clock) begin	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:772:9]
      if (~reset & _GEN[1]) begin	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:772:{9,18,37}]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:772:9]
          $error("Assertion failed: Custom opcode matched for more than one accelerator\n    at LazyRoCC.scala:772 assert(PopCount(VecInit(matches)) <= 1.U,\n");	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:772:9]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:772:9]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:772:9]
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
  RegisteredIngressAtomicReserve paths_0 (	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:743:38]
    .clock                      (clock),
    .reset                      (reset),
    .io_in_ready                (_paths_0_io_in_ready),
    .io_in_valid                (io_in_valid & matches_0),	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:430:41, :747:37]
    .io_in_bits_inst_funct      (io_in_bits_inst_funct),
    .io_in_bits_inst_rs2        (io_in_bits_inst_rs2),
    .io_in_bits_inst_rs1        (io_in_bits_inst_rs1),
    .io_in_bits_inst_xd         (io_in_bits_inst_xd),
    .io_in_bits_inst_xs1        (io_in_bits_inst_xs1),
    .io_in_bits_inst_xs2        (io_in_bits_inst_xs2),
    .io_in_bits_inst_rd         (io_in_bits_inst_rd),
    .io_in_bits_inst_opcode     (io_in_bits_inst_opcode),
    .io_in_bits_rs1             (io_in_bits_rs1),
    .io_in_bits_rs2             (io_in_bits_rs2),
    .io_in_bits_status_debug    (io_in_bits_status_debug),
    .io_in_bits_status_cease    (io_in_bits_status_cease),
    .io_in_bits_status_wfi      (io_in_bits_status_wfi),
    .io_in_bits_status_isa      (io_in_bits_status_isa),
    .io_in_bits_status_dprv     (io_in_bits_status_dprv),
    .io_in_bits_status_dv       (io_in_bits_status_dv),
    .io_in_bits_status_prv      (io_in_bits_status_prv),
    .io_in_bits_status_v        (io_in_bits_status_v),
    .io_in_bits_status_mpv      (io_in_bits_status_mpv),
    .io_in_bits_status_gva      (io_in_bits_status_gva),
    .io_in_bits_status_tsr      (io_in_bits_status_tsr),
    .io_in_bits_status_tw       (io_in_bits_status_tw),
    .io_in_bits_status_tvm      (io_in_bits_status_tvm),
    .io_in_bits_status_mxr      (io_in_bits_status_mxr),
    .io_in_bits_status_sum      (io_in_bits_status_sum),
    .io_in_bits_status_mprv     (io_in_bits_status_mprv),
    .io_in_bits_status_fs       (io_in_bits_status_fs),
    .io_in_bits_status_mpp      (io_in_bits_status_mpp),
    .io_in_bits_status_vs       (io_in_bits_status_vs),
    .io_in_bits_status_spp      (io_in_bits_status_spp),
    .io_in_bits_status_mpie     (io_in_bits_status_mpie),
    .io_in_bits_status_spie     (io_in_bits_status_spie),
    .io_in_bits_status_mie      (io_in_bits_status_mie),
    .io_in_bits_status_sie      (io_in_bits_status_sie),
    .io_out_ready               (io_out_0_ready),
    .io_out_valid               (io_out_0_valid),
    .io_out_bits_inst_funct     (io_out_0_bits_inst_funct),
    .io_out_bits_inst_rs2       (io_out_0_bits_inst_rs2),
    .io_out_bits_inst_rs1       (io_out_0_bits_inst_rs1),
    .io_out_bits_inst_xd        (io_out_0_bits_inst_xd),
    .io_out_bits_inst_xs1       (io_out_0_bits_inst_xs1),
    .io_out_bits_inst_xs2       (io_out_0_bits_inst_xs2),
    .io_out_bits_inst_rd        (io_out_0_bits_inst_rd),
    .io_out_bits_inst_opcode    (io_out_0_bits_inst_opcode),
    .io_out_bits_rs1            (io_out_0_bits_rs1),
    .io_out_bits_rs2            (io_out_0_bits_rs2),
    .io_out_bits_status_debug   (io_out_0_bits_status_debug),
    .io_out_bits_status_cease   (io_out_0_bits_status_cease),
    .io_out_bits_status_wfi     (io_out_0_bits_status_wfi),
    .io_out_bits_status_isa     (io_out_0_bits_status_isa),
    .io_out_bits_status_dprv    (io_out_0_bits_status_dprv),
    .io_out_bits_status_dv      (io_out_0_bits_status_dv),
    .io_out_bits_status_prv     (io_out_0_bits_status_prv),
    .io_out_bits_status_v       (io_out_0_bits_status_v),
    .io_out_bits_status_sd      (io_out_0_bits_status_sd),
    .io_out_bits_status_zero2   (io_out_0_bits_status_zero2),
    .io_out_bits_status_mpv     (io_out_0_bits_status_mpv),
    .io_out_bits_status_gva     (io_out_0_bits_status_gva),
    .io_out_bits_status_mbe     (io_out_0_bits_status_mbe),
    .io_out_bits_status_sbe     (io_out_0_bits_status_sbe),
    .io_out_bits_status_sxl     (io_out_0_bits_status_sxl),
    .io_out_bits_status_uxl     (io_out_0_bits_status_uxl),
    .io_out_bits_status_sd_rv32 (io_out_0_bits_status_sd_rv32),
    .io_out_bits_status_zero1   (io_out_0_bits_status_zero1),
    .io_out_bits_status_tsr     (io_out_0_bits_status_tsr),
    .io_out_bits_status_tw      (io_out_0_bits_status_tw),
    .io_out_bits_status_tvm     (io_out_0_bits_status_tvm),
    .io_out_bits_status_mxr     (io_out_0_bits_status_mxr),
    .io_out_bits_status_sum     (io_out_0_bits_status_sum),
    .io_out_bits_status_mprv    (io_out_0_bits_status_mprv),
    .io_out_bits_status_xs      (io_out_0_bits_status_xs),
    .io_out_bits_status_fs      (io_out_0_bits_status_fs),
    .io_out_bits_status_mpp     (io_out_0_bits_status_mpp),
    .io_out_bits_status_vs      (io_out_0_bits_status_vs),
    .io_out_bits_status_spp     (io_out_0_bits_status_spp),
    .io_out_bits_status_mpie    (io_out_0_bits_status_mpie),
    .io_out_bits_status_ube     (io_out_0_bits_status_ube),
    .io_out_bits_status_spie    (io_out_0_bits_status_spie),
    .io_out_bits_status_upie    (io_out_0_bits_status_upie),
    .io_out_bits_status_mie     (io_out_0_bits_status_mie),
    .io_out_bits_status_hie     (io_out_0_bits_status_hie),
    .io_out_bits_status_sie     (io_out_0_bits_status_sie),
    .io_out_bits_status_uie     (io_out_0_bits_status_uie),
    .io_busy                    (_paths_0_io_busy),
    .io_request_accept          (io_loopconv_request_accept_0),
    .io_request_queue_count     (io_loopconv_request_queue_count_0),
    .io_assembler_partial       (io_loopconv_assembler_partial_0),
    .io_replay_release          (_paths_0_io_replay_release)
  );	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:743:38]
  RegisteredIngressAtomicReserve paths_1 (	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:743:38]
    .clock                      (clock),
    .reset                      (reset),
    .io_in_ready                (_paths_1_io_in_ready),
    .io_in_valid                (io_in_valid & matches_1),	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:430:41, :747:37]
    .io_in_bits_inst_funct      (io_in_bits_inst_funct),
    .io_in_bits_inst_rs2        (io_in_bits_inst_rs2),
    .io_in_bits_inst_rs1        (io_in_bits_inst_rs1),
    .io_in_bits_inst_xd         (io_in_bits_inst_xd),
    .io_in_bits_inst_xs1        (io_in_bits_inst_xs1),
    .io_in_bits_inst_xs2        (io_in_bits_inst_xs2),
    .io_in_bits_inst_rd         (io_in_bits_inst_rd),
    .io_in_bits_inst_opcode     (io_in_bits_inst_opcode),
    .io_in_bits_rs1             (io_in_bits_rs1),
    .io_in_bits_rs2             (io_in_bits_rs2),
    .io_in_bits_status_debug    (io_in_bits_status_debug),
    .io_in_bits_status_cease    (io_in_bits_status_cease),
    .io_in_bits_status_wfi      (io_in_bits_status_wfi),
    .io_in_bits_status_isa      (io_in_bits_status_isa),
    .io_in_bits_status_dprv     (io_in_bits_status_dprv),
    .io_in_bits_status_dv       (io_in_bits_status_dv),
    .io_in_bits_status_prv      (io_in_bits_status_prv),
    .io_in_bits_status_v        (io_in_bits_status_v),
    .io_in_bits_status_mpv      (io_in_bits_status_mpv),
    .io_in_bits_status_gva      (io_in_bits_status_gva),
    .io_in_bits_status_tsr      (io_in_bits_status_tsr),
    .io_in_bits_status_tw       (io_in_bits_status_tw),
    .io_in_bits_status_tvm      (io_in_bits_status_tvm),
    .io_in_bits_status_mxr      (io_in_bits_status_mxr),
    .io_in_bits_status_sum      (io_in_bits_status_sum),
    .io_in_bits_status_mprv     (io_in_bits_status_mprv),
    .io_in_bits_status_fs       (io_in_bits_status_fs),
    .io_in_bits_status_mpp      (io_in_bits_status_mpp),
    .io_in_bits_status_vs       (io_in_bits_status_vs),
    .io_in_bits_status_spp      (io_in_bits_status_spp),
    .io_in_bits_status_mpie     (io_in_bits_status_mpie),
    .io_in_bits_status_spie     (io_in_bits_status_spie),
    .io_in_bits_status_mie      (io_in_bits_status_mie),
    .io_in_bits_status_sie      (io_in_bits_status_sie),
    .io_out_ready               (io_out_1_ready),
    .io_out_valid               (io_out_1_valid),
    .io_out_bits_inst_funct     (io_out_1_bits_inst_funct),
    .io_out_bits_inst_rs2       (io_out_1_bits_inst_rs2),
    .io_out_bits_inst_rs1       (io_out_1_bits_inst_rs1),
    .io_out_bits_inst_xd        (io_out_1_bits_inst_xd),
    .io_out_bits_inst_xs1       (io_out_1_bits_inst_xs1),
    .io_out_bits_inst_xs2       (io_out_1_bits_inst_xs2),
    .io_out_bits_inst_rd        (io_out_1_bits_inst_rd),
    .io_out_bits_inst_opcode    (io_out_1_bits_inst_opcode),
    .io_out_bits_rs1            (io_out_1_bits_rs1),
    .io_out_bits_rs2            (io_out_1_bits_rs2),
    .io_out_bits_status_debug   (io_out_1_bits_status_debug),
    .io_out_bits_status_cease   (io_out_1_bits_status_cease),
    .io_out_bits_status_wfi     (io_out_1_bits_status_wfi),
    .io_out_bits_status_isa     (io_out_1_bits_status_isa),
    .io_out_bits_status_dprv    (io_out_1_bits_status_dprv),
    .io_out_bits_status_dv      (io_out_1_bits_status_dv),
    .io_out_bits_status_prv     (io_out_1_bits_status_prv),
    .io_out_bits_status_v       (io_out_1_bits_status_v),
    .io_out_bits_status_sd      (io_out_1_bits_status_sd),
    .io_out_bits_status_zero2   (io_out_1_bits_status_zero2),
    .io_out_bits_status_mpv     (io_out_1_bits_status_mpv),
    .io_out_bits_status_gva     (io_out_1_bits_status_gva),
    .io_out_bits_status_mbe     (io_out_1_bits_status_mbe),
    .io_out_bits_status_sbe     (io_out_1_bits_status_sbe),
    .io_out_bits_status_sxl     (io_out_1_bits_status_sxl),
    .io_out_bits_status_uxl     (io_out_1_bits_status_uxl),
    .io_out_bits_status_sd_rv32 (io_out_1_bits_status_sd_rv32),
    .io_out_bits_status_zero1   (io_out_1_bits_status_zero1),
    .io_out_bits_status_tsr     (io_out_1_bits_status_tsr),
    .io_out_bits_status_tw      (io_out_1_bits_status_tw),
    .io_out_bits_status_tvm     (io_out_1_bits_status_tvm),
    .io_out_bits_status_mxr     (io_out_1_bits_status_mxr),
    .io_out_bits_status_sum     (io_out_1_bits_status_sum),
    .io_out_bits_status_mprv    (io_out_1_bits_status_mprv),
    .io_out_bits_status_xs      (io_out_1_bits_status_xs),
    .io_out_bits_status_fs      (io_out_1_bits_status_fs),
    .io_out_bits_status_mpp     (io_out_1_bits_status_mpp),
    .io_out_bits_status_vs      (io_out_1_bits_status_vs),
    .io_out_bits_status_spp     (io_out_1_bits_status_spp),
    .io_out_bits_status_mpie    (io_out_1_bits_status_mpie),
    .io_out_bits_status_ube     (io_out_1_bits_status_ube),
    .io_out_bits_status_spie    (io_out_1_bits_status_spie),
    .io_out_bits_status_upie    (io_out_1_bits_status_upie),
    .io_out_bits_status_mie     (io_out_1_bits_status_mie),
    .io_out_bits_status_hie     (io_out_1_bits_status_hie),
    .io_out_bits_status_sie     (io_out_1_bits_status_sie),
    .io_out_bits_status_uie     (io_out_1_bits_status_uie),
    .io_busy                    (_paths_1_io_busy),
    .io_request_accept          (io_loopconv_request_accept_1),
    .io_request_queue_count     (io_loopconv_request_queue_count_1),
    .io_assembler_partial       (io_loopconv_assembler_partial_1),
    .io_replay_release          (_paths_1_io_replay_release)
  );	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:743:38]
  assign io_in_ready = matches_0 & _paths_0_io_in_ready | matches_1 & _paths_1_io_in_ready | _paths_0_io_replay_release | _paths_1_io_replay_release;	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:430:41, :726:7, :743:38, :756:59, :765:21, :766:{47,72}]
  assign io_busy = io_in_valid | _paths_0_io_busy | _paths_1_io_busy;	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:726:7, :743:38, :769:{26,65}]
endmodule

