// Generated by CIRCT firtool-1.75.0
module ShiftBlock_8(	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:12:7]
  input  [7:0] io_in,	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:13:14]
  input  [3:0] io_shamt,	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:13:14]
  input        io_shl,	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:13:14]
  input        io_sign,	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:13:14]
  input  [1:0] io_rm,	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:13:14]
  output [7:0] io_out,	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:13:14]
  output       io_round	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:13:14]
);

  wire [9:0]  _full_shifted_T_33 = $signed($signed({io_shl ? {1'h0, io_in[0], io_in[1], io_in[2], io_in[3], io_in[4], io_in[5], io_in[6], io_in[7]} : {io_sign, io_in}, 1'h0}) >>> io_shamt);	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:22:26, :23:{8,25}, :24:{8,42}]
  wire [15:0] _io_round_T_2 = 16'h1 << io_shamt;	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:30:25]
  wire [8:0]  _io_round_T_3 = _io_round_T_2[8:0] - 9'h1;	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:30:{25,38}]
  wire [7:0]  _io_round_T_7 = io_in & _io_round_T_3[8:1];	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:30:{16,38,45,50}]
  assign io_out = io_shl ? {_full_shifted_T_33[1], _full_shifted_T_33[2], _full_shifted_T_33[3], _full_shifted_T_33[4], _full_shifted_T_33[5], _full_shifted_T_33[6], _full_shifted_T_33[7], _full_shifted_T_33[8]} : _full_shifted_T_33[8:1];	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:12:7, :24:{42,54}, :26:29, :28:{16,32}]
  assign io_round = (&io_rm) ? ~(_full_shifted_T_33[1]) & (|{_full_shifted_T_33[0], _io_round_T_7}) : io_rm != 2'h2 & (io_rm != 2'h1 | (|_io_round_T_7) | _full_shifted_T_33[1]) & _full_shifted_T_33[0];	// @[generators/saturn/src/main/scala/exu/Rounding.scala:8:106, :10:{35,63}, :12:{14,19,25,58}, generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:12:7, :24:{42,54}, :26:29, :29:{47,64}, :30:16]
endmodule

