`timescale 1ns/1ps

// Integration boundary for the camera ingress and HDMI subsystems.
module camera_hdmi_subsystem (
    input wire sys_rstn,
    input wire sys_init_done,
    input wire camera_ref_clk,
    axi4_if.slave mmio_axi,
    axis_video_if.sink display_axis,
    video_stream_if.source camera_capture_channels [8],
    video_stream_if.source hdmi_capture_channels [8],
    input wire hdmi_capture_enable,
    axi_lite_if.master framebuffer_axil,
    input wire capture_clk,
    input wire capture_resetn,

    output wire [7:0] cam_rst_n,
    output wire [7:0] cam_pwdn,
    output wire [7:0] cam_scl,
    inout wire [7:0] cam_sda,
    output wire [7:0] cam_xclk,
    input wire [7:0] cam_xclk_pad,
    input wire [7:0] cam_rst_n_pad,
    input wire [7:0] cam_pwdn_pad,
    input wire [7:0] cam_scl_pad,
    input wire [7:0] cam_pclk,
    input wire [7:0] cam_vsync,
    input wire [7:0] cam_href,
    input wire [63:0] cam_data,
    input wire hdmi_rx_clk_p,
    input wire hdmi_rx_clk_n,
    input wire [2:0] hdmi_rx_data_p,
    input wire [2:0] hdmi_rx_data_n,
    output wire hdmi_ref_clk_p,
    output wire hdmi_ref_clk_n,
    input wire hdmi_tx_refclk_p,
    input wire hdmi_tx_refclk_n,
    input wire hdmi_tx_hpd,
    inout wire hdmi_tx_ddc_scl,
    inout wire hdmi_tx_ddc_sda,
    output wire [3:0] hdmi_tx_data_p,
    output wire [3:0] hdmi_tx_data_n,
    output wire hdmi_tx_en,
    output wire hdmi_tx_locked,
    input wire hdmi_rx_pwr_det,
    output wire hdmi_rx_hpd,
    inout wire hdmi_rx_ddc_scl,
    inout wire hdmi_rx_ddc_sda,
    inout wire hdmi_clkchip_scl,
    inout wire hdmi_clkchip_sda,
    input wire hdmi_clkchip_lol,
    input wire hdmi_clkchip_int,
    output wire hdmi_clkchip_rst,
    output wire camera_pll_locked,
    output wire [479:0] camera_axis_diag,
    output wire [255:0] malformed_counts,
    output wire [7:0] video_interrupts,
    output wire [31:0] hdmi_transport_frame_count,
    output wire [31:0] hdmi_transport_malformed_count,
    output wire [255:0] hdmi_channel_overflow_counts,
    output wire [255:0] hdmi_channel_frame_counts
);
    axi_lite_if #(.ADDR_WIDTH(18)) camera_axil [8]();

    hdmi_subsystem u_hdmi (
        .mmio_axi(mmio_axi), .display_axis(display_axis),
        .hdmi_capture_channels(hdmi_capture_channels),
        .hdmi_capture_enable(hdmi_capture_enable),
        .framebuffer_axil(framebuffer_axil), .camera_axil(camera_axil),
        .capture_clk(capture_clk), .capture_resetn(capture_resetn),
        .hdmi_rx_clk_p(hdmi_rx_clk_p), .hdmi_rx_clk_n(hdmi_rx_clk_n),
        .hdmi_rx_data_p(hdmi_rx_data_p), .hdmi_rx_data_n(hdmi_rx_data_n),
        .hdmi_ref_clk_p(hdmi_ref_clk_p), .hdmi_ref_clk_n(hdmi_ref_clk_n),
        .hdmi_tx_refclk_p(hdmi_tx_refclk_p),
        .hdmi_tx_refclk_n(hdmi_tx_refclk_n), .hdmi_tx_hpd(hdmi_tx_hpd),
        .hdmi_tx_ddc_scl(hdmi_tx_ddc_scl),
        .hdmi_tx_ddc_sda(hdmi_tx_ddc_sda),
        .hdmi_tx_data_p(hdmi_tx_data_p), .hdmi_tx_data_n(hdmi_tx_data_n),
        .hdmi_tx_en(hdmi_tx_en), .hdmi_tx_locked(hdmi_tx_locked),
        .hdmi_rx_pwr_det(hdmi_rx_pwr_det), .hdmi_rx_hpd(hdmi_rx_hpd),
        .hdmi_rx_ddc_scl(hdmi_rx_ddc_scl),
        .hdmi_rx_ddc_sda(hdmi_rx_ddc_sda),
        .hdmi_clkchip_scl(hdmi_clkchip_scl),
        .hdmi_clkchip_sda(hdmi_clkchip_sda),
        .hdmi_clkchip_lol(hdmi_clkchip_lol),
        .hdmi_clkchip_int(hdmi_clkchip_int),
        .hdmi_clkchip_rst(hdmi_clkchip_rst),
        .video_interrupts(video_interrupts),
        .hdmi_transport_frame_count(hdmi_transport_frame_count),
        .hdmi_transport_malformed_count(hdmi_transport_malformed_count),
        .hdmi_channel_overflow_counts(hdmi_channel_overflow_counts),
        .hdmi_channel_frame_counts(hdmi_channel_frame_counts)
    );

    camera_subsystem u_camera_subsystem (
        .sys_rstn(sys_rstn), .sys_init_done(sys_init_done),
        .camera_ref_clk(camera_ref_clk), .capture_clk(capture_clk),
        .capture_resetn(capture_resetn), .camera_axil(camera_axil),
        .capture_channels(camera_capture_channels),
        .cam_rst_n(cam_rst_n), .cam_pwdn(cam_pwdn), .cam_scl(cam_scl),
        .cam_sda(cam_sda), .cam_xclk(cam_xclk),
        .cam_xclk_pad(cam_xclk_pad), .cam_rst_n_pad(cam_rst_n_pad),
        .cam_pwdn_pad(cam_pwdn_pad), .cam_scl_pad(cam_scl_pad),
        .cam_pclk(cam_pclk), .cam_vsync(cam_vsync), .cam_href(cam_href),
        .cam_data(cam_data), .camera_pll_locked(camera_pll_locked),
        .camera_axis_diag(camera_axis_diag),
        .malformed_counts(malformed_counts)
    );
endmodule
