`timescale 1ns/1ps

// Shared HDMI physical layer. RX and TX must share this VPHY instance because
// it owns the board GT resources and both link/status interfaces.
module hdmi_phy_subsystem (
    axi_lite_if.slave vphy_axil,
    input wire hdmi_rx_clk_p,
    input wire hdmi_rx_clk_n,
    input wire [2:0] hdmi_rx_data_p,
    input wire [2:0] hdmi_rx_data_n,
    output wire hdmi_ref_clk_p,
    output wire hdmi_ref_clk_n,
    input wire hdmi_tx_refclk_p,
    input wire hdmi_tx_refclk_n,
    input wire tx_refclk_rdy,
    output wire [3:0] hdmi_tx_data_p,
    output wire [3:0] hdmi_tx_data_n,
    input wire [2:0][39:0] tx_link_data,
    input wire [2:0] tx_link_valid,
    output wire [2:0][39:0] rx_link_data,
    output wire [2:0] rx_link_valid,
    output wire [7:0] tx_sb_data,
    output wire tx_sb_valid,
    output wire [7:0] rx_sb_data,
    output wire rx_sb_valid,
    output wire txoutclk,
    output wire rxoutclk,
    output wire tx_video_clk,
    output wire rx_video_clk,
    output wire vphy_irq
);
    wire tx_refclk, tx_refclk_div2, tx_refclk_bufg;

    tx_refclk_ibuf u_tx_refclk_ibuf (
        .IBUF_DS_P(hdmi_tx_refclk_p), .IBUF_DS_N(hdmi_tx_refclk_n),
        .IBUF_OUT(tx_refclk), .IBUF_DS_ODIV2(tx_refclk_div2)
    );
    tx_refclk_bufg u_tx_refclk_bufg (
        .BUFG_GT_I(tx_refclk_div2), .BUFG_GT_CE(1'b1),
        .BUFG_GT_CEMASK(1'b0), .BUFG_GT_CLR(1'b0),
        .BUFG_GT_CLRMASK(1'b0), .BUFG_GT_DIV(3'b000),
        .BUFG_GT_O(tx_refclk_bufg)
    );

    vid_phy_controller_0 u_vphy (
        .tx_refclk_rdy(tx_refclk_rdy), .tx_tmds_clk(),
        .tx_video_clk(tx_video_clk), .rx_tmds_clk(),
        .rx_video_clk(rx_video_clk),
        .rx_tmds_clk_p(hdmi_ref_clk_p), .rx_tmds_clk_n(hdmi_ref_clk_n),
        .mgtrefclk0_pad_p_in(hdmi_rx_clk_p),
        .mgtrefclk0_pad_n_in(hdmi_rx_clk_n),
        .gtsouthrefclk0_in(tx_refclk),
        .gtsouthrefclk0_odiv2_in(tx_refclk_bufg),
        .gtsouthrefclk00_in(tx_refclk), .gtsouthrefclk01_in(tx_refclk),
        .txrefclk_ceb(), .phy_rxn_in(hdmi_rx_data_n),
        .phy_rxp_in(hdmi_rx_data_p), .phy_txn_out(hdmi_tx_data_n),
        .phy_txp_out(hdmi_tx_data_p), .rxoutclk(rxoutclk),
        .txoutclk(txoutclk),
        .vid_phy_tx_axi4s_aclk(txoutclk),
        .vid_phy_tx_axi4s_aresetn(1'b1),
        .vid_phy_tx_axi4s_ch0_tdata(tx_link_data[0]),
        .vid_phy_tx_axi4s_ch0_tuser(1'b0),
        .vid_phy_tx_axi4s_ch0_tvalid(tx_link_valid[0]),
        .vid_phy_tx_axi4s_ch0_tready(),
        .vid_phy_tx_axi4s_ch1_tdata(tx_link_data[1]),
        .vid_phy_tx_axi4s_ch1_tuser(1'b0),
        .vid_phy_tx_axi4s_ch1_tvalid(tx_link_valid[1]),
        .vid_phy_tx_axi4s_ch1_tready(),
        .vid_phy_tx_axi4s_ch2_tdata(tx_link_data[2]),
        .vid_phy_tx_axi4s_ch2_tuser(1'b0),
        .vid_phy_tx_axi4s_ch2_tvalid(tx_link_valid[2]),
        .vid_phy_tx_axi4s_ch2_tready(),
        .vid_phy_rx_axi4s_aclk(rxoutclk),
        .vid_phy_rx_axi4s_aresetn(1'b1),
        .vid_phy_rx_axi4s_ch0_tdata(rx_link_data[0]),
        .vid_phy_rx_axi4s_ch0_tuser(),
        .vid_phy_rx_axi4s_ch0_tvalid(rx_link_valid[0]),
        .vid_phy_rx_axi4s_ch0_tready(1'b1),
        .vid_phy_rx_axi4s_ch1_tdata(rx_link_data[1]),
        .vid_phy_rx_axi4s_ch1_tuser(),
        .vid_phy_rx_axi4s_ch1_tvalid(rx_link_valid[1]),
        .vid_phy_rx_axi4s_ch1_tready(1'b1),
        .vid_phy_rx_axi4s_ch2_tdata(rx_link_data[2]),
        .vid_phy_rx_axi4s_ch2_tuser(),
        .vid_phy_rx_axi4s_ch2_tvalid(rx_link_valid[2]),
        .vid_phy_rx_axi4s_ch2_tready(1'b1),
        .irq(vphy_irq), .vid_phy_sb_aclk(vphy_axil.aclk),
        .vid_phy_sb_aresetn(vphy_axil.aresetn),
        .vid_phy_status_sb_tx_tdata(tx_sb_data),
        .vid_phy_status_sb_tx_tvalid(tx_sb_valid),
        .vid_phy_status_sb_tx_tready(1'b1),
        .vid_phy_status_sb_rx_tdata(rx_sb_data),
        .vid_phy_status_sb_rx_tvalid(rx_sb_valid),
        .vid_phy_status_sb_rx_tready(1'b1),
        .vid_phy_axi4lite_awaddr(vphy_axil.awaddr),
        .vid_phy_axi4lite_awprot(vphy_axil.awprot),
        .vid_phy_axi4lite_awvalid(vphy_axil.awvalid),
        .vid_phy_axi4lite_awready(vphy_axil.awready),
        .vid_phy_axi4lite_wdata(vphy_axil.wdata),
        .vid_phy_axi4lite_wstrb(vphy_axil.wstrb),
        .vid_phy_axi4lite_wvalid(vphy_axil.wvalid),
        .vid_phy_axi4lite_wready(vphy_axil.wready),
        .vid_phy_axi4lite_bresp(vphy_axil.bresp),
        .vid_phy_axi4lite_bvalid(vphy_axil.bvalid),
        .vid_phy_axi4lite_bready(vphy_axil.bready),
        .vid_phy_axi4lite_araddr(vphy_axil.araddr),
        .vid_phy_axi4lite_arprot(vphy_axil.arprot),
        .vid_phy_axi4lite_arvalid(vphy_axil.arvalid),
        .vid_phy_axi4lite_arready(vphy_axil.arready),
        .vid_phy_axi4lite_rdata(vphy_axil.rdata),
        .vid_phy_axi4lite_rresp(vphy_axil.rresp),
        .vid_phy_axi4lite_rvalid(vphy_axil.rvalid),
        .vid_phy_axi4lite_rready(vphy_axil.rready),
        .vid_phy_axi4lite_aclk(vphy_axil.aclk),
        .vid_phy_axi4lite_aresetn(vphy_axil.aresetn),
        .drpclk(vphy_axil.aclk)
    );
endmodule
