#ifndef TINYYOLOV2_INPUT_CONTRACT_H
#define TINYYOLOV2_INPUT_CONTRACT_H

#define TINYYOLOV2_INPUT_WIDTH                 416
#define TINYYOLOV2_INPUT_HEIGHT                416
#define TINYYOLOV2_INPUT_CHANNELS              3

#define TINYYOLOV2_INPUT_BATCH                 1
#define TINYYOLOV2_INPUT_LAYOUT_NHWC           1
#define TINYYOLOV2_INPUT_CHANNEL_ORDER_RGB     1
#define TINYYOLOV2_INPUT_DATA_TYPE_INT8        1

#define TINYYOLOV2_INPUT_SCALE                 0.007874015748f
#define TINYYOLOV2_INPUT_SCALE_RECIPROCAL      127
#define TINYYOLOV2_INPUT_ZERO_POINT            0
#define TINYYOLOV2_INPUT_QUANT_MIN             (-128)
#define TINYYOLOV2_INPUT_QUANT_MAX             127
#define TINYYOLOV2_INPUT_ACTIVE_MIN            0
#define TINYYOLOV2_INPUT_ACTIVE_MAX            127

#define TINYYOLOV2_INPUT_RESIZE_PILLOW_BILINEAR 1
#define TINYYOLOV2_INPUT_LETTERBOX              0
#define TINYYOLOV2_INPUT_SOURCE_XRGB8888        1

#endif
