#ifndef HDMI_TX_TEST_PLATFORM_H
#define HDMI_TX_TEST_PLATFORM_H

#include <stdint.h>

#define SOC_CLOCK_HZ UINT64_C(100000000)
#define UART_BAUD    UINT64_C(115200)
#define UART_BASE    ((uintptr_t)0x10020000UL)

/* CPU-visible mmio-port-axi4 aperture in the Taihang SoC address map. */
#define VIDEO_MMIO_BASE ((uintptr_t)0x10040000UL)
#define AXI_GPIO_BASE (VIDEO_MMIO_BASE + 0x00000UL)
#define AXI_IIC_BASE  (VIDEO_MMIO_BASE + 0x10000UL)
#define VPHY_BASE     (VIDEO_MMIO_BASE + 0x20000UL)
#define HDMI_RX_BASE  (VIDEO_MMIO_BASE + 0x30000UL)
#define HDMI_TX_BASE  (VIDEO_MMIO_BASE + 0x40000UL)
#define HDMI_TX_VTC_BASE (VIDEO_MMIO_BASE + 0x50000UL)
#define FRAMEBUFFER_BASE (VIDEO_MMIO_BASE + 0x100000UL)
#define POSTPROCESS_DIAG_BASE (VIDEO_MMIO_BASE + 0x130000UL)

#define LOCAL_CAMERA_COUNT 8U
#define HDMI_CAMERA_COUNT 8U
#define VIDEO_CHANNEL_COUNT 16U
#define LOCAL_CAMERA_GLOBAL_BASE 1U
#define CAMERA_PRESENT_MASK UINT32_C(0xFF)

#define CAMERA_CH1_BLOCK_BASE (VIDEO_MMIO_BASE + 0x110000UL)
#define CAMERA_CH2_BLOCK_BASE (VIDEO_MMIO_BASE + 0x114000UL)
#define CAMERA_CH3_BLOCK_BASE (VIDEO_MMIO_BASE + 0x118000UL)
#define CAMERA_CH4_BLOCK_BASE (VIDEO_MMIO_BASE + 0x11C000UL)
#define CAMERA_CH5_BLOCK_BASE (VIDEO_MMIO_BASE + 0x120000UL)
#define CAMERA_CH6_BLOCK_BASE (VIDEO_MMIO_BASE + 0x124000UL)
#define CAMERA_CH7_BLOCK_BASE (VIDEO_MMIO_BASE + 0x128000UL)
#define CAMERA_CH8_BLOCK_BASE (VIDEO_MMIO_BASE + 0x12C000UL)
#define CAMERA_CSI_OFFSET      0x1000U

#define FRAMEBUFFER_CONTROL      0x00U
#define FRAMEBUFFER_STATUS       0x04U
#define FRAMEBUFFER_WIDTH        0x08U
#define FRAMEBUFFER_HEIGHT       0x0CU
#define FRAMEBUFFER_STRIDE       0x10U
#define FRAMEBUFFER_COUNT        0x14U
#define FRAMEBUFFER_DISPLAY_CH   0x18U
#define FRAMEBUFFER_PRESENT_MASK 0x1CU
#define FRAMEBUFFER_BASE0        0x20U
#define FRAMEBUFFER_BUFFER_STRIDE 0x60U
#define FRAMEBUFFER_DISPLAY_MODE  0x64U
#define FRAMEBUFFER_HDMI_CONTROL  0x68U
#define FRAMEBUFFER_WRITER_COUNT(channel) (0x80U + ((channel) * 4U))
#define FRAMEBUFFER_DROP_COUNT(channel) (0xC0U + ((channel) * 4U))
#define FRAMEBUFFER_MALFORMED(channel) (0x100U + ((channel) * 4U))
#define FRAMEBUFFER_READER_COUNT 0x140U
#define FRAMEBUFFER_UNDERFLOW    0x144U
#define FRAMEBUFFER_READER_BASE  0x148U
#define FRAMEBUFFER_READER_DEBUG 0x14CU
#define FRAMEBUFFER_WRITER_PERF_CURRENT 0x150U
#define FRAMEBUFFER_WRITER_PERF_MAX 0x154U
#define FRAMEBUFFER_WRITER_PERF_AW_STALL 0x158U
#define FRAMEBUFFER_WRITER_PERF_W_STALL 0x15CU
#define FRAMEBUFFER_WRITER_PERF_B_STALL 0x160U
#define FRAMEBUFFER_WRITER_PERF_ISSUED 0x164U
#define FRAMEBUFFER_WRITER_PERF_COMPLETED 0x168U
#define FRAMEBUFFER_WRITER_PERF_ERRORS 0x16CU
#define FRAMEBUFFER_HDMI_TRANSPORT_FRAMES 0x170U
#define FRAMEBUFFER_HDMI_TRANSPORT_MALFORMED 0x174U
#define FRAMEBUFFER_HDMI_FRAME_COUNT(channel) (0x180U + ((channel) * 4U))
#define FRAMEBUFFER_HDMI_OVERFLOW_COUNT(channel) (0x1A0U + ((channel) * 4U))
#define FRAMEBUFFER_AI_CONTROL       0x1C0U
#define FRAMEBUFFER_AI_STATUS        0x1C4U
#define FRAMEBUFFER_AI_RELEASE_MASK  0x1C8U
#define FRAMEBUFFER_AI_VALID_MASK    0x1CCU
#define FRAMEBUFFER_AI_FRESH_MASK    0x1D0U
#define FRAMEBUFFER_AI_HELD_MASK     0x1D4U
#define FRAMEBUFFER_AI_META_INDEX    0x1D8U
#define FRAMEBUFFER_AI_META_ADDR     0x1DCU
#define FRAMEBUFFER_AI_META_FRAME_LO 0x1E0U
#define FRAMEBUFFER_AI_META_FRAME_HI 0x1E4U
#define FRAMEBUFFER_AI_META_TIME_LO  0x1E8U
#define FRAMEBUFFER_AI_META_TIME_HI  0x1ECU
#define FRAMEBUFFER_AI_META_VERSION  0x1F0U
#define FRAMEBUFFER_AI_BATCH_LO      0x1F4U
#define FRAMEBUFFER_AI_BATCH_HI      0x1F8U
#define FRAMEBUFFER_AI_DIAG          0x1FCU

#define FRAMEBUFFER_AI_CONTROL_SNAPSHOT UINT32_C(1)
#define FRAMEBUFFER_AI_CONTROL_RELEASE  UINT32_C(2)

#define FRAMEBUFFER_PRE_CONTROL          0x200U
#define FRAMEBUFFER_PRE_STATUS           0x204U
#define FRAMEBUFFER_PRE_RECYCLE_MASK     0x208U
#define FRAMEBUFFER_PRE_PROGRESS         0x20CU
#define FRAMEBUFFER_PRE_ACTIVE_BASE      0x210U
#define FRAMEBUFFER_PRE_ARENA0_BATCH_LO  0x220U
#define FRAMEBUFFER_PRE_ARENA0_BATCH_HI  0x224U
#define FRAMEBUFFER_PRE_ARENA1_BATCH_LO  0x228U
#define FRAMEBUFFER_PRE_ARENA1_BATCH_HI  0x22CU
#define FRAMEBUFFER_PRE_ARENA0_VALID     0x230U
#define FRAMEBUFFER_PRE_ARENA1_VALID     0x234U
#define FRAMEBUFFER_PRE_ARENA0_FRESH     0x238U
#define FRAMEBUFFER_PRE_ARENA1_FRESH     0x23CU
#define FRAMEBUFFER_PRE_LAST_CYCLES      0x240U
#define FRAMEBUFFER_PRE_LAST_READ        0x244U
#define FRAMEBUFFER_PRE_LAST_WRITE       0x248U
#define FRAMEBUFFER_PRE_START_COUNT      0x24CU
#define FRAMEBUFFER_PRE_COMPLETE_COUNT   0x250U
#define FRAMEBUFFER_PRE_ERROR_COUNT      0x254U
#define FRAMEBUFFER_PRE_ARENA0_BASE       0x280U
#define FRAMEBUFFER_PRE_ARENA1_BASE       0x284U
#define FRAMEBUFFER_PRE_MEMBER_STRIDE     0x288U
#define FRAMEBUFFER_PRE_MEMBER_BYTES      0x28CU
#define FRAMEBUFFER_PRE_FORMAT             0x290U

#define FRAMEBUFFER_OVERLAY_CONTROL      0x260U
#define FRAMEBUFFER_OVERLAY_STREAM       0x264U
#define FRAMEBUFFER_OVERLAY_COUNT        0x268U
#define FRAMEBUFFER_OVERLAY_BOX_INDEX    0x26CU
#define FRAMEBUFFER_OVERLAY_BOX_XY0      0x270U
#define FRAMEBUFFER_OVERLAY_BOX_XY1      0x274U
#define FRAMEBUFFER_OVERLAY_BOX_CLASS    0x278U
#define FRAMEBUFFER_OVERLAY_LABEL0       0x294U
#define FRAMEBUFFER_OVERLAY_LABEL1       0x298U
#define FRAMEBUFFER_OVERLAY_LABEL2       0x29CU
#define FRAMEBUFFER_OVERLAY_LABEL3       0x2A0U

#define FRAMEBUFFER_OVERLAY_CONTROL_COMMIT UINT32_C(1)
#define FRAMEBUFFER_OVERLAY_CONTROL_BUSY   UINT32_C(2)

#define FRAMEBUFFER_PRE_CONTROL_START   UINT32_C(1)
#define FRAMEBUFFER_PRE_CONTROL_RECYCLE UINT32_C(2)
#define FRAMEBUFFER_PRE_STATUS_START_BUSY   UINT32_C(1)
#define FRAMEBUFFER_PRE_STATUS_RECYCLE_BUSY UINT32_C(2)
#define FRAMEBUFFER_PRE_STATUS_ENGINE_BUSY  UINT32_C(4)
#define FRAMEBUFFER_PRE_STATUS_READY_SHIFT 3U
#define FRAMEBUFFER_PRE_STATUS_READY_MASK  UINT32_C(0x18)
#define FRAMEBUFFER_PRE_FORMAT_416X416     UINT32_C(0)
#define FRAMEBUFFER_PRE_FORMAT_640X480     UINT32_C(1)
#define TENSOR_ARENA0_PHYS_BASE UINT32_C(0x30000000)
#define TENSOR_ARENA1_PHYS_BASE UINT32_C(0x31000000)
#define AI_PREPROCESS_416X416_BYTES (UINT32_C(416) * UINT32_C(416) * UINT32_C(3))
#define AI_PREPROCESS_640X480_BYTES (UINT32_C(640) * UINT32_C(480) * UINT32_C(3))
/* The active board model is TinyYOLOv2 and consumes the 416 tensor. */
#define TENSOR_MEMBER_BYTES     AI_PREPROCESS_416X416_BYTES
#define TENSOR_MEMBER_STRIDE    TENSOR_MEMBER_BYTES
#define TENSOR_ARENA_BYTES      (AI_PREPROCESS_416X416_BYTES * UINT32_C(16))
#define TENSOR_ARENA_MAX_BYTES  (AI_PREPROCESS_640X480_BYTES * UINT32_C(16))

/* Device-side MIG addresses. Rocket accesses the same storage via bit 31. */
#define AI_MODEL_OUTPUT0_PHYS_BASE UINT32_C(0x32000000)
#define AI_MODEL_OUTPUT_ARENA_BYTES UINT32_C(0x00400000)
#define AI_MODEL_OUTPUT_TENSOR_BYTES UINT32_C(0x00204CC0)
#define AI_DDR_CPU_ALIAS(address) ((uintptr_t)(address) | UINT32_C(0x80000000))

#define GPIO_OUT_TX_ENABLE   (UINT32_C(1) << 0)
#define GPIO_OUT_CLK_RESET_N (UINT32_C(1) << 1)
#define GPIO_IN_RX_PWR_DET (UINT32_C(1) << 0)
#define GPIO_IN_TX_HPD     (UINT32_C(1) << 1)
#define GPIO_IN_CLK_LOL    (UINT32_C(1) << 2)
#define GPIO_IN_CLK_INT    (UINT32_C(1) << 3)
#define GPIO_IN_TX_LOCKED  (UINT32_C(1) << 4)

#define HDMI_CLK_I2C_ADDRESS UINT32_C(0x7C)

#endif
