#ifndef XPARAMETERS_H
#define XPARAMETERS_H

#define XPAR_CPU_CORE_CLOCK_FREQ_HZ 100000000U

#define XPAR_XVPHY_NUM_INSTANCES 1U
#define XPAR_VPHY_0_TRANSCEIVER 6U
#define XPAR_VID_PHY_CONTROLLER_0_TRANSCEIVER 6U

#define XPAR_XV_HDMITXSS_NUM_INSTANCES 1U
#define XPAR_XV_HDMITX_NUM_INSTANCES 1U
#define XPAR_XV_HDMITX_0_DEVICE_ID 0U
#define XPAR_XV_HDMIRXSS_NUM_INSTANCES 1U
#define XPAR_XV_HDMIRX_NUM_INSTANCES 1U
#define XPAR_XV_HDMIRX_0_DEVICE_ID 0U
#define XPAR_XVTC_NUM_INSTANCES 1U

#endif
