// Generated by CIRCT firtool-1.75.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module LoopConvLdWeight(	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:413:7]
  input         clock,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:413:7]
  input         reset,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:413:7]
  output        io_req_ready,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:419:14]
  input         io_req_valid,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:419:14]
  input  [15:0] io_req_bits_outer_bounds_in_channels,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:419:14]
  input  [15:0] io_req_bits_outer_bounds_out_channels,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:419:14]
  input  [15:0] io_req_bits_outer_bounds_weight_stride,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:419:14]
  input  [15:0] io_req_bits_outer_bounds_kernel_dim,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:419:14]
  input  [15:0] io_req_bits_inner_bounds_krows,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:419:14]
  input  [15:0] io_req_bits_inner_bounds_kcols,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:419:14]
  input  [15:0] io_req_bits_inner_bounds_kchs,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:419:14]
  input  [15:0] io_req_bits_derived_params_ochs,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:419:14]
  input  [15:0] io_req_bits_derived_params_out_channels_per_bank,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:419:14]
  input  [15:0] io_req_bits_derived_params_in_channels_per_bank,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:419:14]
  input  [15:0] io_req_bits_derived_params_weight_spad_stride,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:419:14]
  input  [15:0] io_req_bits_addr_end,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:419:14]
  input  [39:0] io_req_bits_dram_addr,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:419:14]
  input         io_req_bits_trans_weight_1203,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:419:14]
  input         io_req_bits_trans_weight_0132,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:419:14]
  input         io_req_bits_dw,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:419:14]
  input         io_req_bits_loop_id,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:419:14]
  input         io_cmd_ready,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:419:14]
  output        io_cmd_valid,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:419:14]
  output [6:0]  io_cmd_bits_inst_funct,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:419:14]
  output [63:0] io_cmd_bits_rs1,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:419:14]
  output [63:0] io_cmd_bits_rs2,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:419:14]
  output        io_idle,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:419:14]
  input         io_rob_overloaded,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:419:14]
  input         io_wait_for_prev_loop,	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:419:14]
  output        io_loop_id	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:419:14]
);

  wire        _command_p_io_in_ready;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:492:25]
  wire        _command_p_io_out_valid;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:492:25]
  wire [6:0]  _command_p_io_out_bits_cmd_inst_funct;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:492:25]
  wire [63:0] _command_p_io_out_bits_cmd_rs1;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:492:25]
  wire [63:0] _command_p_io_out_bits_cmd_rs2;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:492:25]
  wire [67:0] _command_p_io_out_bits_dram_addr;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:492:25]
  wire [63:0] _command_p_io_out_bits_spad_addr;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:492:25]
  wire [15:0] _command_p_io_out_bits_K;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:492:25]
  wire [15:0] _command_p_io_out_bits_J;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:492:25]
  wire        _command_p_io_busy;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:492:25]
  reg  [1:0]  state;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:434:22]
  reg  [15:0] req_outer_bounds_in_channels;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:436:16]
  reg  [15:0] req_outer_bounds_out_channels;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:436:16]
  reg  [15:0] req_outer_bounds_weight_stride;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:436:16]
  reg  [15:0] req_outer_bounds_kernel_dim;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:436:16]
  reg  [15:0] req_inner_bounds_krows;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:436:16]
  reg  [15:0] req_inner_bounds_kcols;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:436:16]
  reg  [15:0] req_inner_bounds_kchs;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:436:16]
  reg  [15:0] req_derived_params_ochs;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:436:16]
  reg  [15:0] req_derived_params_out_channels_per_bank;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:436:16]
  reg  [15:0] req_derived_params_in_channels_per_bank;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:436:16]
  reg  [15:0] req_derived_params_weight_spad_stride;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:436:16]
  reg  [15:0] req_addr_end;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:436:16]
  reg  [39:0] req_dram_addr;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:436:16]
  reg         req_trans_weight_1203;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:436:16]
  reg         req_trans_weight_0132;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:436:16]
  reg         req_dw;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:436:16]
  reg         req_loop_id;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:436:16]
  wire [15:0] max_chs_per_mvin_max_ochs_per_mvin = req_derived_params_ochs < 16'h40 ? req_derived_params_ochs : 16'h40;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:436:16, :443:{32,38}]
  wire [15:0] max_chs_per_mvin_max_kchs_per_mvin = req_inner_bounds_kchs < 16'h40 ? req_inner_bounds_kchs : 16'h40;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:436:16, :443:38, :444:{32,38}]
  wire [15:0] max_chs_per_mvin = req_trans_weight_0132 ? max_chs_per_mvin_max_kchs_per_mvin : max_chs_per_mvin_max_ochs_per_mvin;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:436:16, :443:32, :444:32, :445:8]
  wire [31:0] _GEN = {16'h0, req_inner_bounds_kcols};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:436:16, :448:64]
  wire [47:0] _GEN_0 = {32'h0, req_inner_bounds_krows};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:436:16, :448:72]
  wire [63:0] _GEN_1 = {48'h0, req_derived_params_ochs};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:436:16, :448:80]
  wire [63:0] _GEN_2 = {48'h0, req_inner_bounds_kchs};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:436:16, :449:43]
  wire [63:0] _addr_start_T = {48'h0, req_addr_end} - (req_trans_weight_0132 ? {16'h0, {16'h0, {16'h0, req_derived_params_in_channels_per_bank} * _GEN} * _GEN_0} * _GEN_1 : {16'h0, {16'h0, {16'h0, req_derived_params_out_channels_per_bank} * _GEN} * _GEN_0} * _GEN_2);	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:436:16, :448:{19,64,72,80}, :449:{27,35,43}, :450:33]
  wire [31:0] _GEN_3 = {16'h0, req_outer_bounds_kernel_dim};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:436:16, :454:42]
  reg  [15:0] och;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:459:16]
  reg  [15:0] krow;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:460:17]
  reg  [15:0] kcol;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:461:17]
  reg  [15:0] kch;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:462:16]
  wire [31:0] _GEN_4 = {16'h0, krow};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:460:17, :465:35]
  wire [31:0] _dram_offset_T_19 = _GEN_4 * _GEN_3;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:454:42, :465:35]
  wire [31:0] _GEN_5 = {16'h0, req_outer_bounds_in_channels};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:436:16, :465:46]
  wire [31:0] _GEN_6 = {16'h0, kcol};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:461:17, :465:66]
  wire [31:0] _GEN_7 = {16'h0, kch};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:462:16, :465:79]
  wire [31:0] _GEN_8 = {16'h0, och};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:459:16, :465:103]
  wire [31:0] _GEN_9 = {16'h0, req_outer_bounds_out_channels};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:436:16, :467:87]
  wire [31:0] _GEN_10 = {16'h0, req_inner_bounds_krows};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:436:16, :474:55]
  wire [47:0] _GEN_11 = {32'h0, req_inner_bounds_kcols};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:436:16, :474:63]
  wire [47:0] _GEN_12 = {16'h0, _GEN_4 * _GEN};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:448:64, :465:35, :474:{85,93}]
  wire [15:0] _K_T_9 = req_inner_bounds_kchs - kch;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:436:16, :462:16, :479:14]
  wire [15:0] _K_T_3 = req_derived_params_ochs - och;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:436:16, :459:16, :480:14]
  wire        _io_idle_T = state == 2'h0;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:434:22, :518:25]
  wire        io_req_ready_0 = _io_idle_T & ~_command_p_io_busy;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:492:25, :518:{25,34,37}]
  wire        command_p_io_in_valid = (|state) & ~io_wait_for_prev_loop & (|req_dram_addr);	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:434:22, :436:16, :522:{34,43,46,69,87}]
  wire        _command_p_io_in_bits_cmd_T = state == 2'h1;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:434:22, :504:27, :523:41]
  wire        _GEN_13 = _command_p_io_out_bits_cmd_inst_funct == 7'h1;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:492:25, :513:23, :532:46]
  wire        _GEN_14 = req_dram_addr == 40'h0;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:436:16, :522:87, :544:22]
  wire        _GEN_15 = _command_p_io_in_ready & command_p_io_in_valid;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:492:25, :522:{43,69}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire [16:0] _next_kch_T_3 = {1'h0, kch} + {1'h0, req_trans_weight_0132 ? max_chs_per_mvin_max_kchs_per_mvin : 16'h10};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:436:16, :444:32, :462:16, :479:14, :482:20, :551:23, generators/gemmini/src/main/scala/gemmini/Util.scala:41:15]
  wire [15:0] next_kch = _next_kch_T_3 > {1'h0, req_inner_bounds_kchs - 16'h1} ? 16'h0 : _next_kch_T_3[15:0];	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:436:16, generators/gemmini/src/main/scala/gemmini/Util.scala:39:28, :41:15, :43:17, src/main/scala/chisel3/util/Mux.scala:126:16]
  wire [16:0] _next_kcol_T_4 = {1'h0, kcol} + 17'h1;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:461:17, generators/gemmini/src/main/scala/gemmini/Util.scala:41:15]
  wire [15:0] _next_kcol_T_6 = _next_kcol_T_4 > {1'h0, req_inner_bounds_kcols - 16'h1} ? 16'h0 : _next_kcol_T_4[15:0];	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:436:16, generators/gemmini/src/main/scala/gemmini/Util.scala:39:28, :41:15, :43:17, src/main/scala/chisel3/util/Mux.scala:126:16]
  wire        _state_T_3 = ((|next_kch) ? kcol : _next_kcol_T_6) == 16'h0;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:461:17, :554:59, :555:60, src/main/scala/chisel3/util/Mux.scala:126:16]
  wire        _next_krow_T_2 = _state_T_3 & ~(|next_kch);	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:554:59, :555:{60,68}, src/main/scala/chisel3/util/Mux.scala:126:16]
  wire [16:0] _next_krow_T_6 = {1'h0, krow} + 17'h1;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:460:17, generators/gemmini/src/main/scala/gemmini/Util.scala:41:15]
  wire [15:0] _next_krow_T_8 = _next_krow_T_6 > {1'h0, req_inner_bounds_krows - 16'h1} ? 16'h0 : _next_krow_T_6[15:0];	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:436:16, generators/gemmini/src/main/scala/gemmini/Util.scala:39:28, :41:15, :43:17, src/main/scala/chisel3/util/Mux.scala:126:16]
  wire        _state_T_1 = (_next_krow_T_2 ? _next_krow_T_8 : krow) == 16'h0;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:460:17, :555:68, :556:60, src/main/scala/chisel3/util/Mux.scala:126:16]
  wire        _next_och_T_4 = _state_T_1 & _state_T_3 & ~(|next_kch);	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:554:59, :555:60, :556:{60,68,89}, src/main/scala/chisel3/util/Mux.scala:126:16]
  wire [16:0] _next_och_T_8 = {1'h0, och} + {1'h0, req_trans_weight_0132 ? 16'h10 : max_chs_per_mvin_max_ochs_per_mvin};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:436:16, :443:32, :459:16, :480:14, :482:20, :550:23, generators/gemmini/src/main/scala/gemmini/Util.scala:41:15]
  wire [15:0] _next_och_T_10 = _next_och_T_8 > {1'h0, req_derived_params_ochs - 16'h1} ? 16'h0 : _next_och_T_8[15:0];	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:436:16, generators/gemmini/src/main/scala/gemmini/Util.scala:39:28, :41:15, :43:17, src/main/scala/chisel3/util/Mux.scala:126:16]
  wire        _GEN_16 = io_req_ready_0 & io_req_valid;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:518:34, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  always @(posedge clock) begin	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:413:7]
    if (reset)	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:413:7]
      state <= 2'h0;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:434:22]
    else if (_GEN_16)	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35]
      state <= 2'h1;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:434:22, :504:27]
    else if (_GEN_14)	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:544:22]
      state <= 2'h0;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:434:22]
    else if (_GEN_15)	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35]
      state <= _command_p_io_in_bits_cmd_T ? 2'h2 : {~((_next_och_T_4 ? _next_och_T_10 : och) == 16'h0 & _state_T_1 & _state_T_3 & ~(|next_kch)), 1'h0};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:434:22, :459:16, :523:41, :547:29, :548:13, :554:59, :555:60, :556:{60,68,89}, :563:{13,19,29,37,58,79}, src/main/scala/chisel3/util/Mux.scala:126:16]
    if (_GEN_16) begin	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35]
      req_outer_bounds_in_channels <= io_req_bits_outer_bounds_in_channels;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:436:16]
      req_outer_bounds_out_channels <= io_req_bits_outer_bounds_out_channels;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:436:16]
      req_outer_bounds_weight_stride <= io_req_bits_outer_bounds_weight_stride;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:436:16]
      req_outer_bounds_kernel_dim <= io_req_bits_outer_bounds_kernel_dim;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:436:16]
      req_inner_bounds_krows <= io_req_bits_inner_bounds_krows;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:436:16]
      req_inner_bounds_kcols <= io_req_bits_inner_bounds_kcols;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:436:16]
      req_inner_bounds_kchs <= io_req_bits_inner_bounds_kchs;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:436:16]
      req_derived_params_ochs <= io_req_bits_derived_params_ochs;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:436:16]
      req_derived_params_out_channels_per_bank <= io_req_bits_derived_params_out_channels_per_bank;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:436:16]
      req_derived_params_in_channels_per_bank <= io_req_bits_derived_params_in_channels_per_bank;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:436:16]
      req_derived_params_weight_spad_stride <= io_req_bits_derived_params_weight_spad_stride;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:436:16]
      req_addr_end <= io_req_bits_addr_end;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:436:16]
      req_dram_addr <= io_req_bits_dram_addr;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:436:16]
      req_trans_weight_1203 <= io_req_bits_trans_weight_1203;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:436:16]
      req_trans_weight_0132 <= io_req_bits_trans_weight_0132;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:436:16]
      req_dw <= io_req_bits_dw;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:436:16]
      req_loop_id <= io_req_bits_loop_id;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:436:16]
      och <= 16'h0;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:459:16]
      krow <= 16'h0;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:460:17]
      kcol <= 16'h0;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:461:17]
      kch <= 16'h0;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:462:16]
    end
    else begin	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35]
      if (_GEN_14 | ~_GEN_15 | _command_p_io_in_bits_cmd_T | ~_next_och_T_4) begin	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:459:16, :462:16, :523:41, :544:{22,30}, :546:36, :547:29, :556:{68,89}, :561:11, generators/gemmini/src/main/scala/gemmini/Util.scala:42:8, src/main/scala/chisel3/util/Decoupled.scala:51:35, src/main/scala/chisel3/util/Mux.scala:126:16]
      end
      else	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:459:16, :544:30, :546:36, :547:29, :561:11, src/main/scala/chisel3/util/Mux.scala:126:16]
        och <= _next_och_T_10;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:459:16, src/main/scala/chisel3/util/Mux.scala:126:16]
      if (_GEN_14 | ~_GEN_15 | _command_p_io_in_bits_cmd_T | ~_next_krow_T_2) begin	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:460:17, :462:16, :523:41, :544:{22,30}, :546:36, :547:29, :555:68, :560:12, generators/gemmini/src/main/scala/gemmini/Util.scala:42:8, src/main/scala/chisel3/util/Decoupled.scala:51:35, src/main/scala/chisel3/util/Mux.scala:126:16]
      end
      else	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:460:17, :544:30, :546:36, :547:29, :560:12, src/main/scala/chisel3/util/Mux.scala:126:16]
        krow <= _next_krow_T_8;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:460:17, src/main/scala/chisel3/util/Mux.scala:126:16]
      if (_GEN_14 | ~_GEN_15 | (|{_command_p_io_in_bits_cmd_T, next_kch})) begin	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:461:17, :462:16, :523:41, :544:{22,30}, :546:36, :547:29, :554:59, :559:12, src/main/scala/chisel3/util/Decoupled.scala:51:35, src/main/scala/chisel3/util/Mux.scala:126:16]
      end
      else	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:461:17, :544:30, :546:36, :547:29]
        kcol <= _next_kcol_T_6;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:461:17, src/main/scala/chisel3/util/Mux.scala:126:16]
      if (_GEN_14 | ~_GEN_15 | _command_p_io_in_bits_cmd_T) begin	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:462:16, :523:41, :544:{22,30}, :546:36, :547:29, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      end
      else	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:462:16, :544:30, :546:36, :547:29]
        kch <= next_kch;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:462:16, src/main/scala/chisel3/util/Mux.scala:126:16]
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:413:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:413:7]
      `FIRRTL_BEFORE_INITIAL	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:413:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:27];	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:413:7]
    initial begin	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:413:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:413:7]
        `INIT_RANDOM_PROLOG_	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:413:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:413:7]
        for (logic [4:0] i = 5'h0; i < 5'h1C; i += 5'h1) begin
          _RANDOM[i] = `RANDOM;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:413:7]
        end	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:413:7]
        state = _RANDOM[5'h0][1:0];	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:413:7, :434:22]
        req_outer_bounds_in_channels = {_RANDOM[5'h1][31:18], _RANDOM[5'h2][1:0]};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:413:7, :436:16]
        req_outer_bounds_out_channels = _RANDOM[5'h2][17:2];	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:413:7, :436:16]
        req_outer_bounds_weight_stride = {_RANDOM[5'h4][31:18], _RANDOM[5'h5][1:0]};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:413:7, :436:16]
        req_outer_bounds_kernel_dim = _RANDOM[5'h7][17:2];	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:413:7, :436:16]
        req_inner_bounds_krows = {_RANDOM[5'hB][31:18], _RANDOM[5'hC][1:0]};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:413:7, :436:16]
        req_inner_bounds_kcols = _RANDOM[5'hC][17:2];	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:413:7, :436:16]
        req_inner_bounds_kchs = {_RANDOM[5'hC][31:18], _RANDOM[5'hD][1:0]};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:413:7, :436:16]
        req_derived_params_ochs = _RANDOM[5'h12][17:2];	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:413:7, :436:16]
        req_derived_params_out_channels_per_bank = _RANDOM[5'h15][17:2];	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:413:7, :436:16]
        req_derived_params_in_channels_per_bank = {_RANDOM[5'h15][31:18], _RANDOM[5'h16][1:0]};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:413:7, :436:16]
        req_derived_params_weight_spad_stride = _RANDOM[5'h17][17:2];	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:413:7, :436:16]
        req_addr_end = {_RANDOM[5'h17][31:18], _RANDOM[5'h18][1:0]};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:413:7, :436:16]
        req_dram_addr = {_RANDOM[5'h18][31:2], _RANDOM[5'h19][9:0]};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:413:7, :436:16]
        req_trans_weight_1203 = _RANDOM[5'h19][10];	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:413:7, :436:16]
        req_trans_weight_0132 = _RANDOM[5'h19][11];	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:413:7, :436:16]
        req_dw = _RANDOM[5'h19][12];	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:413:7, :436:16]
        req_loop_id = _RANDOM[5'h19][13];	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:413:7, :436:16]
        och = _RANDOM[5'h19][29:14];	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:413:7, :436:16, :459:16]
        krow = {_RANDOM[5'h19][31:30], _RANDOM[5'h1A][13:0]};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:413:7, :436:16, :460:17]
        kcol = _RANDOM[5'h1A][29:14];	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:413:7, :460:17, :461:17]
        kch = {_RANDOM[5'h1A][31:30], _RANDOM[5'h1B][13:0]};	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:413:7, :460:17, :462:16]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:413:7]
      `FIRRTL_AFTER_INITIAL	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:413:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  Pipeline_4 command_p (	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:492:25]
    .clock                      (clock),
    .reset                      (reset),
    .io_in_ready                (_command_p_io_in_ready),
    .io_in_valid                (command_p_io_in_valid),	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:522:{43,69}]
    .io_in_bits_cmd_inst_funct  ({6'h0, ~_command_p_io_in_bits_cmd_T}),	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:523:{34,41}]
    .io_in_bits_cmd_rs1         (_command_p_io_in_bits_cmd_T ? {33'h7F000000, req_derived_params_weight_spad_stride[14:0], 16'h109} : 64'h0),	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:436:16, :502:25, :507:36, :514:16, :523:{34,41}]
    .io_in_bits_cmd_rs2         (_command_p_io_in_bits_cmd_T ? {16'h0, req_dw ? 48'h1 : req_trans_weight_1203 ? {16'h0, _GEN_3 * _GEN_3} * {32'h0, req_outer_bounds_out_channels} : {32'h0, req_trans_weight_0132 ? req_outer_bounds_in_channels : req_outer_bounds_weight_stride}} : 64'h0),	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:436:16, :454:{42,55}, :509:18, :514:16, :523:{34,41}, src/main/scala/chisel3/util/Mux.scala:126:16]
    .io_in_bits_dram_addr       ({27'h0, {9'h0, req_dw ? _dram_offset_T_19 + _GEN_6 : req_trans_weight_1203 ? (_GEN_7 * _GEN_3 * _GEN_3 + _dram_offset_T_19 + _GEN_6) * _GEN_9 + _GEN_8 : req_trans_weight_0132 ? (_dram_offset_T_19 * _GEN_9 + _GEN_6 * _GEN_9 + _GEN_8) * _GEN_5 + _GEN_7 : (_dram_offset_T_19 * _GEN_5 + _GEN_6 * _GEN_5 + _GEN_7) * {16'h0, req_outer_bounds_weight_stride} + _GEN_8} + {1'h0, req_dram_addr}}),	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:436:16, :454:42, :465:{35,46,59,66,79,87,103}, :466:34, :467:{36,47,59,78,87,102}, :468:{48,62,69,83,91,105}, :470:33, :1588:17, src/main/scala/chisel3/util/Mux.scala:126:16]
    .io_in_bits_spad_addr       (req_trans_weight_0132 ? _addr_start_T + {16'h0, {16'h0, {16'h0, kch / 16'h10} * _GEN_10} * _GEN_11} * _GEN_1 + {16'h0, _GEN_12 * {32'h0, req_derived_params_ochs}} + {32'h0, _GEN_6 * {16'h0, req_derived_params_ochs}} + {48'h0, och} : _addr_start_T + {16'h0, {16'h0, {16'h0, och / 16'h10} * _GEN_10} * _GEN_11} * _GEN_2 + {16'h0, _GEN_12 * {32'h0, req_inner_bounds_kchs}} + {32'h0, _GEN_6 * {16'h0, req_inner_bounds_kchs}} + {48'h0, kch}),	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:436:16, :448:80, :449:43, :450:33, :459:16, :462:16, :465:66, :472:22, :474:{16,23,55,63,71,78,93,100,107,114}, :475:{16,23,55,63,71,78,93,100,107,114}, :482:20]
    .io_in_bits_K               (req_trans_weight_0132 ? (_K_T_3 > 16'h10 ? 16'h10 : _K_T_3) : _K_T_9 > 16'h10 ? 16'h10 : _K_T_9),	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:436:16, :479:14, :480:14, :481:14, :482:{8,20}, :483:{8,20}]
    .io_in_bits_J               (req_trans_weight_0132 ? (_K_T_9 > max_chs_per_mvin ? max_chs_per_mvin_max_kchs_per_mvin : _K_T_9) : _K_T_3 > max_chs_per_mvin ? max_chs_per_mvin_max_ochs_per_mvin : _K_T_3),	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:436:16, :443:32, :444:32, :445:8, :478:14, :479:{8,14,20}, :480:{8,14,20}]
    .io_out_ready               (io_cmd_ready & ~io_rob_overloaded),	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:529:{42,45}]
    .io_out_valid               (_command_p_io_out_valid),
    .io_out_bits_cmd_inst_funct (_command_p_io_out_bits_cmd_inst_funct),
    .io_out_bits_cmd_rs1        (_command_p_io_out_bits_cmd_rs1),
    .io_out_bits_cmd_rs2        (_command_p_io_out_bits_cmd_rs2),
    .io_out_bits_dram_addr      (_command_p_io_out_bits_dram_addr),
    .io_out_bits_spad_addr      (_command_p_io_out_bits_spad_addr),
    .io_out_bits_K              (_command_p_io_out_bits_K),
    .io_out_bits_J              (_command_p_io_out_bits_J),
    .io_busy                    (_command_p_io_busy)
  );	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:492:25]
  assign io_req_ready = io_req_ready_0;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:413:7, :518:34]
  assign io_cmd_valid = _command_p_io_out_valid & ~io_rob_overloaded;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:413:7, :492:25, :529:45, :530:42]
  assign io_cmd_bits_inst_funct = _command_p_io_out_bits_cmd_inst_funct;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:413:7, :492:25]
  assign io_cmd_bits_rs1 = _GEN_13 ? _command_p_io_out_bits_dram_addr[63:0] : _command_p_io_out_bits_cmd_rs1;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:413:7, :492:25, :531:15, :532:{46,61}, :534:21]
  assign io_cmd_bits_rs2 = _GEN_13 ? {11'h0, _command_p_io_out_bits_K[4:0], 9'h0, _command_p_io_out_bits_J[6:0], 3'h0, _command_p_io_out_bits_spad_addr[28:26], 10'h0, _command_p_io_out_bits_spad_addr[15:0]} : _command_p_io_out_bits_cmd_rs2;	// @[generators/gemmini/src/main/scala/gemmini/LocalAddr.scala:108:37, :109:57, generators/gemmini/src/main/scala/gemmini/LoopConv.scala:413:7, :492:25, :531:15, :532:{46,61}, :537:27, :538:27, :540:{21,37}]
  assign io_idle = _io_idle_T & ~_command_p_io_busy;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:413:7, :492:25, :518:{25,37}, :519:29]
  assign io_loop_id = req_loop_id;	// @[generators/gemmini/src/main/scala/gemmini/LoopConv.scala:413:7, :436:16]
endmodule

