// Generated by CIRCT firtool-1.75.0

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module MultiHeadedQueue_1(	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7]
  input         clock,	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7]
  input         reset,	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7]
  output        io_enq_ready,	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:8:14]
  input         io_enq_valid,	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:8:14]
  input  [6:0]  io_enq_bits_cmd_inst_funct,	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:8:14]
  input  [63:0] io_enq_bits_cmd_rs1,	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:8:14]
  input  [63:0] io_enq_bits_cmd_rs2,	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:8:14]
  input         io_enq_bits_rob_id_valid,	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:8:14]
  input  [6:0]  io_enq_bits_rob_id_bits,	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:8:14]
  output        io_deq_valid_0,	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:8:14]
  output        io_deq_valid_1,	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:8:14]
  output        io_deq_valid_2,	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:8:14]
  output [6:0]  io_deq_bits_0_cmd_inst_funct,	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:8:14]
  output [63:0] io_deq_bits_0_cmd_rs1,	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:8:14]
  output [63:0] io_deq_bits_0_cmd_rs2,	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:8:14]
  output        io_deq_bits_0_rob_id_valid,	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:8:14]
  output [6:0]  io_deq_bits_0_rob_id_bits,	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:8:14]
  output [6:0]  io_deq_bits_1_cmd_inst_funct,	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:8:14]
  output [63:0] io_deq_bits_1_cmd_rs1,	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:8:14]
  output [63:0] io_deq_bits_1_cmd_rs2,	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:8:14]
  output        io_deq_bits_1_rob_id_valid,	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:8:14]
  output [6:0]  io_deq_bits_1_rob_id_bits,	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:8:14]
  output [63:0] io_deq_bits_2_cmd_rs1,	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:8:14]
  output [63:0] io_deq_bits_2_cmd_rs2,	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:8:14]
  output [6:0]  io_deq_bits_2_rob_id_bits,	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:8:14]
  input  [1:0]  io_deq_pop	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:8:14]
);

  reg  [6:0]        regs_0_cmd_inst_funct;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
  reg  [63:0]       regs_0_cmd_rs1;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
  reg  [63:0]       regs_0_cmd_rs2;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
  reg               regs_0_rob_id_valid;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
  reg  [6:0]        regs_0_rob_id_bits;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
  reg  [6:0]        regs_1_cmd_inst_funct;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
  reg  [63:0]       regs_1_cmd_rs1;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
  reg  [63:0]       regs_1_cmd_rs2;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
  reg               regs_1_rob_id_valid;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
  reg  [6:0]        regs_1_rob_id_bits;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
  reg  [6:0]        regs_2_cmd_inst_funct;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
  reg  [63:0]       regs_2_cmd_rs1;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
  reg  [63:0]       regs_2_cmd_rs2;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
  reg               regs_2_rob_id_valid;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
  reg  [6:0]        regs_2_rob_id_bits;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
  reg  [6:0]        regs_3_cmd_inst_funct;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
  reg  [63:0]       regs_3_cmd_rs1;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
  reg  [63:0]       regs_3_cmd_rs2;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
  reg               regs_3_rob_id_valid;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
  reg  [6:0]        regs_3_rob_id_bits;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
  reg  [6:0]        regs_4_cmd_inst_funct;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
  reg  [63:0]       regs_4_cmd_rs1;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
  reg  [63:0]       regs_4_cmd_rs2;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
  reg               regs_4_rob_id_valid;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
  reg  [6:0]        regs_4_rob_id_bits;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
  reg  [6:0]        regs_5_cmd_inst_funct;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
  reg  [63:0]       regs_5_cmd_rs1;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
  reg  [63:0]       regs_5_cmd_rs2;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
  reg               regs_5_rob_id_valid;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
  reg  [6:0]        regs_5_rob_id_bits;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
  reg  [6:0]        regs_6_cmd_inst_funct;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
  reg  [63:0]       regs_6_cmd_rs1;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
  reg  [63:0]       regs_6_cmd_rs2;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
  reg               regs_6_rob_id_valid;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
  reg  [6:0]        regs_6_rob_id_bits;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
  reg  [6:0]        regs_7_cmd_inst_funct;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
  reg  [63:0]       regs_7_cmd_rs1;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
  reg  [63:0]       regs_7_cmd_rs2;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
  reg               regs_7_rob_id_valid;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
  reg  [6:0]        regs_7_rob_id_bits;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
  reg  [6:0]        regs_8_cmd_inst_funct;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
  reg  [63:0]       regs_8_cmd_rs1;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
  reg  [63:0]       regs_8_cmd_rs2;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
  reg               regs_8_rob_id_valid;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
  reg  [6:0]        regs_8_rob_id_bits;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
  reg  [6:0]        regs_9_cmd_inst_funct;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
  reg  [63:0]       regs_9_cmd_rs1;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
  reg  [63:0]       regs_9_cmd_rs2;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
  reg               regs_9_rob_id_valid;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
  reg  [6:0]        regs_9_rob_id_bits;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
  reg  [6:0]        regs_10_cmd_inst_funct;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
  reg  [63:0]       regs_10_cmd_rs1;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
  reg  [63:0]       regs_10_cmd_rs2;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
  reg               regs_10_rob_id_valid;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
  reg  [6:0]        regs_10_rob_id_bits;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
  reg  [6:0]        regs_11_cmd_inst_funct;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
  reg  [63:0]       regs_11_cmd_rs1;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
  reg  [63:0]       regs_11_cmd_rs2;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
  reg               regs_11_rob_id_valid;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
  reg  [6:0]        regs_11_rob_id_bits;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
  reg  [6:0]        regs_12_cmd_inst_funct;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
  reg  [63:0]       regs_12_cmd_rs1;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
  reg  [63:0]       regs_12_cmd_rs2;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
  reg               regs_12_rob_id_valid;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
  reg  [6:0]        regs_12_rob_id_bits;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
  reg  [6:0]        regs_13_cmd_inst_funct;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
  reg  [63:0]       regs_13_cmd_rs1;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
  reg  [63:0]       regs_13_cmd_rs2;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
  reg               regs_13_rob_id_valid;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
  reg  [6:0]        regs_13_rob_id_bits;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
  reg  [6:0]        regs_14_cmd_inst_funct;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
  reg  [63:0]       regs_14_cmd_rs1;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
  reg  [63:0]       regs_14_cmd_rs2;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
  reg               regs_14_rob_id_valid;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
  reg  [6:0]        regs_14_rob_id_bits;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
  reg  [6:0]        regs_15_cmd_inst_funct;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
  reg  [63:0]       regs_15_cmd_rs1;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
  reg  [63:0]       regs_15_cmd_rs2;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
  reg               regs_15_rob_id_valid;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
  reg  [6:0]        regs_15_rob_id_bits;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
  reg  [3:0]        raddr;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:23:22]
  reg  [3:0]        waddr;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:24:22]
  reg  [4:0]        len;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:25:20]
  wire [3:0]        _raddr_T_11 = 4'hF - raddr;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:23:22, generators/gemmini/src/main/scala/gemmini/Util.scala:13:57]
  wire [15:0][6:0]  _GEN = {{regs_15_cmd_inst_funct}, {regs_14_cmd_inst_funct}, {regs_13_cmd_inst_funct}, {regs_12_cmd_inst_funct}, {regs_11_cmd_inst_funct}, {regs_10_cmd_inst_funct}, {regs_9_cmd_inst_funct}, {regs_8_cmd_inst_funct}, {regs_7_cmd_inst_funct}, {regs_6_cmd_inst_funct}, {regs_5_cmd_inst_funct}, {regs_4_cmd_inst_funct}, {regs_3_cmd_inst_funct}, {regs_2_cmd_inst_funct}, {regs_1_cmd_inst_funct}, {regs_0_cmd_inst_funct}};	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17, :32:20]
  wire [15:0][63:0] _GEN_0 = {{regs_15_cmd_rs1}, {regs_14_cmd_rs1}, {regs_13_cmd_rs1}, {regs_12_cmd_rs1}, {regs_11_cmd_rs1}, {regs_10_cmd_rs1}, {regs_9_cmd_rs1}, {regs_8_cmd_rs1}, {regs_7_cmd_rs1}, {regs_6_cmd_rs1}, {regs_5_cmd_rs1}, {regs_4_cmd_rs1}, {regs_3_cmd_rs1}, {regs_2_cmd_rs1}, {regs_1_cmd_rs1}, {regs_0_cmd_rs1}};	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17, :32:20]
  wire [15:0][63:0] _GEN_1 = {{regs_15_cmd_rs2}, {regs_14_cmd_rs2}, {regs_13_cmd_rs2}, {regs_12_cmd_rs2}, {regs_11_cmd_rs2}, {regs_10_cmd_rs2}, {regs_9_cmd_rs2}, {regs_8_cmd_rs2}, {regs_7_cmd_rs2}, {regs_6_cmd_rs2}, {regs_5_cmd_rs2}, {regs_4_cmd_rs2}, {regs_3_cmd_rs2}, {regs_2_cmd_rs2}, {regs_1_cmd_rs2}, {regs_0_cmd_rs2}};	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17, :32:20]
  wire [15:0]       _GEN_2 = {{regs_15_rob_id_valid}, {regs_14_rob_id_valid}, {regs_13_rob_id_valid}, {regs_12_rob_id_valid}, {regs_11_rob_id_valid}, {regs_10_rob_id_valid}, {regs_9_rob_id_valid}, {regs_8_rob_id_valid}, {regs_7_rob_id_valid}, {regs_6_rob_id_valid}, {regs_5_rob_id_valid}, {regs_4_rob_id_valid}, {regs_3_rob_id_valid}, {regs_2_rob_id_valid}, {regs_1_rob_id_valid}, {regs_0_rob_id_valid}};	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17, :32:20]
  wire [15:0][6:0]  _GEN_3 = {{regs_15_rob_id_bits}, {regs_14_rob_id_bits}, {regs_13_rob_id_bits}, {regs_12_rob_id_bits}, {regs_11_rob_id_bits}, {regs_10_rob_id_bits}, {regs_9_rob_id_bits}, {regs_8_rob_id_bits}, {regs_7_rob_id_bits}, {regs_6_rob_id_bits}, {regs_5_rob_id_bits}, {regs_4_rob_id_bits}, {regs_3_rob_id_bits}, {regs_2_rob_id_bits}, {regs_1_rob_id_bits}, {regs_0_rob_id_bits}};	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17, :32:20]
  wire [3:0]        _io_deq_bits_1_T_19 = (&raddr) ? 4'h1 - _raddr_T_11 - 4'h1 : raddr + 4'h1;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:23:22, generators/gemmini/src/main/scala/gemmini/Util.scala:13:{10,13,48,57,62,71}]
  wire [3:0]        _io_deq_bits_2_T_19 = raddr > 4'hD ? 4'h2 - _raddr_T_11 - 4'h1 : raddr + 4'h2;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:23:22, generators/gemmini/src/main/scala/gemmini/Util.scala:13:{10,13,48,57,62,71}]
  wire [4:0]        _GEN_4 = {3'h0, io_deq_pop};	// @[generators/gemmini/src/main/scala/gemmini/Util.scala:13:22]
  `ifndef SYNTHESIS	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:48:9]
    always @(posedge clock) begin	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:48:9]
      if (~reset & ~(_GEN_4 <= len & io_deq_pop != 2'h3)) begin	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:25:20, :48:{9,21,53,67}, generators/gemmini/src/main/scala/gemmini/Util.scala:13:22]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:48:9]
          $error("Assertion failed\n    at MultiHeadedQueue.scala:48 assert(io.deq.pop <= len && io.deq.pop <= heads.U && io.deq.pop <= maxpop.U)\n");	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:48:9]
        if (`STOP_COND_)	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:48:9]
          $fatal;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:48:9]
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
  wire [3:0]        _GEN_5 = {2'h0, io_deq_pop};	// @[generators/gemmini/src/main/scala/gemmini/Util.scala:13:22]
  wire              _len_T_4 = ~(len[4]) & io_enq_valid;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:25:20, :27:23, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  always @(posedge clock) begin	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7]
    if (_len_T_4 & waddr == 4'h0) begin	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17, :24:22, :36:22, :37:17, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      regs_0_cmd_inst_funct <= io_enq_bits_cmd_inst_funct;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
      regs_0_cmd_rs1 <= io_enq_bits_cmd_rs1;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
      regs_0_cmd_rs2 <= io_enq_bits_cmd_rs2;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
      regs_0_rob_id_valid <= io_enq_bits_rob_id_valid;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
      regs_0_rob_id_bits <= io_enq_bits_rob_id_bits;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
    end
    if (_len_T_4 & waddr == 4'h1) begin	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17, :24:22, :36:22, :37:17, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      regs_1_cmd_inst_funct <= io_enq_bits_cmd_inst_funct;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
      regs_1_cmd_rs1 <= io_enq_bits_cmd_rs1;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
      regs_1_cmd_rs2 <= io_enq_bits_cmd_rs2;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
      regs_1_rob_id_valid <= io_enq_bits_rob_id_valid;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
      regs_1_rob_id_bits <= io_enq_bits_rob_id_bits;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
    end
    if (_len_T_4 & waddr == 4'h2) begin	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17, :24:22, :36:22, :37:17, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      regs_2_cmd_inst_funct <= io_enq_bits_cmd_inst_funct;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
      regs_2_cmd_rs1 <= io_enq_bits_cmd_rs1;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
      regs_2_cmd_rs2 <= io_enq_bits_cmd_rs2;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
      regs_2_rob_id_valid <= io_enq_bits_rob_id_valid;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
      regs_2_rob_id_bits <= io_enq_bits_rob_id_bits;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
    end
    if (_len_T_4 & waddr == 4'h3) begin	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17, :24:22, :36:22, :37:17, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      regs_3_cmd_inst_funct <= io_enq_bits_cmd_inst_funct;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
      regs_3_cmd_rs1 <= io_enq_bits_cmd_rs1;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
      regs_3_cmd_rs2 <= io_enq_bits_cmd_rs2;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
      regs_3_rob_id_valid <= io_enq_bits_rob_id_valid;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
      regs_3_rob_id_bits <= io_enq_bits_rob_id_bits;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
    end
    if (_len_T_4 & waddr == 4'h4) begin	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17, :24:22, :36:22, :37:17, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      regs_4_cmd_inst_funct <= io_enq_bits_cmd_inst_funct;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
      regs_4_cmd_rs1 <= io_enq_bits_cmd_rs1;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
      regs_4_cmd_rs2 <= io_enq_bits_cmd_rs2;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
      regs_4_rob_id_valid <= io_enq_bits_rob_id_valid;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
      regs_4_rob_id_bits <= io_enq_bits_rob_id_bits;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
    end
    if (_len_T_4 & waddr == 4'h5) begin	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17, :24:22, :36:22, :37:17, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      regs_5_cmd_inst_funct <= io_enq_bits_cmd_inst_funct;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
      regs_5_cmd_rs1 <= io_enq_bits_cmd_rs1;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
      regs_5_cmd_rs2 <= io_enq_bits_cmd_rs2;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
      regs_5_rob_id_valid <= io_enq_bits_rob_id_valid;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
      regs_5_rob_id_bits <= io_enq_bits_rob_id_bits;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
    end
    if (_len_T_4 & waddr == 4'h6) begin	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17, :24:22, :36:22, :37:17, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      regs_6_cmd_inst_funct <= io_enq_bits_cmd_inst_funct;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
      regs_6_cmd_rs1 <= io_enq_bits_cmd_rs1;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
      regs_6_cmd_rs2 <= io_enq_bits_cmd_rs2;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
      regs_6_rob_id_valid <= io_enq_bits_rob_id_valid;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
      regs_6_rob_id_bits <= io_enq_bits_rob_id_bits;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
    end
    if (_len_T_4 & waddr == 4'h7) begin	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17, :24:22, :36:22, :37:17, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      regs_7_cmd_inst_funct <= io_enq_bits_cmd_inst_funct;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
      regs_7_cmd_rs1 <= io_enq_bits_cmd_rs1;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
      regs_7_cmd_rs2 <= io_enq_bits_cmd_rs2;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
      regs_7_rob_id_valid <= io_enq_bits_rob_id_valid;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
      regs_7_rob_id_bits <= io_enq_bits_rob_id_bits;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
    end
    if (_len_T_4 & waddr == 4'h8) begin	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17, :24:22, :36:22, :37:17, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      regs_8_cmd_inst_funct <= io_enq_bits_cmd_inst_funct;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
      regs_8_cmd_rs1 <= io_enq_bits_cmd_rs1;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
      regs_8_cmd_rs2 <= io_enq_bits_cmd_rs2;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
      regs_8_rob_id_valid <= io_enq_bits_rob_id_valid;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
      regs_8_rob_id_bits <= io_enq_bits_rob_id_bits;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
    end
    if (_len_T_4 & waddr == 4'h9) begin	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17, :24:22, :36:22, :37:17, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      regs_9_cmd_inst_funct <= io_enq_bits_cmd_inst_funct;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
      regs_9_cmd_rs1 <= io_enq_bits_cmd_rs1;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
      regs_9_cmd_rs2 <= io_enq_bits_cmd_rs2;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
      regs_9_rob_id_valid <= io_enq_bits_rob_id_valid;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
      regs_9_rob_id_bits <= io_enq_bits_rob_id_bits;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
    end
    if (_len_T_4 & waddr == 4'hA) begin	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17, :24:22, :36:22, :37:17, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      regs_10_cmd_inst_funct <= io_enq_bits_cmd_inst_funct;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
      regs_10_cmd_rs1 <= io_enq_bits_cmd_rs1;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
      regs_10_cmd_rs2 <= io_enq_bits_cmd_rs2;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
      regs_10_rob_id_valid <= io_enq_bits_rob_id_valid;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
      regs_10_rob_id_bits <= io_enq_bits_rob_id_bits;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
    end
    if (_len_T_4 & waddr == 4'hB) begin	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17, :24:22, :36:22, :37:17, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      regs_11_cmd_inst_funct <= io_enq_bits_cmd_inst_funct;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
      regs_11_cmd_rs1 <= io_enq_bits_cmd_rs1;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
      regs_11_cmd_rs2 <= io_enq_bits_cmd_rs2;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
      regs_11_rob_id_valid <= io_enq_bits_rob_id_valid;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
      regs_11_rob_id_bits <= io_enq_bits_rob_id_bits;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
    end
    if (_len_T_4 & waddr == 4'hC) begin	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17, :24:22, :36:22, :37:17, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      regs_12_cmd_inst_funct <= io_enq_bits_cmd_inst_funct;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
      regs_12_cmd_rs1 <= io_enq_bits_cmd_rs1;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
      regs_12_cmd_rs2 <= io_enq_bits_cmd_rs2;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
      regs_12_rob_id_valid <= io_enq_bits_rob_id_valid;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
      regs_12_rob_id_bits <= io_enq_bits_rob_id_bits;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
    end
    if (_len_T_4 & waddr == 4'hD) begin	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17, :24:22, :36:22, :37:17, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      regs_13_cmd_inst_funct <= io_enq_bits_cmd_inst_funct;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
      regs_13_cmd_rs1 <= io_enq_bits_cmd_rs1;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
      regs_13_cmd_rs2 <= io_enq_bits_cmd_rs2;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
      regs_13_rob_id_valid <= io_enq_bits_rob_id_valid;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
      regs_13_rob_id_bits <= io_enq_bits_rob_id_bits;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
    end
    if (_len_T_4 & waddr == 4'hE) begin	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17, :24:22, :36:22, :37:17, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      regs_14_cmd_inst_funct <= io_enq_bits_cmd_inst_funct;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
      regs_14_cmd_rs1 <= io_enq_bits_cmd_rs1;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
      regs_14_cmd_rs2 <= io_enq_bits_cmd_rs2;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
      regs_14_rob_id_valid <= io_enq_bits_rob_id_valid;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
      regs_14_rob_id_bits <= io_enq_bits_rob_id_bits;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
    end
    if (_len_T_4 & (&waddr)) begin	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17, :24:22, :36:22, :37:17, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      regs_15_cmd_inst_funct <= io_enq_bits_cmd_inst_funct;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
      regs_15_cmd_rs1 <= io_enq_bits_cmd_rs1;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
      regs_15_cmd_rs2 <= io_enq_bits_cmd_rs2;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
      regs_15_rob_id_valid <= io_enq_bits_rob_id_valid;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
      regs_15_rob_id_bits <= io_enq_bits_rob_id_bits;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:22:17]
    end
    if (reset) begin	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7]
      raddr <= 4'h0;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:23:22]
      waddr <= 4'h0;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:24:22]
      len <= 5'h0;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:25:20]
    end
    else begin	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7]
      if (|io_deq_pop) begin	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:43:19]
        raddr <= raddr >= 4'hF - _GEN_5 + 4'h1 & (|io_deq_pop) ? _GEN_5 - _raddr_T_11 - 4'h1 : raddr + _GEN_5;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:23:22, generators/gemmini/src/main/scala/gemmini/Util.scala:13:{10,13,22,26,32,37,48,57,62,71}]
        len <= len - _GEN_4 + {4'h0, _len_T_4};	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:25:20, :45:{16,29}, generators/gemmini/src/main/scala/gemmini/Util.scala:13:22, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      end
      else if (_len_T_4)	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35]
        len <= len + 5'h1;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:25:20, :39:16]
      if (_len_T_4)	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35]
        waddr <= (&waddr) ? 4'h1 - (4'hF - waddr) - 4'h1 : waddr + 4'h1;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:24:22, generators/gemmini/src/main/scala/gemmini/Util.scala:13:{10,13,48,57,62,71}]
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7]
      `FIRRTL_BEFORE_INITIAL	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:137];	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7]
    initial begin	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7]
        `INIT_RANDOM_PROLOG_	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7]
        for (logic [7:0] i = 8'h0; i < 8'h8A; i += 8'h1) begin
          _RANDOM[i] = `RANDOM;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7]
        end	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7]
        regs_0_cmd_inst_funct = _RANDOM[8'h0][6:0];	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :22:17]
        regs_0_cmd_rs1 = {_RANDOM[8'h1], _RANDOM[8'h2]};	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :22:17]
        regs_0_cmd_rs2 = {_RANDOM[8'h3], _RANDOM[8'h4]};	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :22:17]
        regs_0_rob_id_valid = _RANDOM[8'h8][9];	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :22:17]
        regs_0_rob_id_bits = _RANDOM[8'h8][16:10];	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :22:17]
        regs_1_cmd_inst_funct = _RANDOM[8'h8][25:19];	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :22:17]
        regs_1_cmd_rs1 = {_RANDOM[8'h9][31:19], _RANDOM[8'hA], _RANDOM[8'hB][18:0]};	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :22:17]
        regs_1_cmd_rs2 = {_RANDOM[8'hB][31:19], _RANDOM[8'hC], _RANDOM[8'hD][18:0]};	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :22:17]
        regs_1_rob_id_valid = _RANDOM[8'h10][28];	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :22:17]
        regs_1_rob_id_bits = {_RANDOM[8'h10][31:29], _RANDOM[8'h11][3:0]};	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :22:17]
        regs_2_cmd_inst_funct = _RANDOM[8'h11][12:6];	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :22:17]
        regs_2_cmd_rs1 = {_RANDOM[8'h12][31:6], _RANDOM[8'h13], _RANDOM[8'h14][5:0]};	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :22:17]
        regs_2_cmd_rs2 = {_RANDOM[8'h14][31:6], _RANDOM[8'h15], _RANDOM[8'h16][5:0]};	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :22:17]
        regs_2_rob_id_valid = _RANDOM[8'h19][15];	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :22:17]
        regs_2_rob_id_bits = _RANDOM[8'h19][22:16];	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :22:17]
        regs_3_cmd_inst_funct = _RANDOM[8'h19][31:25];	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :22:17]
        regs_3_cmd_rs1 = {_RANDOM[8'h1A][31:25], _RANDOM[8'h1B], _RANDOM[8'h1C][24:0]};	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :22:17]
        regs_3_cmd_rs2 = {_RANDOM[8'h1C][31:25], _RANDOM[8'h1D], _RANDOM[8'h1E][24:0]};	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :22:17]
        regs_3_rob_id_valid = _RANDOM[8'h22][2];	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :22:17]
        regs_3_rob_id_bits = _RANDOM[8'h22][9:3];	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :22:17]
        regs_4_cmd_inst_funct = _RANDOM[8'h22][18:12];	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :22:17]
        regs_4_cmd_rs1 = {_RANDOM[8'h23][31:12], _RANDOM[8'h24], _RANDOM[8'h25][11:0]};	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :22:17]
        regs_4_cmd_rs2 = {_RANDOM[8'h25][31:12], _RANDOM[8'h26], _RANDOM[8'h27][11:0]};	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :22:17]
        regs_4_rob_id_valid = _RANDOM[8'h2A][21];	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :22:17]
        regs_4_rob_id_bits = _RANDOM[8'h2A][28:22];	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :22:17]
        regs_5_cmd_inst_funct = {_RANDOM[8'h2A][31], _RANDOM[8'h2B][5:0]};	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :22:17]
        regs_5_cmd_rs1 = {_RANDOM[8'h2B][31], _RANDOM[8'h2C], _RANDOM[8'h2D][30:0]};	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :22:17]
        regs_5_cmd_rs2 = {_RANDOM[8'h2D][31], _RANDOM[8'h2E], _RANDOM[8'h2F][30:0]};	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :22:17]
        regs_5_rob_id_valid = _RANDOM[8'h33][8];	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :22:17]
        regs_5_rob_id_bits = _RANDOM[8'h33][15:9];	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :22:17]
        regs_6_cmd_inst_funct = _RANDOM[8'h33][24:18];	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :22:17]
        regs_6_cmd_rs1 = {_RANDOM[8'h34][31:18], _RANDOM[8'h35], _RANDOM[8'h36][17:0]};	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :22:17]
        regs_6_cmd_rs2 = {_RANDOM[8'h36][31:18], _RANDOM[8'h37], _RANDOM[8'h38][17:0]};	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :22:17]
        regs_6_rob_id_valid = _RANDOM[8'h3B][27];	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :22:17]
        regs_6_rob_id_bits = {_RANDOM[8'h3B][31:28], _RANDOM[8'h3C][2:0]};	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :22:17]
        regs_7_cmd_inst_funct = _RANDOM[8'h3C][11:5];	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :22:17]
        regs_7_cmd_rs1 = {_RANDOM[8'h3D][31:5], _RANDOM[8'h3E], _RANDOM[8'h3F][4:0]};	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :22:17]
        regs_7_cmd_rs2 = {_RANDOM[8'h3F][31:5], _RANDOM[8'h40], _RANDOM[8'h41][4:0]};	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :22:17]
        regs_7_rob_id_valid = _RANDOM[8'h44][14];	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :22:17]
        regs_7_rob_id_bits = _RANDOM[8'h44][21:15];	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :22:17]
        regs_8_cmd_inst_funct = _RANDOM[8'h44][30:24];	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :22:17]
        regs_8_cmd_rs1 = {_RANDOM[8'h45][31:24], _RANDOM[8'h46], _RANDOM[8'h47][23:0]};	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :22:17]
        regs_8_cmd_rs2 = {_RANDOM[8'h47][31:24], _RANDOM[8'h48], _RANDOM[8'h49][23:0]};	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :22:17]
        regs_8_rob_id_valid = _RANDOM[8'h4D][1];	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :22:17]
        regs_8_rob_id_bits = _RANDOM[8'h4D][8:2];	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :22:17]
        regs_9_cmd_inst_funct = _RANDOM[8'h4D][17:11];	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :22:17]
        regs_9_cmd_rs1 = {_RANDOM[8'h4E][31:11], _RANDOM[8'h4F], _RANDOM[8'h50][10:0]};	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :22:17]
        regs_9_cmd_rs2 = {_RANDOM[8'h50][31:11], _RANDOM[8'h51], _RANDOM[8'h52][10:0]};	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :22:17]
        regs_9_rob_id_valid = _RANDOM[8'h55][20];	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :22:17]
        regs_9_rob_id_bits = _RANDOM[8'h55][27:21];	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :22:17]
        regs_10_cmd_inst_funct = {_RANDOM[8'h55][31:30], _RANDOM[8'h56][4:0]};	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :22:17]
        regs_10_cmd_rs1 = {_RANDOM[8'h56][31:30], _RANDOM[8'h57], _RANDOM[8'h58][29:0]};	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :22:17]
        regs_10_cmd_rs2 = {_RANDOM[8'h58][31:30], _RANDOM[8'h59], _RANDOM[8'h5A][29:0]};	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :22:17]
        regs_10_rob_id_valid = _RANDOM[8'h5E][7];	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :22:17]
        regs_10_rob_id_bits = _RANDOM[8'h5E][14:8];	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :22:17]
        regs_11_cmd_inst_funct = _RANDOM[8'h5E][23:17];	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :22:17]
        regs_11_cmd_rs1 = {_RANDOM[8'h5F][31:17], _RANDOM[8'h60], _RANDOM[8'h61][16:0]};	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :22:17]
        regs_11_cmd_rs2 = {_RANDOM[8'h61][31:17], _RANDOM[8'h62], _RANDOM[8'h63][16:0]};	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :22:17]
        regs_11_rob_id_valid = _RANDOM[8'h66][26];	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :22:17]
        regs_11_rob_id_bits = {_RANDOM[8'h66][31:27], _RANDOM[8'h67][1:0]};	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :22:17]
        regs_12_cmd_inst_funct = _RANDOM[8'h67][10:4];	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :22:17]
        regs_12_cmd_rs1 = {_RANDOM[8'h68][31:4], _RANDOM[8'h69], _RANDOM[8'h6A][3:0]};	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :22:17]
        regs_12_cmd_rs2 = {_RANDOM[8'h6A][31:4], _RANDOM[8'h6B], _RANDOM[8'h6C][3:0]};	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :22:17]
        regs_12_rob_id_valid = _RANDOM[8'h6F][13];	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :22:17]
        regs_12_rob_id_bits = _RANDOM[8'h6F][20:14];	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :22:17]
        regs_13_cmd_inst_funct = _RANDOM[8'h6F][29:23];	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :22:17]
        regs_13_cmd_rs1 = {_RANDOM[8'h70][31:23], _RANDOM[8'h71], _RANDOM[8'h72][22:0]};	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :22:17]
        regs_13_cmd_rs2 = {_RANDOM[8'h72][31:23], _RANDOM[8'h73], _RANDOM[8'h74][22:0]};	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :22:17]
        regs_13_rob_id_valid = _RANDOM[8'h78][0];	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :22:17]
        regs_13_rob_id_bits = _RANDOM[8'h78][7:1];	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :22:17]
        regs_14_cmd_inst_funct = _RANDOM[8'h78][16:10];	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :22:17]
        regs_14_cmd_rs1 = {_RANDOM[8'h79][31:10], _RANDOM[8'h7A], _RANDOM[8'h7B][9:0]};	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :22:17]
        regs_14_cmd_rs2 = {_RANDOM[8'h7B][31:10], _RANDOM[8'h7C], _RANDOM[8'h7D][9:0]};	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :22:17]
        regs_14_rob_id_valid = _RANDOM[8'h80][19];	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :22:17]
        regs_14_rob_id_bits = _RANDOM[8'h80][26:20];	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :22:17]
        regs_15_cmd_inst_funct = {_RANDOM[8'h80][31:29], _RANDOM[8'h81][3:0]};	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :22:17]
        regs_15_cmd_rs1 = {_RANDOM[8'h81][31:29], _RANDOM[8'h82], _RANDOM[8'h83][28:0]};	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :22:17]
        regs_15_cmd_rs2 = {_RANDOM[8'h83][31:29], _RANDOM[8'h84], _RANDOM[8'h85][28:0]};	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :22:17]
        regs_15_rob_id_valid = _RANDOM[8'h89][6];	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :22:17]
        regs_15_rob_id_bits = _RANDOM[8'h89][13:7];	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :22:17]
        raddr = _RANDOM[8'h89][19:16];	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :22:17, :23:22]
        waddr = _RANDOM[8'h89][23:20];	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :22:17, :24:22]
        len = _RANDOM[8'h89][28:24];	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :22:17, :25:20]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7]
      `FIRRTL_AFTER_INITIAL	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_enq_ready = ~(len[4]);	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :25:20, :27:23]
  assign io_deq_valid_0 = |len;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :25:20, :31:28]
  assign io_deq_valid_1 = |(len[4:1]);	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :25:20, :31:28]
  assign io_deq_valid_2 = len > 5'h2;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :25:20, :31:28]
  assign io_deq_bits_0_cmd_inst_funct = _GEN[raddr];	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :23:22, :32:20]
  assign io_deq_bits_0_cmd_rs1 = _GEN_0[raddr];	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :23:22, :32:20]
  assign io_deq_bits_0_cmd_rs2 = _GEN_1[raddr];	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :23:22, :32:20]
  assign io_deq_bits_0_rob_id_valid = _GEN_2[raddr];	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :23:22, :32:20]
  assign io_deq_bits_0_rob_id_bits = _GEN_3[raddr];	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :23:22, :32:20]
  assign io_deq_bits_1_cmd_inst_funct = _GEN[_io_deq_bits_1_T_19];	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :32:20, generators/gemmini/src/main/scala/gemmini/Util.scala:13:10]
  assign io_deq_bits_1_cmd_rs1 = _GEN_0[_io_deq_bits_1_T_19];	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :32:20, generators/gemmini/src/main/scala/gemmini/Util.scala:13:10]
  assign io_deq_bits_1_cmd_rs2 = _GEN_1[_io_deq_bits_1_T_19];	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :32:20, generators/gemmini/src/main/scala/gemmini/Util.scala:13:10]
  assign io_deq_bits_1_rob_id_valid = _GEN_2[_io_deq_bits_1_T_19];	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :32:20, generators/gemmini/src/main/scala/gemmini/Util.scala:13:10]
  assign io_deq_bits_1_rob_id_bits = _GEN_3[_io_deq_bits_1_T_19];	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :32:20, generators/gemmini/src/main/scala/gemmini/Util.scala:13:10]
  assign io_deq_bits_2_cmd_rs1 = _GEN_0[_io_deq_bits_2_T_19];	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :32:20, generators/gemmini/src/main/scala/gemmini/Util.scala:13:10]
  assign io_deq_bits_2_cmd_rs2 = _GEN_1[_io_deq_bits_2_T_19];	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :32:20, generators/gemmini/src/main/scala/gemmini/Util.scala:13:10]
  assign io_deq_bits_2_rob_id_bits = _GEN_3[_io_deq_bits_2_T_19];	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:7:7, :32:20, generators/gemmini/src/main/scala/gemmini/Util.scala:13:10]
endmodule

