#!/usr/bin/env python3
"""Build RTL class lookup tables from the exact checked-in model header."""

import re
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
PARAMS = ROOT / "sw/yolov5/generators/gemmini/software/gemmini-rocc-tests/imagenet/yolov5nu-stage8f-dual-consumer-spad-reuse-img640x480-image025-profile_params.h"
OUTPUT = ROOT / "rtl/ai/postprocess/yolov5nu_raw_class_lut.sv"
DFL_OUTPUT = ROOT / "rtl/ai/postprocess/yolov5nu_dfl_lut.sv"


def main() -> None:
    source = PARAMS.read_text()
    match = re.search(r"yolov5nu_sigmoid_lut0\[256\]\s*=\s*\{([^}]+)\}", source)
    if not match:
        raise SystemExit("model sigmoid LUT missing")
    sigmoid = [int(value) for value in re.findall(r"-?\d+", match.group(1))]
    if len(sigmoid) != 256:
        raise SystemExit("invalid sigmoid LUT length")
    scales = [0.2354075164, 0.3665552139, 0.449272126]
    out_scale = np.float32(0.449272126)
    lines = [
        "`timescale 1ns/1ps",
        "// Generated by scripts/generate_yolov5nu_postprocess_luts.py.",
        "// Exact 256-entry model sigmoid ROM after per-head INT8 requantization.",
        "module yolov5nu_raw_class_lut (",
        "    input wire [1:0] head,",
        "    input wire [7:0] raw,",
        "    output reg [7:0] score",
        ");",
        "    always @* begin",
        "        case ({head, raw})",
    ]
    for head, scale in enumerate(scales):
        for raw in range(256):
            signed = raw if raw < 128 else raw - 256
            value = np.float32(np.float32(signed) * np.float32(scale))
            quant = int(np.rint(np.float32(value / out_scale)))
            quant = min(127, max(-128, quant))
            lines.append(f"        10'h{head * 256 + raw:03x}: score = 8'd{sigmoid[quant & 255]};")
    lines.extend(["        default: score = 8'd0;", "        endcase", "    end", "endmodule", ""])
    OUTPUT.write_text("\n".join(lines))
    print(f"wrote {OUTPUT.relative_to(ROOT)} ({len(scales) * 256} entries)")

    dfl_scales = [0.2151331604, 0.1472641826, 0.1159213334]
    dfl_scale = np.float32(0.2151331604)
    exp_match = re.search(r"yolov5nu_softmax_exp_lut0\[256\]\s*=\s*\{([^}]+)\}", source)
    if not exp_match:
        raise SystemExit("model DFL exponent LUT missing")
    exp_values = [float(number) for number in re.findall(
        r"(?:\d+\.\d*|\d*\.\d+|\d+)(?:e[+-]?\d+)?", exp_match.group(1)
    )]
    if len(exp_values) != 256:
        raise SystemExit(f"invalid DFL exponent length {len(exp_values)}")
    lines = [
        "`timescale 1ns/1ps",
        "// Generated from the checked-in model's requant and softmax constants.",
        "module yolov5nu_dfl_lut (",
        "    input wire [1:0] head, input wire [7:0] raw,",
        "    input wire [7:0] exponent_difference,",
        "    output reg signed [7:0] requant,",
        "    output reg [24:0] exponent_q24",
        ");",
        "    always @* begin",
        "        case ({head, raw})",
    ]
    for head, scale in enumerate(dfl_scales):
        for raw in range(256):
            signed = raw if raw < 128 else raw - 256
            value = np.float32(np.float32(signed) * np.float32(scale))
            quant = int(np.rint(np.float32(value / dfl_scale)))
            quant = min(127, max(-128, quant))
            lines.append(f"        10'h{head * 256 + raw:03x}: requant = 8'sh{quant & 255:02x};")
    lines += ["        default: requant = 8'sd0;", "        endcase",
              "        case (exponent_difference)"]
    for diff, value in enumerate(exp_values):
        number = int(round(float(np.float32(value)) * (1 << 24)))
        lines.append(f"        8'd{diff}: exponent_q24 = 25'd{number};")
    lines += ["        default: exponent_q24 = 25'd0;", "        endcase", "    end", "endmodule", ""]
    DFL_OUTPUT.write_text("\n".join(lines))
    print(f"wrote {DFL_OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
