#!/usr/bin/env python3
"""Generate exact COCO labels; score rounding has two registered stages."""
from pathlib import Path
import re
root=Path(__file__).resolve().parents[1]
s=(root/'sw/src/ai_class_names.c').read_text().split('coco_names[80] = {',1)[1].split('};',1)[0]
names=re.findall(r'"([^"]+)"',s);assert len(names)==80
out=['`timescale 1ns/1ps','// Generated by scripts/generate_ppu_overlay_labels.py.','module ppu_overlay_label(input wire clk,input wire [7:0] class_id,input wire [15:0] score,output wire [127:0] label);','reg [127:0] name,name1,name2;reg [4:0] length,length1,length2;','reg [22:0] scaled;reg [6:0] percent;reg [39:0] suffix;','always @* begin','name=0;length=0;case(class_id)']
for i,name in enumerate(names+['unknown']):
 out += [f"{'default' if i==80 else str(i)}:begin name=128'h{int.from_bytes(name.encode().ljust(16,bytes([0])),'little'):032x};length={len(name)};end"]
out+=['endcase','end','always @(posedge clk) begin','name1<=name;length1<=length;scaled<=({7\'d0,score}<<6)+({7\'d0,score}<<5)+({7\'d0,score}<<2)+23\'d16384;','name2<=name1;length2<=length1;percent<=scaled[22:15]>100?100:scaled[21:15];','end','always @* begin case(percent)']
for n in range(101):out += [f"{n}:suffix=40'h{int.from_bytes((' '+str(n)+'%').encode().ljust(5,bytes([0])),'little'):010x};"]
out+=['default:suffix=0;endcase end',"assign label=name2|({88'd0,suffix}<<(length2*8));",'endmodule']
(root/'rtl/ai/postprocess/ppu_overlay_label.sv').write_text('\n'.join(out)+'\n')
