// Generated by CIRCT firtool-1.75.0
module Arbiter2_VectorWrite(	// @[src/main/scala/chisel3/util/Arbiter.scala:133:7]
  output        io_in_0_ready,	// @[src/main/scala/chisel3/util/Arbiter.scala:140:14]
  input         io_in_0_valid,	// @[src/main/scala/chisel3/util/Arbiter.scala:140:14]
  input  [5:0]  io_in_0_bits_eg,	// @[src/main/scala/chisel3/util/Arbiter.scala:140:14]
  input  [63:0] io_in_0_bits_data,	// @[src/main/scala/chisel3/util/Arbiter.scala:140:14]
  input  [63:0] io_in_0_bits_mask,	// @[src/main/scala/chisel3/util/Arbiter.scala:140:14]
  output        io_in_1_ready,	// @[src/main/scala/chisel3/util/Arbiter.scala:140:14]
  input         io_in_1_valid,	// @[src/main/scala/chisel3/util/Arbiter.scala:140:14]
  input  [5:0]  io_in_1_bits_eg,	// @[src/main/scala/chisel3/util/Arbiter.scala:140:14]
  input  [63:0] io_in_1_bits_data,	// @[src/main/scala/chisel3/util/Arbiter.scala:140:14]
  input  [63:0] io_in_1_bits_mask,	// @[src/main/scala/chisel3/util/Arbiter.scala:140:14]
  input         io_out_ready,	// @[src/main/scala/chisel3/util/Arbiter.scala:140:14]
  output        io_out_valid,	// @[src/main/scala/chisel3/util/Arbiter.scala:140:14]
  output [5:0]  io_out_bits_eg,	// @[src/main/scala/chisel3/util/Arbiter.scala:140:14]
  output [63:0] io_out_bits_data,	// @[src/main/scala/chisel3/util/Arbiter.scala:140:14]
  output [63:0] io_out_bits_mask	// @[src/main/scala/chisel3/util/Arbiter.scala:140:14]
);

  assign io_in_0_ready = io_out_ready;	// @[src/main/scala/chisel3/util/Arbiter.scala:133:7]
  assign io_in_1_ready = ~io_in_0_valid & io_out_ready;	// @[src/main/scala/chisel3/util/Arbiter.scala:45:78, :133:7, :153:19]
  assign io_out_valid = io_in_0_valid | io_in_1_valid;	// @[src/main/scala/chisel3/util/Arbiter.scala:133:7, :154:31]
  assign io_out_bits_eg = io_in_0_valid ? io_in_0_bits_eg : io_in_1_bits_eg;	// @[src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19]
  assign io_out_bits_data = io_in_0_valid ? io_in_0_bits_data : io_in_1_bits_data;	// @[src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19]
  assign io_out_bits_mask = io_in_0_valid ? io_in_0_bits_mask : io_in_1_bits_mask;	// @[src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19]
endmodule

