// Generated by CIRCT firtool-1.75.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module DCEQueue_7(	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:12:7]
  input         clock,	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:12:7]
  input         reset,	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:12:7]
  output        io_enq_ready,	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:20:14]
  input         io_enq_valid,	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:20:14]
  input  [2:0]  io_enq_bits_sifq_head,	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:20:14]
  input  [2:0]  io_enq_bits_sifq_tail,	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:20:14]
  input         io_enq_bits_sifq_masked,	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:20:14]
  input         io_enq_bits_sifq_last,	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:20:14]
  input  [1:0]  io_enq_bits_sifq_lsiq_id,	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:20:14]
  input  [39:0] io_enq_bits_request_addr,	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:20:14]
  input  [3:0]  io_enq_bits_request_tag,	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:20:14]
  input         io_deq_ready,	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:20:14]
  output        io_deq_valid,	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:20:14]
  output [2:0]  io_deq_bits_sifq_head,	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:20:14]
  output [2:0]  io_deq_bits_sifq_tail,	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:20:14]
  output        io_deq_bits_sifq_masked,	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:20:14]
  output        io_deq_bits_sifq_last,	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:20:14]
  output [1:0]  io_deq_bits_sifq_lsiq_id,	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:20:14]
  output [39:0] io_deq_bits_request_addr,	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:20:14]
  output [3:0]  io_deq_bits_request_tag	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:20:14]
);

  reg  [2:0]  ram_0_sifq_head;	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:24:16]
  reg  [2:0]  ram_0_sifq_tail;	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:24:16]
  reg         ram_0_sifq_masked;	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:24:16]
  reg         ram_0_sifq_last;	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:24:16]
  reg  [1:0]  ram_0_sifq_lsiq_id;	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:24:16]
  reg  [39:0] ram_0_request_addr;	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:24:16]
  reg  [3:0]  ram_0_request_tag;	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:24:16]
  reg  [2:0]  ram_1_sifq_head;	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:24:16]
  reg  [2:0]  ram_1_sifq_tail;	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:24:16]
  reg         ram_1_sifq_masked;	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:24:16]
  reg         ram_1_sifq_last;	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:24:16]
  reg  [1:0]  ram_1_sifq_lsiq_id;	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:24:16]
  reg  [39:0] ram_1_request_addr;	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:24:16]
  reg  [3:0]  ram_1_request_tag;	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:24:16]
  reg         wrap_1;	// @[src/main/scala/chisel3/util/Counter.scala:61:40]
  reg         wrap;	// @[src/main/scala/chisel3/util/Counter.scala:61:40]
  reg         maybe_full;	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:27:27]
  wire        ptr_match = wrap_1 == wrap;	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:28:33, src/main/scala/chisel3/util/Counter.scala:61:40]
  wire        empty = ptr_match & ~maybe_full;	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:27:27, :28:33, :29:{25,28}]
  wire        full = ptr_match & maybe_full;	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:27:27, :28:33, :30:24]
  wire        do_deq = io_deq_ready & ~empty;	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:29:25, :54:19, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire        do_enq = ~full & io_enq_valid;	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:30:24, :55:19, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  always @(posedge clock) begin	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:12:7]
    if (do_enq & ~wrap_1) begin	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:24:16, :44:16, :45:24, src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      ram_0_sifq_head <= io_enq_bits_sifq_head;	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:24:16]
      ram_0_sifq_tail <= io_enq_bits_sifq_tail;	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:24:16]
      ram_0_sifq_masked <= io_enq_bits_sifq_masked;	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:24:16]
      ram_0_sifq_last <= io_enq_bits_sifq_last;	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:24:16]
      ram_0_sifq_lsiq_id <= io_enq_bits_sifq_lsiq_id;	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:24:16]
      ram_0_request_addr <= io_enq_bits_request_addr;	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:24:16]
      ram_0_request_tag <= io_enq_bits_request_tag;	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:24:16]
    end
    if (do_enq & wrap_1) begin	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:24:16, :44:16, :45:24, src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      ram_1_sifq_head <= io_enq_bits_sifq_head;	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:24:16]
      ram_1_sifq_tail <= io_enq_bits_sifq_tail;	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:24:16]
      ram_1_sifq_masked <= io_enq_bits_sifq_masked;	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:24:16]
      ram_1_sifq_last <= io_enq_bits_sifq_last;	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:24:16]
      ram_1_sifq_lsiq_id <= io_enq_bits_sifq_lsiq_id;	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:24:16]
      ram_1_request_addr <= io_enq_bits_request_addr;	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:24:16]
      ram_1_request_tag <= io_enq_bits_request_tag;	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:24:16]
    end
    if (reset) begin	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:12:7]
      wrap_1 <= 1'h0;	// @[src/main/scala/chisel3/util/Counter.scala:61:40]
      wrap <= 1'h0;	// @[src/main/scala/chisel3/util/Counter.scala:61:40]
      maybe_full <= 1'h0;	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:27:27]
    end
    else begin	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:12:7]
      if (do_enq)	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35]
        wrap_1 <= wrap_1 - 1'h1;	// @[src/main/scala/chisel3/util/Counter.scala:61:40, :77:24]
      if (do_deq)	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35]
        wrap <= wrap - 1'h1;	// @[src/main/scala/chisel3/util/Counter.scala:61:40, :77:24]
      if (~(do_enq == do_deq))	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:27:27, :50:{15,27}, :51:16, src/main/scala/chisel3/util/Decoupled.scala:51:35]
        maybe_full <= do_enq;	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:27:27, src/main/scala/chisel3/util/Decoupled.scala:51:35]
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:12:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:12:7]
      `FIRRTL_BEFORE_INITIAL	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:12:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:8];	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:12:7]
    initial begin	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:12:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:12:7]
        `INIT_RANDOM_PROLOG_	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:12:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:12:7]
        for (logic [3:0] i = 4'h0; i < 4'h9; i += 4'h1) begin
          _RANDOM[i] = `RANDOM;	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:12:7]
        end	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:12:7]
        ram_0_sifq_head = _RANDOM[4'h0][4:2];	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:12:7, :24:16]
        ram_0_sifq_tail = _RANDOM[4'h0][7:5];	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:12:7, :24:16]
        ram_0_sifq_masked = _RANDOM[4'h0][8];	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:12:7, :24:16]
        ram_0_sifq_last = _RANDOM[4'h0][9];	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:12:7, :24:16]
        ram_0_sifq_lsiq_id = _RANDOM[4'h0][11:10];	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:12:7, :24:16]
        ram_0_request_addr = {_RANDOM[4'h0][31:24], _RANDOM[4'h1]};	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:12:7, :24:16]
        ram_0_request_tag = _RANDOM[4'h4][11:8];	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:12:7, :24:16]
        ram_1_sifq_head = _RANDOM[4'h4][15:13];	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:12:7, :24:16]
        ram_1_sifq_tail = _RANDOM[4'h4][18:16];	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:12:7, :24:16]
        ram_1_sifq_masked = _RANDOM[4'h4][19];	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:12:7, :24:16]
        ram_1_sifq_last = _RANDOM[4'h4][20];	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:12:7, :24:16]
        ram_1_sifq_lsiq_id = _RANDOM[4'h4][22:21];	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:12:7, :24:16]
        ram_1_request_addr = {_RANDOM[4'h5][31:3], _RANDOM[4'h6][10:0]};	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:12:7, :24:16]
        ram_1_request_tag = _RANDOM[4'h8][22:19];	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:12:7, :24:16]
        wrap_1 = _RANDOM[4'h8][24];	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:12:7, :24:16, src/main/scala/chisel3/util/Counter.scala:61:40]
        wrap = _RANDOM[4'h8][25];	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:12:7, :24:16, src/main/scala/chisel3/util/Counter.scala:61:40]
        maybe_full = _RANDOM[4'h8][26];	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:12:7, :24:16, :27:27]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:12:7]
      `FIRRTL_AFTER_INITIAL	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:12:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_enq_ready = ~full;	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:12:7, :30:24, :55:19]
  assign io_deq_valid = ~empty;	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:12:7, :29:25, :54:19]
  assign io_deq_bits_sifq_head = wrap ? ram_1_sifq_head : ram_0_sifq_head;	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:12:7, :24:16, :57:15, src/main/scala/chisel3/util/Counter.scala:61:40]
  assign io_deq_bits_sifq_tail = wrap ? ram_1_sifq_tail : ram_0_sifq_tail;	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:12:7, :24:16, :57:15, src/main/scala/chisel3/util/Counter.scala:61:40]
  assign io_deq_bits_sifq_masked = wrap ? ram_1_sifq_masked : ram_0_sifq_masked;	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:12:7, :24:16, :57:15, src/main/scala/chisel3/util/Counter.scala:61:40]
  assign io_deq_bits_sifq_last = wrap ? ram_1_sifq_last : ram_0_sifq_last;	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:12:7, :24:16, :57:15, src/main/scala/chisel3/util/Counter.scala:61:40]
  assign io_deq_bits_sifq_lsiq_id = wrap ? ram_1_sifq_lsiq_id : ram_0_sifq_lsiq_id;	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:12:7, :24:16, :57:15, src/main/scala/chisel3/util/Counter.scala:61:40]
  assign io_deq_bits_request_addr = wrap ? ram_1_request_addr : ram_0_request_addr;	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:12:7, :24:16, :57:15, src/main/scala/chisel3/util/Counter.scala:61:40]
  assign io_deq_bits_request_tag = wrap ? ram_1_request_tag : ram_0_request_tag;	// @[generators/saturn/src/main/scala/common/DCEQueue.scala:12:7, :24:16, :57:15, src/main/scala/chisel3/util/Counter.scala:61:40]
endmodule

