// Generated by CIRCT firtool-1.75.0
module EarlyVectorDecode(	// @[generators/saturn/src/main/scala/frontend/EarlyDecode.scala:10:7]
  input  [31:0] io_inst,	// @[generators/rocket-chip/src/main/scala/rocket/VectorUnit.scala:91:14]
  input         io_vconfig_vtype_vill,	// @[generators/rocket-chip/src/main/scala/rocket/VectorUnit.scala:91:14]
  input  [2:0]  io_vconfig_vtype_vsew,	// @[generators/rocket-chip/src/main/scala/rocket/VectorUnit.scala:91:14]
  output        io_vector,	// @[generators/rocket-chip/src/main/scala/rocket/VectorUnit.scala:91:14]
  output        io_legal,	// @[generators/rocket-chip/src/main/scala/rocket/VectorUnit.scala:91:14]
  output        io_fp,	// @[generators/rocket-chip/src/main/scala/rocket/VectorUnit.scala:91:14]
  output        io_read_rs1,	// @[generators/rocket-chip/src/main/scala/rocket/VectorUnit.scala:91:14]
  output        io_read_rs2,	// @[generators/rocket-chip/src/main/scala/rocket/VectorUnit.scala:91:14]
  output        io_read_frs1,	// @[generators/rocket-chip/src/main/scala/rocket/VectorUnit.scala:91:14]
  output        io_write_rd,	// @[generators/rocket-chip/src/main/scala/rocket/VectorUnit.scala:91:14]
  output        io_write_frd	// @[generators/rocket-chip/src/main/scala/rocket/VectorUnit.scala:91:14]
);

  wire        _v_store_T_1 = io_inst[14:12] == 3'h1;	// @[generators/rocket-chip/src/main/scala/util/package.scala:17:47, generators/saturn/src/main/scala/frontend/EarlyDecode.scala:23:22]
  wire        _v_store_T_2 = io_inst[14:12] == 3'h2;	// @[generators/rocket-chip/src/main/scala/util/package.scala:17:47, generators/saturn/src/main/scala/frontend/EarlyDecode.scala:23:22]
  wire        _v_store_T_3 = io_inst[14:12] == 3'h3;	// @[generators/rocket-chip/src/main/scala/util/package.scala:17:47, generators/saturn/src/main/scala/frontend/EarlyDecode.scala:23:22]
  wire        _v_store_T_4 = io_inst[14:12] == 3'h4;	// @[generators/rocket-chip/src/main/scala/util/package.scala:17:47, generators/saturn/src/main/scala/frontend/EarlyDecode.scala:23:22]
  wire        v_load = io_inst[6:0] == 7'h7 & ~(_v_store_T_1 | _v_store_T_2 | _v_store_T_3 | _v_store_T_4);	// @[generators/rocket-chip/src/main/scala/util/package.scala:17:47, :82:59, generators/saturn/src/main/scala/frontend/EarlyDecode.scala:21:23, :35:{23,35,38}]
  wire        v_store = io_inst[6:0] == 7'h27 & ~(_v_store_T_1 | _v_store_T_2 | _v_store_T_3 | _v_store_T_4);	// @[generators/rocket-chip/src/main/scala/util/package.scala:17:47, :82:59, generators/saturn/src/main/scala/frontend/EarlyDecode.scala:21:23, :36:{24,37,40}]
  wire        v_arith_maybe = io_inst[6:0] == 7'h57 & io_inst[14:12] != 3'h7;	// @[generators/saturn/src/main/scala/frontend/EarlyDecode.scala:21:23, :23:22, :37:{30,44,54}]
  wire [20:0] v_arith_decode_invInputs = ~{io_inst[19:15], io_inst[24:20], io_inst[14:12], io_inst[31:26], io_vconfig_vtype_vsew[1:0]};	// @[generators/saturn/src/main/scala/frontend/EarlyDecode.scala:23:22, :24:22, :31:23, :32:20, generators/saturn/src/main/scala/insns/Decode.scala:60:{18,68}, src/main/scala/chisel3/util/pla.scala:78:21]
  wire [91:0] _v_arith_decode_orMatrixOutputs_T =
    {&{v_arith_decode_invInputs[2], v_arith_decode_invInputs[4], v_arith_decode_invInputs[5], v_arith_decode_invInputs[6], v_arith_decode_invInputs[8], v_arith_decode_invInputs[9]},
     &{v_arith_decode_invInputs[3], v_arith_decode_invInputs[5], v_arith_decode_invInputs[7], v_arith_decode_invInputs[8], v_arith_decode_invInputs[9]},
     &{io_vconfig_vtype_vsew[0], v_arith_decode_invInputs[2], v_arith_decode_invInputs[5], v_arith_decode_invInputs[6], v_arith_decode_invInputs[7], v_arith_decode_invInputs[9]},
     &{io_vconfig_vtype_vsew[1], v_arith_decode_invInputs[2], v_arith_decode_invInputs[5], v_arith_decode_invInputs[6], v_arith_decode_invInputs[7], v_arith_decode_invInputs[9]},
     &{v_arith_decode_invInputs[2], io_inst[27], v_arith_decode_invInputs[6], v_arith_decode_invInputs[7], v_arith_decode_invInputs[8], v_arith_decode_invInputs[9]},
     &{v_arith_decode_invInputs[2], io_inst[27], v_arith_decode_invInputs[4], v_arith_decode_invInputs[7], v_arith_decode_invInputs[8], v_arith_decode_invInputs[10], v_arith_decode_invInputs[16], v_arith_decode_invInputs[20]},
     &{v_arith_decode_invInputs[2], io_inst[27], v_arith_decode_invInputs[4], v_arith_decode_invInputs[7], v_arith_decode_invInputs[8], v_arith_decode_invInputs[10], v_arith_decode_invInputs[17], v_arith_decode_invInputs[20]},
     &{v_arith_decode_invInputs[2], io_inst[27], v_arith_decode_invInputs[4], v_arith_decode_invInputs[7], v_arith_decode_invInputs[8], v_arith_decode_invInputs[10], v_arith_decode_invInputs[19], v_arith_decode_invInputs[20]},
     &{io_vconfig_vtype_vsew[0], v_arith_decode_invInputs[1], v_arith_decode_invInputs[2], io_inst[27], v_arith_decode_invInputs[4], v_arith_decode_invInputs[5], v_arith_decode_invInputs[7], v_arith_decode_invInputs[9], v_arith_decode_invInputs[10], v_arith_decode_invInputs[19]},
     &{io_vconfig_vtype_vsew[0], v_arith_decode_invInputs[1], v_arith_decode_invInputs[2], io_inst[27], v_arith_decode_invInputs[4], v_arith_decode_invInputs[5], v_arith_decode_invInputs[7], v_arith_decode_invInputs[9], v_arith_decode_invInputs[10], v_arith_decode_invInputs[20]},
     &{io_vconfig_vtype_vsew[0], v_arith_decode_invInputs[2], io_inst[27], v_arith_decode_invInputs[4], v_arith_decode_invInputs[5], v_arith_decode_invInputs[7], v_arith_decode_invInputs[9], v_arith_decode_invInputs[10], v_arith_decode_invInputs[19], v_arith_decode_invInputs[20]},
     &{v_arith_decode_invInputs[0], io_vconfig_vtype_vsew[1], v_arith_decode_invInputs[2], io_inst[27], v_arith_decode_invInputs[4], v_arith_decode_invInputs[5], v_arith_decode_invInputs[7], v_arith_decode_invInputs[9], v_arith_decode_invInputs[10], v_arith_decode_invInputs[19]},
     &{v_arith_decode_invInputs[2], v_arith_decode_invInputs[3], io_inst[28], v_arith_decode_invInputs[7], v_arith_decode_invInputs[8], v_arith_decode_invInputs[9]},
     &{io_inst[26], io_inst[28], v_arith_decode_invInputs[5], v_arith_decode_invInputs[7], v_arith_decode_invInputs[8], v_arith_decode_invInputs[9]},
     &{io_inst[26], v_arith_decode_invInputs[4], io_inst[29], v_arith_decode_invInputs[6], v_arith_decode_invInputs[8]},
     &{io_vconfig_vtype_vsew[0], v_arith_decode_invInputs[2], io_inst[27], v_arith_decode_invInputs[4], io_inst[29], v_arith_decode_invInputs[6], v_arith_decode_invInputs[9]},
     &{io_vconfig_vtype_vsew[1], v_arith_decode_invInputs[2], io_inst[27], v_arith_decode_invInputs[4], io_inst[29], v_arith_decode_invInputs[6], v_arith_decode_invInputs[9]},
     &{v_arith_decode_invInputs[3], io_inst[30], v_arith_decode_invInputs[7], v_arith_decode_invInputs[8], v_arith_decode_invInputs[9]},
     &{v_arith_decode_invInputs[4], io_inst[30], v_arith_decode_invInputs[7], v_arith_decode_invInputs[8], v_arith_decode_invInputs[9]},
     &{v_arith_decode_invInputs[2], v_arith_decode_invInputs[3], v_arith_decode_invInputs[4], v_arith_decode_invInputs[5], io_inst[30], v_arith_decode_invInputs[7], v_arith_decode_invInputs[10], v_arith_decode_invInputs[16], v_arith_decode_invInputs[17], v_arith_decode_invInputs[18], v_arith_decode_invInputs[19], v_arith_decode_invInputs[20]},
     &{io_vconfig_vtype_vsew[0], io_inst[26], io_inst[27], v_arith_decode_invInputs[4], io_inst[30], v_arith_decode_invInputs[7], v_arith_decode_invInputs[9], v_arith_decode_invInputs[10], v_arith_decode_invInputs[16], v_arith_decode_invInputs[17], v_arith_decode_invInputs[18], v_arith_decode_invInputs[19]},
     &{io_vconfig_vtype_vsew[1], io_inst[26], io_inst[27], v_arith_decode_invInputs[4], io_inst[30], v_arith_decode_invInputs[7], v_arith_decode_invInputs[9], v_arith_decode_invInputs[10], v_arith_decode_invInputs[16], v_arith_decode_invInputs[17], v_arith_decode_invInputs[18], v_arith_decode_invInputs[19]},
     &{io_vconfig_vtype_vsew[0], io_inst[26], v_arith_decode_invInputs[4], io_inst[29], io_inst[30], v_arith_decode_invInputs[7], v_arith_decode_invInputs[9]},
     &{io_vconfig_vtype_vsew[1], io_inst[26], v_arith_decode_invInputs[4], io_inst[29], io_inst[30], v_arith_decode_invInputs[7], v_arith_decode_invInputs[9]},
     &{v_arith_decode_invInputs[0], v_arith_decode_invInputs[3], v_arith_decode_invInputs[4], v_arith_decode_invInputs[5], io_inst[31], v_arith_decode_invInputs[8], v_arith_decode_invInputs[10]},
     &{v_arith_decode_invInputs[1], v_arith_decode_invInputs[3], v_arith_decode_invInputs[4], v_arith_decode_invInputs[5], io_inst[31], v_arith_decode_invInputs[8], v_arith_decode_invInputs[10]},
     &{io_inst[26], v_arith_decode_invInputs[5], v_arith_decode_invInputs[6], io_inst[31], v_arith_decode_invInputs[8]},
     &{v_arith_decode_invInputs[0], io_inst[26], v_arith_decode_invInputs[3], io_inst[28], v_arith_decode_invInputs[5], io_inst[31], v_arith_decode_invInputs[8]},
     &{v_arith_decode_invInputs[1], io_inst[26], v_arith_decode_invInputs[3], io_inst[28], v_arith_decode_invInputs[5], io_inst[31], v_arith_decode_invInputs[8]},
     &{v_arith_decode_invInputs[0], io_inst[29], v_arith_decode_invInputs[6], io_inst[31], v_arith_decode_invInputs[8], v_arith_decode_invInputs[9]},
     &{io_vconfig_vtype_vsew[0], v_arith_decode_invInputs[1], io_inst[29], v_arith_decode_invInputs[6], io_inst[31], v_arith_decode_invInputs[9]},
     &{io_vconfig_vtype_vsew[1], v_arith_decode_invInputs[4], io_inst[29], v_arith_decode_invInputs[6], io_inst[31], v_arith_decode_invInputs[9]},
     &{io_vconfig_vtype_vsew[0], v_arith_decode_invInputs[2], v_arith_decode_invInputs[3], v_arith_decode_invInputs[5], v_arith_decode_invInputs[6], io_inst[12], v_arith_decode_invInputs[9]},
     &{io_vconfig_vtype_vsew[0], v_arith_decode_invInputs[5], v_arith_decode_invInputs[6], v_arith_decode_invInputs[7], io_inst[12], v_arith_decode_invInputs[9], v_arith_decode_invInputs[10]},
     &{io_vconfig_vtype_vsew[1], v_arith_decode_invInputs[2], v_arith_decode_invInputs[3], v_arith_decode_invInputs[5], v_arith_decode_invInputs[6], io_inst[12], v_arith_decode_invInputs[9]},
     &{io_vconfig_vtype_vsew[1], v_arith_decode_invInputs[5], v_arith_decode_invInputs[6], v_arith_decode_invInputs[7], io_inst[12], v_arith_decode_invInputs[9], v_arith_decode_invInputs[10]},
     &{io_vconfig_vtype_vsew[0], v_arith_decode_invInputs[3], v_arith_decode_invInputs[4], io_inst[29], v_arith_decode_invInputs[6], io_inst[12], v_arith_decode_invInputs[9]},
     &{io_vconfig_vtype_vsew[1], v_arith_decode_invInputs[3], v_arith_decode_invInputs[4], io_inst[29], v_arith_decode_invInputs[6], io_inst[12], v_arith_decode_invInputs[9]},
     &{io_vconfig_vtype_vsew[0], v_arith_decode_invInputs[2], v_arith_decode_invInputs[3], io_inst[29], io_inst[30], io_inst[12], v_arith_decode_invInputs[9]},
     &{io_vconfig_vtype_vsew[1], v_arith_decode_invInputs[2], v_arith_decode_invInputs[3], io_inst[29], io_inst[30], io_inst[12], v_arith_decode_invInputs[9]},
     &{io_vconfig_vtype_vsew[0], v_arith_decode_invInputs[1], io_inst[29], v_arith_decode_invInputs[6], io_inst[31], io_inst[12], v_arith_decode_invInputs[10]},
     &{io_vconfig_vtype_vsew[0], io_inst[28], io_inst[29], io_inst[31], io_inst[12], v_arith_decode_invInputs[9]},
     &{io_vconfig_vtype_vsew[1], io_inst[28], io_inst[29], io_inst[31], io_inst[12], v_arith_decode_invInputs[9]},
     &{io_vconfig_vtype_vsew[0], v_arith_decode_invInputs[2], v_arith_decode_invInputs[5], io_inst[30], io_inst[31], io_inst[12], v_arith_decode_invInputs[9]},
     &{io_vconfig_vtype_vsew[0], v_arith_decode_invInputs[4], v_arith_decode_invInputs[5], io_inst[30], io_inst[31], io_inst[12], v_arith_decode_invInputs[9], v_arith_decode_invInputs[10]},
     &{io_vconfig_vtype_vsew[1], v_arith_decode_invInputs[2], v_arith_decode_invInputs[5], io_inst[30], io_inst[31], io_inst[12], v_arith_decode_invInputs[9]},
     &{io_vconfig_vtype_vsew[1], v_arith_decode_invInputs[4], v_arith_decode_invInputs[5], io_inst[30], io_inst[31], io_inst[12], v_arith_decode_invInputs[9], v_arith_decode_invInputs[10]},
     &{v_arith_decode_invInputs[2], v_arith_decode_invInputs[3], v_arith_decode_invInputs[4], v_arith_decode_invInputs[5], v_arith_decode_invInputs[6], io_inst[13], v_arith_decode_invInputs[10]},
     &{v_arith_decode_invInputs[5], v_arith_decode_invInputs[6], v_arith_decode_invInputs[8], io_inst[13], v_arith_decode_invInputs[10]},
     &{io_inst[26], io_inst[27], v_arith_decode_invInputs[4], v_arith_decode_invInputs[6], v_arith_decode_invInputs[7], io_inst[13], v_arith_decode_invInputs[10]},
     &{v_arith_decode_invInputs[4], io_inst[29], v_arith_decode_invInputs[6], v_arith_decode_invInputs[7], v_arith_decode_invInputs[8], io_inst[13]},
     &{io_inst[26], v_arith_decode_invInputs[4], io_inst[29], v_arith_decode_invInputs[6], io_inst[13], v_arith_decode_invInputs[10]},
     &{io_inst[26], io_inst[27], io_inst[28], io_inst[30], v_arith_decode_invInputs[7], io_inst[13], v_arith_decode_invInputs[10]},
     &{io_inst[29], io_inst[30], v_arith_decode_invInputs[7], v_arith_decode_invInputs[8], io_inst[13], v_arith_decode_invInputs[10]},
     &{v_arith_decode_invInputs[0], v_arith_decode_invInputs[5], io_inst[31], v_arith_decode_invInputs[8], io_inst[13]},
     &{v_arith_decode_invInputs[1], v_arith_decode_invInputs[5], io_inst[31], v_arith_decode_invInputs[8], io_inst[13]},
     &{v_arith_decode_invInputs[5], v_arith_decode_invInputs[6], io_inst[31], v_arith_decode_invInputs[8], io_inst[13]},
     &{io_inst[26], v_arith_decode_invInputs[6], io_inst[31], v_arith_decode_invInputs[8], io_inst[13]},
     &{v_arith_decode_invInputs[0], io_inst[26], io_inst[27], io_inst[31], v_arith_decode_invInputs[8], io_inst[13]},
     &{v_arith_decode_invInputs[1], io_inst[26], io_inst[27], io_inst[31], v_arith_decode_invInputs[8], io_inst[13]},
     &{v_arith_decode_invInputs[0], io_inst[26], io_inst[28], io_inst[31], v_arith_decode_invInputs[8], io_inst[13]},
     &{v_arith_decode_invInputs[1], io_inst[26], io_inst[28], io_inst[31], v_arith_decode_invInputs[8], io_inst[13]},
     &{v_arith_decode_invInputs[0], io_inst[26], v_arith_decode_invInputs[3], io_inst[28], v_arith_decode_invInputs[5], io_inst[31], io_inst[13], v_arith_decode_invInputs[10]},
     &{v_arith_decode_invInputs[1], io_inst[26], v_arith_decode_invInputs[3], io_inst[28], v_arith_decode_invInputs[5], io_inst[31], io_inst[13], v_arith_decode_invInputs[10]},
     &{io_inst[26], io_inst[28], v_arith_decode_invInputs[5], v_arith_decode_invInputs[6], io_inst[31], io_inst[13], v_arith_decode_invInputs[10]},
     &{v_arith_decode_invInputs[0], v_arith_decode_invInputs[2], io_inst[30], io_inst[31], v_arith_decode_invInputs[8], io_inst[13]},
     &{v_arith_decode_invInputs[1], v_arith_decode_invInputs[2], io_inst[30], io_inst[31], v_arith_decode_invInputs[8], io_inst[13]},
     &{io_inst[27], v_arith_decode_invInputs[4], io_inst[29], v_arith_decode_invInputs[6], io_inst[12], io_inst[13], v_arith_decode_invInputs[10]},
     &{v_arith_decode_invInputs[2], io_inst[28], io_inst[29], v_arith_decode_invInputs[7], io_inst[12], io_inst[13], v_arith_decode_invInputs[10]},
     &{io_inst[27], io_inst[28], io_inst[29], v_arith_decode_invInputs[7], io_inst[12], io_inst[13], v_arith_decode_invInputs[10]},
     &{v_arith_decode_invInputs[3], io_inst[30], v_arith_decode_invInputs[7], io_inst[12], io_inst[13], v_arith_decode_invInputs[10]},
     &{v_arith_decode_invInputs[3], v_arith_decode_invInputs[4], v_arith_decode_invInputs[6], io_inst[31], io_inst[12], io_inst[13], v_arith_decode_invInputs[10]},
     &{v_arith_decode_invInputs[0], io_inst[29], v_arith_decode_invInputs[6], io_inst[31], io_inst[12], io_inst[13], v_arith_decode_invInputs[10]},
     &{io_inst[26], io_inst[27], v_arith_decode_invInputs[7], v_arith_decode_invInputs[8], v_arith_decode_invInputs[9], io_inst[14]},
     &{io_inst[27], io_inst[29], v_arith_decode_invInputs[6], v_arith_decode_invInputs[7], v_arith_decode_invInputs[8], io_inst[14]},
     &{io_inst[27], io_inst[29], v_arith_decode_invInputs[7], v_arith_decode_invInputs[8], v_arith_decode_invInputs[9], io_inst[14]},
     &{io_inst[27], io_inst[28], io_inst[29], v_arith_decode_invInputs[6], v_arith_decode_invInputs[7], v_arith_decode_invInputs[9], io_inst[14]},
     &{v_arith_decode_invInputs[2], v_arith_decode_invInputs[3], v_arith_decode_invInputs[4], v_arith_decode_invInputs[5], io_inst[30], v_arith_decode_invInputs[7], v_arith_decode_invInputs[8], io_inst[14], v_arith_decode_invInputs[11], v_arith_decode_invInputs[12], v_arith_decode_invInputs[13], v_arith_decode_invInputs[14], v_arith_decode_invInputs[15]},
     &{v_arith_decode_invInputs[2], v_arith_decode_invInputs[3], v_arith_decode_invInputs[4], v_arith_decode_invInputs[5], io_inst[30], v_arith_decode_invInputs[7], v_arith_decode_invInputs[9], io_inst[14], v_arith_decode_invInputs[11], v_arith_decode_invInputs[12], v_arith_decode_invInputs[13], v_arith_decode_invInputs[14], v_arith_decode_invInputs[15]},
     &{io_inst[26], io_inst[27], io_inst[28], v_arith_decode_invInputs[5], io_inst[30], v_arith_decode_invInputs[7], v_arith_decode_invInputs[9], io_inst[14]},
     &{io_vconfig_vtype_vsew[0], io_inst[26], io_inst[29], io_inst[30], v_arith_decode_invInputs[7], v_arith_decode_invInputs[9], io_inst[14]},
     &{io_vconfig_vtype_vsew[1], io_inst[26], io_inst[29], io_inst[30], v_arith_decode_invInputs[7], v_arith_decode_invInputs[9], io_inst[14]},
     &{io_vconfig_vtype_vsew[0], v_arith_decode_invInputs[3], v_arith_decode_invInputs[4], v_arith_decode_invInputs[6], io_inst[31], v_arith_decode_invInputs[9], io_inst[14]},
     &{io_vconfig_vtype_vsew[1], v_arith_decode_invInputs[3], v_arith_decode_invInputs[4], v_arith_decode_invInputs[6], io_inst[31], v_arith_decode_invInputs[9], io_inst[14]},
     &{io_vconfig_vtype_vsew[0], v_arith_decode_invInputs[1], io_inst[26], io_inst[27], io_inst[28], v_arith_decode_invInputs[6], io_inst[31], v_arith_decode_invInputs[9], io_inst[14]},
     &{io_vconfig_vtype_vsew[1], io_inst[26], io_inst[27], io_inst[28], v_arith_decode_invInputs[5], v_arith_decode_invInputs[6], io_inst[31], v_arith_decode_invInputs[9], io_inst[14]},
     &{v_arith_decode_invInputs[2], v_arith_decode_invInputs[3], io_inst[28], io_inst[30], v_arith_decode_invInputs[7], v_arith_decode_invInputs[8], v_arith_decode_invInputs[10], io_inst[15], v_arith_decode_invInputs[17], v_arith_decode_invInputs[18], v_arith_decode_invInputs[19]},
     &{v_arith_decode_invInputs[2], v_arith_decode_invInputs[3], io_inst[28], io_inst[30], v_arith_decode_invInputs[7], v_arith_decode_invInputs[8], v_arith_decode_invInputs[10], io_inst[16], v_arith_decode_invInputs[18], v_arith_decode_invInputs[19], v_arith_decode_invInputs[20]},
     &{io_vconfig_vtype_vsew[0], io_inst[27], v_arith_decode_invInputs[4], v_arith_decode_invInputs[5], io_inst[30], v_arith_decode_invInputs[7], v_arith_decode_invInputs[9], v_arith_decode_invInputs[10], v_arith_decode_invInputs[17], io_inst[17], v_arith_decode_invInputs[19], v_arith_decode_invInputs[20]},
     &{io_vconfig_vtype_vsew[1], io_inst[27], v_arith_decode_invInputs[4], v_arith_decode_invInputs[5], io_inst[30], v_arith_decode_invInputs[7], v_arith_decode_invInputs[9], v_arith_decode_invInputs[10], v_arith_decode_invInputs[17], io_inst[17], v_arith_decode_invInputs[19], v_arith_decode_invInputs[20]},
     &{v_arith_decode_invInputs[0], v_arith_decode_invInputs[2], io_inst[27], v_arith_decode_invInputs[4], v_arith_decode_invInputs[5], io_inst[30], v_arith_decode_invInputs[7], v_arith_decode_invInputs[9], v_arith_decode_invInputs[10], io_inst[18], v_arith_decode_invInputs[20]},
     &{v_arith_decode_invInputs[2], v_arith_decode_invInputs[3], io_inst[30], v_arith_decode_invInputs[7], v_arith_decode_invInputs[8], v_arith_decode_invInputs[10], v_arith_decode_invInputs[17], v_arith_decode_invInputs[18], v_arith_decode_invInputs[19], io_inst[19]}};	// @[src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:{53,70}, :114:19]
  wire        v_arith = v_arith_maybe & (|_v_arith_decode_orMatrixOutputs_T);	// @[generators/saturn/src/main/scala/frontend/EarlyDecode.scala:37:44, :38:31, src/main/scala/chisel3/util/pla.scala:114:{19,36}]
  wire        _io_vector_T = v_load | v_store;	// @[generators/saturn/src/main/scala/frontend/EarlyDecode.scala:35:35, :36:37, :40:23]
  wire        unit = io_inst[27:26] == 2'h0;	// @[generators/rocket-chip/src/main/scala/util/package.scala:17:47, generators/saturn/src/main/scala/frontend/EarlyDecode.scala:27:20, :43:20]
  wire        _whole_T_2 = io_inst[24:20] == 5'h8;	// @[generators/saturn/src/main/scala/frontend/EarlyDecode.scala:24:22, :44:43]
  wire        _GEN = io_inst[24:20] == 5'h0 | _whole_T_2 | io_inst[24:20] == 5'hB;	// @[generators/rocket-chip/src/main/scala/util/package.scala:17:47, :82:59, generators/saturn/src/main/scala/frontend/EarlyDecode.scala:24:22, :44:43]
  wire        io_fp_0 = ~_io_vector_T & v_arith & io_inst[14:12] == 3'h5;	// @[generators/saturn/src/main/scala/frontend/EarlyDecode.scala:17:16, :23:22, :38:31, :40:23, :42:28, :53:25, :56:{18,28}]
  assign io_vector = _io_vector_T | v_arith_maybe;	// @[generators/saturn/src/main/scala/frontend/EarlyDecode.scala:10:7, :37:44, :40:{23,34}]
  assign io_legal = _io_vector_T ? ~(io_inst[28] | unit & (v_store & ~_GEN | v_load & ~(_GEN | io_inst[24:20] == 5'h10))) & ~(io_inst[28]) & (io_inst[14:12] == 3'h0 | io_inst[14:12] == 3'h5 | io_inst[14:12] == 3'h6 | (&(io_inst[14:12]))) & (~io_vconfig_vtype_vill | unit & (v_load & _whole_T_2 | v_store & _whole_T_2)) : v_arith & ~io_vconfig_vtype_vill;	// @[generators/rocket-chip/src/main/scala/util/package.scala:17:47, :82:59, generators/saturn/src/main/scala/frontend/EarlyDecode.scala:10:7, :13:12, :23:22, :24:22, :28:20, :35:35, :36:37, :38:31, :40:23, :42:28, :43:20, :44:{22,34,43,59,71}, :45:{14,21,29,66,70,93}, :46:17, :47:{20,23,82,93}, :48:{21,24,74,85}, :50:{24,35}, :53:25, :54:{14,17}]
  assign io_fp = io_fp_0;	// @[generators/saturn/src/main/scala/frontend/EarlyDecode.scala:10:7, :17:16, :42:28, :53:25, :56:18]
  assign io_read_rs1 = _io_vector_T | v_arith & (io_inst[14:12] == 3'h4 | io_inst[14:12] == 3'h6);	// @[generators/rocket-chip/src/main/scala/util/package.scala:17:47, :82:59, generators/saturn/src/main/scala/frontend/EarlyDecode.scala:10:7, :15:15, :23:22, :38:31, :40:23, :42:28, :51:17, :53:25, :55:17]
  assign io_read_rs2 = _io_vector_T & io_inst[27:26] == 2'h2;	// @[generators/saturn/src/main/scala/frontend/EarlyDecode.scala:10:7, :16:15, :27:20, :40:23, :42:28, :52:{17,24}]
  assign io_read_frs1 = io_fp_0;	// @[generators/saturn/src/main/scala/frontend/EarlyDecode.scala:10:7, :17:16, :42:28, :53:25, :56:18]
  assign io_write_rd = ~_io_vector_T & v_arith & io_inst[14:12] == 3'h2 & io_inst[31:26] == 6'h10;	// @[generators/rocket-chip/src/main/scala/util/package.scala:17:47, generators/saturn/src/main/scala/frontend/EarlyDecode.scala:10:7, :17:16, :18:15, :23:22, :31:23, :38:31, :40:23, :42:28, :53:25, :57:{17,27,37,58}]
  assign io_write_frd = ~_io_vector_T & v_arith & io_inst[14:12] == 3'h1 & io_inst[31:26] == 6'h10;	// @[generators/rocket-chip/src/main/scala/util/package.scala:17:47, generators/saturn/src/main/scala/frontend/EarlyDecode.scala:10:7, :17:16, :19:16, :23:22, :31:23, :38:31, :40:23, :42:28, :53:25, :58:{18,28,38,59}]
endmodule

