// Generated by CIRCT firtool-1.75.0
module OldestRRArbiter_6(	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:10:7]
  input        clock,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:10:7]
  output       io_in_0_ready,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:11:14]
  input        io_in_0_valid,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:11:14]
  input  [5:0] io_in_0_bits_eg,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:11:14]
  input        io_in_0_bits_oldest,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:11:14]
  output       io_in_1_ready,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:11:14]
  input        io_in_1_valid,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:11:14]
  input  [5:0] io_in_1_bits_eg,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:11:14]
  input        io_in_1_bits_oldest,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:11:14]
  output       io_in_2_ready,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:11:14]
  input        io_in_2_valid,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:11:14]
  input  [5:0] io_in_2_bits_eg,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:11:14]
  input        io_in_2_bits_oldest,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:11:14]
  output       io_in_3_ready,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:11:14]
  input        io_in_3_valid,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:11:14]
  input  [5:0] io_in_3_bits_eg,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:11:14]
  input        io_in_3_bits_oldest,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:11:14]
  output       io_in_4_ready,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:11:14]
  input        io_in_4_valid,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:11:14]
  input  [5:0] io_in_4_bits_eg,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:11:14]
  input        io_out_ready,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:11:14]
  output [5:0] io_out_bits_eg	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:11:14]
);

  wire       _arb_io_in_0_ready;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:13:19]
  wire       _arb_io_in_1_ready;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:13:19]
  wire       _arb_io_in_2_ready;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:13:19]
  wire       _arb_io_in_3_ready;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:13:19]
  wire       _arb_io_in_4_ready;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:13:19]
  wire [5:0] _arb_io_out_bits_eg;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:13:19]
  wire       oldest_oh_0 = io_in_0_valid & io_in_0_bits_oldest;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:15:42]
  wire       oldest_oh_1 = io_in_1_valid & io_in_1_bits_oldest;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:15:42]
  wire       oldest_oh_2 = io_in_2_valid & io_in_2_bits_oldest;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:15:42]
  wire       oldest_oh_3 = io_in_3_valid & io_in_3_bits_oldest;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:15:42]
  wire       _GEN = oldest_oh_0 | oldest_oh_1 | oldest_oh_2 | oldest_oh_3;	// @[generators/rocket-chip/src/main/scala/util/package.scala:82:59, generators/saturn/src/main/scala/backend/RegisterFile.scala:15:42]
  RRArbiter_11 arb (	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:13:19]
    .clock           (clock),
    .io_in_0_ready   (_arb_io_in_0_ready),
    .io_in_0_valid   (io_in_0_valid),
    .io_in_0_bits_eg (io_in_0_bits_eg),
    .io_in_1_ready   (_arb_io_in_1_ready),
    .io_in_1_valid   (io_in_1_valid),
    .io_in_1_bits_eg (io_in_1_bits_eg),
    .io_in_2_ready   (_arb_io_in_2_ready),
    .io_in_2_valid   (io_in_2_valid),
    .io_in_2_bits_eg (io_in_2_bits_eg),
    .io_in_3_ready   (_arb_io_in_3_ready),
    .io_in_3_valid   (io_in_3_valid),
    .io_in_3_bits_eg (io_in_3_bits_eg),
    .io_in_4_ready   (_arb_io_in_4_ready),
    .io_in_4_valid   (io_in_4_valid),
    .io_in_4_bits_eg (io_in_4_bits_eg),
    .io_out_ready    (io_out_ready),
    .io_out_bits_eg  (_arb_io_out_bits_eg)
  );	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:13:19]
  assign io_in_0_ready = _GEN ? oldest_oh_0 & io_out_ready : _arb_io_in_0_ready;	// @[generators/rocket-chip/src/main/scala/util/package.scala:82:59, generators/saturn/src/main/scala/backend/RegisterFile.scala:10:7, :13:19, :14:6, :15:42, :16:24, :21:{22,38}]
  assign io_in_1_ready = _GEN ? oldest_oh_1 & io_out_ready : _arb_io_in_1_ready;	// @[generators/rocket-chip/src/main/scala/util/package.scala:82:59, generators/saturn/src/main/scala/backend/RegisterFile.scala:10:7, :13:19, :14:6, :15:42, :16:24, :21:{22,38}]
  assign io_in_2_ready = _GEN ? oldest_oh_2 & io_out_ready : _arb_io_in_2_ready;	// @[generators/rocket-chip/src/main/scala/util/package.scala:82:59, generators/saturn/src/main/scala/backend/RegisterFile.scala:10:7, :13:19, :14:6, :15:42, :16:24, :21:{22,38}]
  assign io_in_3_ready = _GEN ? oldest_oh_3 & io_out_ready : _arb_io_in_3_ready;	// @[generators/rocket-chip/src/main/scala/util/package.scala:82:59, generators/saturn/src/main/scala/backend/RegisterFile.scala:10:7, :13:19, :14:6, :15:42, :16:24, :21:{22,38}]
  assign io_in_4_ready = ~_GEN & _arb_io_in_4_ready;	// @[generators/rocket-chip/src/main/scala/util/package.scala:82:59, generators/saturn/src/main/scala/backend/RegisterFile.scala:10:7, :13:19, :14:6, :16:24, :21:22]
  assign io_out_bits_eg = _GEN ? (oldest_oh_0 ? io_in_0_bits_eg : 6'h0) | (oldest_oh_1 ? io_in_1_bits_eg : 6'h0) | (oldest_oh_2 ? io_in_2_bits_eg : 6'h0) | (oldest_oh_3 ? io_in_3_bits_eg : 6'h0) : _arb_io_out_bits_eg;	// @[generators/rocket-chip/src/main/scala/util/package.scala:82:59, generators/saturn/src/main/scala/backend/RegisterFile.scala:10:7, :13:19, :14:6, :15:42, :16:24, :19:17, src/main/scala/chisel3/util/Mux.scala:30:73]
endmodule

