// Generated by CIRCT firtool-1.75.0
module RegisterReadXbar(	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:26:7]
  input         clock,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:26:7]
  output        io_in_0_req_ready,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:27:14]
  input         io_in_0_req_valid,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:27:14]
  input  [5:0]  io_in_0_req_bits_eg,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:27:14]
  input         io_in_0_req_bits_oldest,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:27:14]
  output [63:0] io_in_0_resp,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:27:14]
  output        io_in_1_req_ready,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:27:14]
  input         io_in_1_req_valid,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:27:14]
  input  [5:0]  io_in_1_req_bits_eg,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:27:14]
  input         io_in_1_req_bits_oldest,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:27:14]
  output [63:0] io_in_1_resp,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:27:14]
  input         io_out_0_req_ready,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:27:14]
  output        io_out_0_req_valid,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:27:14]
  output [5:0]  io_out_0_req_bits_eg,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:27:14]
  input  [63:0] io_out_0_resp,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:27:14]
  input         io_out_1_req_ready,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:27:14]
  output        io_out_1_req_valid,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:27:14]
  output [5:0]  io_out_1_req_bits_eg,	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:27:14]
  input  [63:0] io_out_1_resp	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:27:14]
);

  wire       _arbs_1_io_in_0_ready;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:32:38]
  wire       _arbs_1_io_in_1_ready;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:32:38]
  wire       _arbs_0_io_in_0_ready;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:32:38]
  wire       _arbs_0_io_in_1_ready;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:32:38]
  wire [5:0] arbs_1_io_in_0_bits_eg = {1'h0, io_in_0_req_bits_eg[5:1]};	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:43:{32,56}]
  wire [5:0] arbs_1_io_in_1_bits_eg = {1'h0, io_in_1_req_bits_eg[5:1]};	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:43:{32,56}]
  OldestRRArbiter arbs_0 (	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:32:38]
    .clock               (clock),
    .io_in_0_ready       (_arbs_0_io_in_0_ready),
    .io_in_0_valid       (io_in_0_req_valid & ~(io_in_0_req_bits_eg[0])),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:40:82, :42:{52,63}]
    .io_in_0_bits_eg     (arbs_1_io_in_0_bits_eg),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:43:32]
    .io_in_0_bits_oldest (io_in_0_req_bits_oldest),
    .io_in_1_ready       (_arbs_0_io_in_1_ready),
    .io_in_1_valid       (io_in_1_req_valid & ~(io_in_1_req_bits_eg[0])),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:40:82, :42:{52,63}]
    .io_in_1_bits_eg     (arbs_1_io_in_1_bits_eg),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:43:32]
    .io_in_1_bits_oldest (io_in_1_req_bits_oldest),
    .io_out_ready        (io_out_0_req_ready),
    .io_out_valid        (io_out_0_req_valid),
    .io_out_bits_eg      (io_out_0_req_bits_eg)
  );	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:32:38]
  OldestRRArbiter arbs_1 (	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:32:38]
    .clock               (clock),
    .io_in_0_ready       (_arbs_1_io_in_0_ready),
    .io_in_0_valid       (io_in_0_req_valid & io_in_0_req_bits_eg[0]),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:40:82, :42:52]
    .io_in_0_bits_eg     (arbs_1_io_in_0_bits_eg),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:43:32]
    .io_in_0_bits_oldest (io_in_0_req_bits_oldest),
    .io_in_1_ready       (_arbs_1_io_in_1_ready),
    .io_in_1_valid       (io_in_1_req_valid & io_in_1_req_bits_eg[0]),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:40:82, :42:52]
    .io_in_1_bits_eg     (arbs_1_io_in_1_bits_eg),	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:43:32]
    .io_in_1_bits_oldest (io_in_1_req_bits_oldest),
    .io_out_ready        (io_out_1_req_ready),
    .io_out_valid        (io_out_1_req_valid),
    .io_out_bits_eg      (io_out_1_req_bits_eg)
  );	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:32:38]
  assign io_in_0_req_ready = ~(io_in_0_req_bits_eg[0]) & _arbs_0_io_in_0_ready | io_in_0_req_bits_eg[0] & _arbs_1_io_in_0_ready;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:26:7, :32:38, :40:82, :42:63, src/main/scala/chisel3/util/Mux.scala:30:73]
  assign io_in_0_resp = (io_in_0_req_bits_eg[0] ? 64'h0 : io_out_0_resp) | (io_in_0_req_bits_eg[0] ? io_out_1_resp : 64'h0);	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:26:7, :40:82, src/main/scala/chisel3/util/Mux.scala:30:73]
  assign io_in_1_req_ready = ~(io_in_1_req_bits_eg[0]) & _arbs_0_io_in_1_ready | io_in_1_req_bits_eg[0] & _arbs_1_io_in_1_ready;	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:26:7, :32:38, :40:82, :42:63, src/main/scala/chisel3/util/Mux.scala:30:73]
  assign io_in_1_resp = (io_in_1_req_bits_eg[0] ? 64'h0 : io_out_0_resp) | (io_in_1_req_bits_eg[0] ? io_out_1_resp : 64'h0);	// @[generators/saturn/src/main/scala/backend/RegisterFile.scala:26:7, :40:82, src/main/scala/chisel3/util/Mux.scala:30:73]
endmodule

