// Generated by CIRCT firtool-1.75.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module ShiftArray(	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:83:7]
  input         clock,	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:83:7]
  input  [1:0]  io_in_eew,	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:85:14]
  input  [63:0] io_in,	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:85:14]
  input  [63:0] io_shamt,	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:85:14]
  input         io_rori_hi,	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:85:14]
  input         io_rot,	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:85:14]
  input         io_shl,	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:85:14]
  input         io_signed,	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:85:14]
  input         io_scaling,	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:85:14]
  input  [1:0]  io_rm,	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:85:14]
  input         io_narrowing,	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:85:14]
  output [7:0]  io_out_0,	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:85:14]
  output [7:0]  io_out_1,	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:85:14]
  output [7:0]  io_out_2,	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:85:14]
  output [7:0]  io_out_3,	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:85:14]
  output [7:0]  io_out_4,	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:85:14]
  output [7:0]  io_out_5,	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:85:14]
  output [7:0]  io_out_6,	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:85:14]
  output [7:0]  io_out_7,	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:85:14]
  output [7:0]  io_set_vxsat	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:85:14]
);

  wire [7:0]       _scaling_array_io_out_0;	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:123:29]
  wire [7:0]       _scaling_array_io_out_1;	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:123:29]
  wire [7:0]       _scaling_array_io_out_2;	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:123:29]
  wire [7:0]       _scaling_array_io_out_3;	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:123:29]
  wire [7:0]       _scaling_array_io_out_4;	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:123:29]
  wire [7:0]       _scaling_array_io_out_5;	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:123:29]
  wire [7:0]       _scaling_array_io_out_6;	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:123:29]
  wire [7:0]       _scaling_array_io_out_7;	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:123:29]
  wire             _scaling_array_io_carry_1;	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:123:29]
  wire             _scaling_array_io_carry_3;	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:123:29]
  wire             _scaling_array_io_carry_5;	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:123:29]
  wire             _scaling_array_io_carry_7;	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:123:29]
  wire [63:0]      _shifter_io_out;	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:109:25]
  wire [7:0]       _shifter_io_round;	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:109:25]
  reg  [7:0]       shifted_0;	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:101:20]
  reg  [7:0]       shifted_1;	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:101:20]
  reg  [7:0]       shifted_2;	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:101:20]
  reg  [7:0]       shifted_3;	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:101:20]
  reg  [7:0]       shifted_4;	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:101:20]
  reg  [7:0]       shifted_5;	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:101:20]
  reg  [7:0]       shifted_6;	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:101:20]
  reg  [7:0]       shifted_7;	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:101:20]
  reg              rounding_incrs_0;	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:102:27]
  reg              rounding_incrs_1;	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:102:27]
  reg              rounding_incrs_2;	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:102:27]
  reg              rounding_incrs_3;	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:102:27]
  reg              rounding_incrs_4;	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:102:27]
  reg              rounding_incrs_5;	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:102:27]
  reg              rounding_incrs_6;	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:102:27]
  reg              rounding_incrs_7;	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:102:27]
  reg  [1:0]       in_eew_pipe;	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:103:28]
  reg              signed_pipe;	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:104:28]
  reg              scaling_pipe;	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:105:29]
  reg              narrowing_pipe;	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:106:31]
  wire [3:0]       _narrow_unsigned_mask_T_13 = {|{_scaling_array_io_carry_7, _scaling_array_io_out_7}, |{_scaling_array_io_carry_5, _scaling_array_io_out_5}, |{_scaling_array_io_carry_3, _scaling_array_io_out_3}, |{_scaling_array_io_carry_1, _scaling_array_io_out_1}};	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:123:29, :147:{10,63}, :148:7]
  wire [1:0]       _narrow_out_clipped_T_2 = in_eew_pipe - 2'h1;	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:103:28, :149:18]
  wire [7:0]       his_0 = {_scaling_array_io_out_1[6:0], _scaling_array_io_out_0[7]};	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:123:29, :154:{87,89,108}]
  wire [7:0]       his_1 = {_scaling_array_io_out_3[6:0], _scaling_array_io_out_2[7]};	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:123:29, :154:{87,89,108}]
  wire [7:0]       his_2 = {_scaling_array_io_out_5[6:0], _scaling_array_io_out_4[7]};	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:123:29, :154:{87,89,108}]
  wire [7:0]       his_3 = {_scaling_array_io_out_7[6:0], _scaling_array_io_out_6[7]};	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:123:29, :154:{87,89,108}]
  wire [31:0]      narrow_signed_clips_0 = {_scaling_array_io_out_7[7] ? 8'h80 : 8'h7F, _scaling_array_io_out_5[7] ? 8'h80 : 8'h7F, _scaling_array_io_out_3[7] ? 8'h80 : 8'h7F, _scaling_array_io_out_1[7] ? 8'h80 : 8'h7F};	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:123:29, :153:42, :159:{48,74}]
  wire [3:0]       narrow_signed_masks_0 = {_scaling_array_io_out_7[7] & his_3 != 8'hFF | ~(_scaling_array_io_out_7[7]) & (|his_3), _scaling_array_io_out_5[7] & his_2 != 8'hFF | ~(_scaling_array_io_out_5[7]) & (|his_2), _scaling_array_io_out_3[7] & his_1 != 8'hFF | ~(_scaling_array_io_out_3[7]) & (|his_1), _scaling_array_io_out_1[7] & his_0 != 8'hFF | ~(_scaling_array_io_out_1[7]) & (|his_0)};	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:123:29, :153:42, :154:87, :155:{59,64}, :156:{56,59,64}, :160:51, :161:21]
  wire [15:0]      his_0_1 = {_scaling_array_io_out_3[6:0], _scaling_array_io_out_2, _scaling_array_io_out_1[7]};	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:123:29, :154:{87,89,108}]
  wire [15:0]      his_1_1 = {_scaling_array_io_out_7[6:0], _scaling_array_io_out_6, _scaling_array_io_out_5[7]};	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:123:29, :154:{87,89,108}]
  wire [31:0]      his_0_2 = {_scaling_array_io_out_7[6:0], _scaling_array_io_out_6, _scaling_array_io_out_5, _scaling_array_io_out_4, _scaling_array_io_out_3[7]};	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:123:29, :154:{87,89,108}]
  wire [3:0][31:0] _GEN = {{narrow_signed_clips_0}, {_scaling_array_io_out_7[7] ? 32'h80000000 : 32'h7FFFFFFF}, {{_scaling_array_io_out_7[7] ? 16'h8000 : 16'h7FFF, _scaling_array_io_out_3[7] ? 16'h8000 : 16'h7FFF}}, {narrow_signed_clips_0}};	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:123:29, :153:42, :159:{48,74}, :164:84]
  wire [3:0][3:0]  _GEN_0 = {{narrow_signed_masks_0}, {{4{_scaling_array_io_out_7[7] & his_0_2 != 32'hFFFFFFFF | ~(_scaling_array_io_out_7[7]) & (|his_0_2)}}}, {{{2{_scaling_array_io_out_7[7] & his_1_1 != 16'hFFFF | ~(_scaling_array_io_out_7[7]) & (|his_1_1)}}, {2{_scaling_array_io_out_3[7] & his_0_1 != 16'hFFFF | ~(_scaling_array_io_out_3[7]) & (|his_0_1)}}}}, {narrow_signed_masks_0}};	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:123:29, :153:42, :154:87, :155:{59,64}, :156:{56,59,64}, :160:51, :161:21, :166:24]
  wire [3:0][3:0]  _GEN_1 = {{_narrow_unsigned_mask_T_13}, {{4{|{_scaling_array_io_carry_7, _scaling_array_io_out_7, _scaling_array_io_out_6, _scaling_array_io_out_5, _scaling_array_io_out_4}}}}, {{{2{|{_scaling_array_io_carry_7, _scaling_array_io_out_7, _scaling_array_io_out_6}}}, {2{|{_scaling_array_io_carry_3, _scaling_array_io_out_3, _scaling_array_io_out_2}}}}}, {_narrow_unsigned_mask_T_13}};	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:123:29, :146:20, :147:{10,63}, :148:7, :166:24]
  wire [3:0]       narrow_mask = signed_pipe ? _GEN_0[_narrow_out_clipped_T_2] : _GEN_1[_narrow_out_clipped_T_2];	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:104:28, :149:18, :166:24]
  wire [31:0]      _narrow_out_clipped_T = {_scaling_array_io_out_6, _scaling_array_io_out_4, _scaling_array_io_out_2, _scaling_array_io_out_0};	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:123:29, :169:73]
  wire [3:0][31:0] _GEN_2 = {{_narrow_out_clipped_T}, {{_scaling_array_io_out_3, _scaling_array_io_out_2, _scaling_array_io_out_1, _scaling_array_io_out_0}}, {{_scaling_array_io_out_5, _scaling_array_io_out_4, _scaling_array_io_out_1, _scaling_array_io_out_0}}, {_narrow_out_clipped_T}};	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:123:29, :136:79, :169:73, :170:14]
  wire [7:0]       narrow_out_clipped_0 = narrow_mask[0] & scaling_pipe ? (signed_pipe ? _GEN[_narrow_out_clipped_T_2][7:0] : 8'hFF) : _GEN_2[_narrow_out_clipped_T_2][7:0];	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:104:28, :105:29, :149:18, :164:84, :166:24, :167:24, :170:14, :171:22, :172:{51,54}]
  wire [7:0]       narrow_out_clipped_1 = narrow_mask[1] & scaling_pipe ? (signed_pipe ? _GEN[_narrow_out_clipped_T_2][15:8] : 8'hFF) : _GEN_2[_narrow_out_clipped_T_2][15:8];	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:104:28, :105:29, :149:18, :164:84, :166:24, :167:24, :170:14, :171:22, :172:{51,54}]
  wire [7:0]       narrow_out_clipped_2 = narrow_mask[2] & scaling_pipe ? (signed_pipe ? _GEN[_narrow_out_clipped_T_2][23:16] : 8'hFF) : _GEN_2[_narrow_out_clipped_T_2][23:16];	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:104:28, :105:29, :149:18, :164:84, :166:24, :167:24, :170:14, :171:22, :172:{51,54}]
  wire [7:0]       narrow_out_clipped_3 = narrow_mask[3] & scaling_pipe ? (signed_pipe ? _GEN[_narrow_out_clipped_T_2][31:24] : 8'hFF) : _GEN_2[_narrow_out_clipped_T_2][31:24];	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:104:28, :105:29, :149:18, :164:84, :166:24, :167:24, :170:14, :171:22, :172:{51,54}]
  always @(posedge clock) begin	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:83:7]
    shifted_0 <= _shifter_io_out[7:0];	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:101:20, :109:25, :118:39]
    shifted_1 <= _shifter_io_out[15:8];	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:101:20, :109:25, :118:39]
    shifted_2 <= _shifter_io_out[23:16];	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:101:20, :109:25, :118:39]
    shifted_3 <= _shifter_io_out[31:24];	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:101:20, :109:25, :118:39]
    shifted_4 <= _shifter_io_out[39:32];	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:101:20, :109:25, :118:39]
    shifted_5 <= _shifter_io_out[47:40];	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:101:20, :109:25, :118:39]
    shifted_6 <= _shifter_io_out[55:48];	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:101:20, :109:25, :118:39]
    shifted_7 <= _shifter_io_out[63:56];	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:101:20, :109:25, :118:39]
    rounding_incrs_0 <= _shifter_io_round[0];	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:102:27, :109:25, :119:48]
    rounding_incrs_1 <= _shifter_io_round[1];	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:102:27, :109:25, :119:48]
    rounding_incrs_2 <= _shifter_io_round[2];	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:102:27, :109:25, :119:48]
    rounding_incrs_3 <= _shifter_io_round[3];	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:102:27, :109:25, :119:48]
    rounding_incrs_4 <= _shifter_io_round[4];	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:102:27, :109:25, :119:48]
    rounding_incrs_5 <= _shifter_io_round[5];	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:102:27, :109:25, :119:48]
    rounding_incrs_6 <= _shifter_io_round[6];	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:102:27, :109:25, :119:48]
    rounding_incrs_7 <= _shifter_io_round[7];	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:102:27, :109:25, :119:48]
    in_eew_pipe <= io_in_eew;	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:103:28]
    signed_pipe <= io_signed;	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:104:28]
    scaling_pipe <= io_scaling;	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:105:29]
    narrowing_pipe <= io_narrowing;	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:106:31]
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:83:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:83:7]
      `FIRRTL_BEFORE_INITIAL	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:83:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:2];	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:83:7]
    initial begin	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:83:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:83:7]
        `INIT_RANDOM_PROLOG_	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:83:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:83:7]
        for (logic [1:0] i = 2'h0; i < 2'h3; i += 2'h1) begin
          _RANDOM[i] = `RANDOM;	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:83:7]
        end	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:83:7]
        shifted_0 = _RANDOM[2'h0][7:0];	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:83:7, :101:20]
        shifted_1 = _RANDOM[2'h0][15:8];	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:83:7, :101:20]
        shifted_2 = _RANDOM[2'h0][23:16];	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:83:7, :101:20]
        shifted_3 = _RANDOM[2'h0][31:24];	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:83:7, :101:20]
        shifted_4 = _RANDOM[2'h1][7:0];	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:83:7, :101:20]
        shifted_5 = _RANDOM[2'h1][15:8];	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:83:7, :101:20]
        shifted_6 = _RANDOM[2'h1][23:16];	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:83:7, :101:20]
        shifted_7 = _RANDOM[2'h1][31:24];	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:83:7, :101:20]
        rounding_incrs_0 = _RANDOM[2'h2][0];	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:83:7, :102:27]
        rounding_incrs_1 = _RANDOM[2'h2][1];	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:83:7, :102:27]
        rounding_incrs_2 = _RANDOM[2'h2][2];	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:83:7, :102:27]
        rounding_incrs_3 = _RANDOM[2'h2][3];	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:83:7, :102:27]
        rounding_incrs_4 = _RANDOM[2'h2][4];	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:83:7, :102:27]
        rounding_incrs_5 = _RANDOM[2'h2][5];	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:83:7, :102:27]
        rounding_incrs_6 = _RANDOM[2'h2][6];	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:83:7, :102:27]
        rounding_incrs_7 = _RANDOM[2'h2][7];	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:83:7, :102:27]
        in_eew_pipe = _RANDOM[2'h2][9:8];	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:83:7, :102:27, :103:28]
        signed_pipe = _RANDOM[2'h2][10];	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:83:7, :102:27, :104:28]
        scaling_pipe = _RANDOM[2'h2][11];	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:83:7, :102:27, :105:29]
        narrowing_pipe = _RANDOM[2'h2][12];	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:83:7, :102:27, :106:31]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:83:7]
      `FIRRTL_AFTER_INITIAL	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:83:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  ShiftUnit shifter (	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:109:25]
    .io_in_eew (io_in_eew),
    .io_in     (io_in),
    .io_shamt  ({io_shamt[63:6], io_shamt[5:0] | {io_rori_hi, 5'h0}}),	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:112:{51,56}]
    .io_rot    (io_rot),
    .io_shl    (io_shl),
    .io_signed (io_signed),
    .io_rm     (io_rm),
    .io_out    (_shifter_io_out),
    .io_round  (_shifter_io_round)
  );	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:109:25]
  AdderArray scaling_array (	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:123:29]
    .io_in1_0      (shifted_0),	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:101:20]
    .io_in1_1      (shifted_1),	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:101:20]
    .io_in1_2      (shifted_2),	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:101:20]
    .io_in1_3      (shifted_3),	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:101:20]
    .io_in1_4      (shifted_4),	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:101:20]
    .io_in1_5      (shifted_5),	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:101:20]
    .io_in1_6      (shifted_6),	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:101:20]
    .io_in1_7      (shifted_7),	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:101:20]
    .io_in2_0      (8'h0),
    .io_in2_1      (8'h0),
    .io_in2_2      (8'h0),
    .io_in2_3      (8'h0),
    .io_in2_4      (8'h0),
    .io_in2_5      (8'h0),
    .io_in2_6      (8'h0),
    .io_in2_7      (8'h0),
    .io_incr_0     (scaling_pipe & rounding_incrs_0),	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:102:27, :105:29, :126:33]
    .io_incr_1     (scaling_pipe & rounding_incrs_1),	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:102:27, :105:29, :126:33]
    .io_incr_2     (scaling_pipe & rounding_incrs_2),	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:102:27, :105:29, :126:33]
    .io_incr_3     (scaling_pipe & rounding_incrs_3),	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:102:27, :105:29, :126:33]
    .io_incr_4     (scaling_pipe & rounding_incrs_4),	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:102:27, :105:29, :126:33]
    .io_incr_5     (scaling_pipe & rounding_incrs_5),	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:102:27, :105:29, :126:33]
    .io_incr_6     (scaling_pipe & rounding_incrs_6),	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:102:27, :105:29, :126:33]
    .io_incr_7     (scaling_pipe & rounding_incrs_7),	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:102:27, :105:29, :126:33]
    .io_mask_carry (8'h0),
    .io_signed     (1'h0),
    .io_eew        (in_eew_pipe),	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:103:28]
    .io_avg        (1'h0),
    .io_rm         (2'h0),	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:83:7]
    .io_sub        (1'h0),
    .io_cmask      (1'h0),
    .io_out_0      (_scaling_array_io_out_0),
    .io_out_1      (_scaling_array_io_out_1),
    .io_out_2      (_scaling_array_io_out_2),
    .io_out_3      (_scaling_array_io_out_3),
    .io_out_4      (_scaling_array_io_out_4),
    .io_out_5      (_scaling_array_io_out_5),
    .io_out_6      (_scaling_array_io_out_6),
    .io_out_7      (_scaling_array_io_out_7),
    .io_carry_0    (/* unused */),
    .io_carry_1    (_scaling_array_io_carry_1),
    .io_carry_2    (/* unused */),
    .io_carry_3    (_scaling_array_io_carry_3),
    .io_carry_4    (/* unused */),
    .io_carry_5    (_scaling_array_io_carry_5),
    .io_carry_6    (/* unused */),
    .io_carry_7    (_scaling_array_io_carry_7)
  );	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:123:29]
  assign io_out_0 = narrowing_pipe ? narrow_out_clipped_0 : _scaling_array_io_out_0;	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:83:7, :106:31, :123:29, :172:51, :175:16]
  assign io_out_1 = narrowing_pipe ? narrow_out_clipped_1 : _scaling_array_io_out_1;	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:83:7, :106:31, :123:29, :172:51, :175:16]
  assign io_out_2 = narrowing_pipe ? narrow_out_clipped_2 : _scaling_array_io_out_2;	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:83:7, :106:31, :123:29, :172:51, :175:16]
  assign io_out_3 = narrowing_pipe ? narrow_out_clipped_3 : _scaling_array_io_out_3;	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:83:7, :106:31, :123:29, :172:51, :175:16]
  assign io_out_4 = narrowing_pipe ? narrow_out_clipped_0 : _scaling_array_io_out_4;	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:83:7, :106:31, :123:29, :172:51, :175:16]
  assign io_out_5 = narrowing_pipe ? narrow_out_clipped_1 : _scaling_array_io_out_5;	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:83:7, :106:31, :123:29, :172:51, :175:16]
  assign io_out_6 = narrowing_pipe ? narrow_out_clipped_2 : _scaling_array_io_out_6;	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:83:7, :106:31, :123:29, :172:51, :175:16]
  assign io_out_7 = narrowing_pipe ? narrow_out_clipped_3 : _scaling_array_io_out_7;	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:83:7, :106:31, :123:29, :172:51, :175:16]
  assign io_set_vxsat = narrowing_pipe & scaling_pipe ? {2{narrow_mask}} : 8'h0;	// @[generators/saturn/src/main/scala/exu/int/ShiftPipe.scala:83:7, :105:29, :106:31, :166:24, :176:{22,38,59}]
endmodule

