###############################################################################

###############################################################################
# Board clock and reset
###############################################################################

create_clock -period 40.000 [get_ports clk_25m]

set_property IOSTANDARD LVCMOS18 [get_ports clk_25m]
set_property PACKAGE_PIN AM33 [get_ports clk_25m]

set_property IOSTANDARD LVCMOS18 [get_ports sys_rstn]
set_property PACKAGE_PIN AM24 [get_ports sys_rstn]

# set_property IOSTANDARD LVCMOS18 [get_ports conf_done1]
# set_property IOSTANDARD LVCMOS18 [get_ports conf_done2]
set_property IOSTANDARD LVCMOS18 [get_ports si5338_scl1]
set_property IOSTANDARD LVCMOS18 [get_ports si5338_scl2]
set_property IOSTANDARD LVCMOS18 [get_ports si5338_sda1]
set_property IOSTANDARD LVCMOS18 [get_ports si5338_sda2]

# set_property PACKAGE_PIN AL24 [get_ports conf_done1]
# set_property PACKAGE_PIN AL21 [get_ports conf_done2]
set_property PACKAGE_PIN AP38 [get_ports si5338_scl1]
set_property PACKAGE_PIN AT35 [get_ports si5338_scl2]
set_property PACKAGE_PIN AR38 [get_ports si5338_sda1]
set_property PACKAGE_PIN AT36 [get_ports si5338_sda2]

create_clock -period 10.000 -name clk_100m_p [get_ports clk_100m_p]

# P3 camera-video clock is generated by a dedicated BUFGCE_DIV from the MIG
# UI clock. Give it a stable name and preserve the real 2:1 relationship;
# do not declare the complete 300/150 MHz domains asynchronous.
create_generated_clock -name camera_video_clk -divide_by 2 \
    -source [get_pins u_ddr_memory/u_camera_video_clk_div/I] \
    [get_pins u_ddr_memory/u_camera_video_clk_div/O]

# Chipyard exposes its RISC-V JTAG TAP through Xilinx USER4 BSCAN.  The
# generated JTAGTUNNEL contains state and edge counters clocked directly from
# BSCANE2/INTERNAL_TCK, followed by a BUFGCE for the inner TAP.  Without a
# clock on this root Vivado leaves the complete tunnel untimed; a harmless
# full-design reroute can then create same-edge SHIFT-to-counter hold failures
# and corrupt DTMCS scans.  OpenOCD normally runs this tunnel at 15 MHz.
create_clock -name rocket_bscan_tck -period 66.667 \
    -waveform {0.000 33.333} \
    [get_pins -hierarchical -filter \
        {NAME =~ */inst_jtag_tunnel/bscane2/INTERNAL_TCK}]

# The Rocket debug transport crosses between JTAG TCK and the 100 MHz SoC
# clock through generated asynchronous queues and reset synchronizers.  Keep
# those CDC paths asynchronous while fully timing every path contained inside
# the BSCAN/JTAG domain itself.  Include clocks derived from clk_100m_p so the
# constraint remains correct if the SoC clock is divided again later.  Keep
# this as a direct XDC command: Vivado does not support Tcl "if" in XDC files.
set_clock_groups -asynchronous \
    -group [get_clocks -include_generated_clocks clk_100m_p] \
    -group [get_clocks -include_generated_clocks rocket_bscan_tck]

set_property PACKAGE_PIN AY24 [get_ports clk_100m_p]
set_property PACKAGE_PIN AY23 [get_ports clk_100m_n]
set_property IOSTANDARD LVDS [get_ports clk_100m_p]
set_property IOSTANDARD LVDS [get_ports clk_100m_n]

# Rocket UART, 115200 baud at the 100 MHz SoC clock.
set_property PACKAGE_PIN AJ31 [get_ports uart_rxd]
set_property PACKAGE_PIN AL31 [get_ports uart_txd]
set_property IOSTANDARD LVCMOS18 [get_ports {uart_rxd uart_txd}]

 # DDR calibration status crosses asynchronously into the 100 MHz SoC domain.
set_false_path -to [get_pins {u_control_soc/ddr_calib_sync_reg[0]/D}]

set_false_path -to [get_pins -hierarchical -filter \
    {NAME =~ */u_video_framebuffer/u_control/ack_sync_1_reg/D}]

# DDR UI reset is an asynchronous-assert/synchronous-release reset generated
# by ddr_reset_sync. The synchronizer clock and recovery/removal checks remain
# constrained; the old Q-origin exception was not a valid timing startpoint in
# this netlist and caused a misleading XDC critical warning.

# MIG calibration asserts the reset synchronizer asynchronously. The CLR pin
# intentionally has no recovery requirement against the calibration clock.
set_false_path -to [get_pins {u_ddr_memory/ddr_reset_sync_reg[0]/CLR}]
set_false_path -to [get_pins {u_ddr_memory/video_reset_sync_reg[0]/CLR}]

# The functional oversampling receiver treats every DVP signal, including
# PCLK, as asynchronous data into a 300 MHz IOB register.  Only the pad to the
# first IOB stage is excluded; all IOB-to-second-stage and 300 MHz functional
# paths remain fully timed.
set_false_path -to [get_pins -hierarchical -filter \
    {NAME =~ *dvp_data_iob_reg*/D || \
     NAME =~ *dvp_href_iob_reg/D || \
     NAME =~ *dvp_vsync_iob_reg/D || \
     NAME =~ *dvp_pclk_iob_reg/D}]

# The second sampling stage must remain physically close to the input IOB.
# This datapath-only budget expresses that requirement without hard-locking a
# complete SLR pblock; the following aligned pipe stage is free to absorb the
# SLR crossing selected by the placer.
set dvp_iob_cells [get_cells -hierarchical -filter \
    {NAME =~ *dvp_data_iob_reg* || \
     NAME =~ *dvp_href_iob_reg || \
     NAME =~ *dvp_vsync_iob_reg || \
     NAME =~ *dvp_pclk_iob_reg}]
set dvp_sync_cells [get_cells -hierarchical -filter \
    {NAME =~ *dvp_data_sync_reg* || \
     NAME =~ *dvp_href_sync_reg || \
     NAME =~ *dvp_vsync_sync_reg || \
     NAME =~ *dvp_pclk_sync_reg}]
set_max_delay 1.500 -datapath_only \
    -from $dvp_iob_cells -to $dvp_sync_cells

# The eight FMC camera inputs sit in two SLRs.  USER_SLR_ASSIGNMENT applies
# only to hierarchical cells and is ignored on these leaf registers, so use
# leaf-capable pblocks for the short, aligned crossing pipeline:
#   CH1..4: IOB(SLR3) -> sync(SLR3) -> pipe(SLR2) -> recovery(SLR1)
#   CH5..8: IOB(SLR2) -> sync(SLR2) -> pipe(SLR1) -> recovery(SLR1)
# Guide the placer toward a local metastability-catching aperture and at most
# one following SLR hop, while leaving it free to violate the regions when a
# hard assignment would degrade overall timing.
create_pblock pblock_dvp_sync_slr3
resize_pblock [get_pblocks pblock_dvp_sync_slr3] -add SLR3
set_property IS_SOFT true [get_pblocks pblock_dvp_sync_slr3]
add_cells_to_pblock [get_pblocks pblock_dvp_sync_slr3] \
    [get_cells -hierarchical -regexp \
        {.*g_camera_frontend\[[0-3]\]\.u_camera/dvp_(data|href|vsync|pclk)_sync_reg.*}]

create_pblock pblock_dvp_bridge_slr2
resize_pblock [get_pblocks pblock_dvp_bridge_slr2] -add SLR2
set_property IS_SOFT true [get_pblocks pblock_dvp_bridge_slr2]
add_cells_to_pblock [get_pblocks pblock_dvp_bridge_slr2] \
    [get_cells -hierarchical -regexp \
        {.*g_camera_frontend\[[0-3]\]\.u_camera/dvp_(data|href|vsync|pclk)_pipe_reg.*|.*g_camera_frontend\[[4-7]\]\.u_camera/dvp_(data|href|vsync|pclk)_sync_reg.*}]

create_pblock pblock_dvp_pipe_slr1
resize_pblock [get_pblocks pblock_dvp_pipe_slr1] -add SLR1
set_property IS_SOFT true [get_pblocks pblock_dvp_pipe_slr1]
add_cells_to_pblock [get_pblocks pblock_dvp_pipe_slr1] \
    [get_cells -hierarchical -regexp \
        {.*g_camera_frontend\[[4-7]\]\.u_camera/dvp_(data|href|vsync|pclk)_pipe_reg.*}]

# The raw DVP and output-pad probes are sampled through explicit two-stage
# synchronizers in the 100 MHz diagnostic domain.  Time only the second stage;
# the asynchronous source-to-first-stage arcs are CDC paths by construction.
set_false_path -to [get_pins -hierarchical -filter \
    {NAME =~ *sample_sync_1_reg*/D}]
set_false_path -to [get_pins -hierarchical -filter \
    {NAME =~ *pad_sync_1_reg*/D}]

# Camera control and diagnostic requests cross into the 300 MHz capture domain
# through explicit two-stage synchronizers.  Only their first-stage D pins are
# asynchronous; the second stage remains normally timed so placement still
# maximizes synchronizer resolution time.  Keep these endpoint-specific rather
# than declaring the complete 24/100/300 MHz clock domains asynchronous.
set_false_path -to [get_pins -hierarchical -filter \
    {NAME =~ */capture_enable_sync1_reg/D || \
     NAME =~ */recovery_sample_offset_sync1_reg*/D || \
     NAME =~ */diag_clear_video_sync1_reg/D || \
     NAME =~ */stats_snapshot_video_sync1_reg/D || \
     NAME =~ *u_camera_cdc/diag_clear_sync1_reg/D || \
     NAME =~ *u_camera_stream/diag_clear_sync1_reg/D}]

# Each OV7670 frontend publishes a 32-bit geometry snapshot together with a
# toggle. The source values change only once per completed frame and remain
# stable while the toggle passes through two AXI-clock synchronizer stages;
# the destination waits one additional AXI clock before consuming the bus.
# Suppress the meaningless asynchronous clock-phase setup/hold checks only at
# each first-stage synchronizer. ASYNC_REG placement keeps both stages local;
# the frame-long source stability and delayed toggle capture provide the
# bundled-data settling interval.
set_false_path \
    -to [get_pins -hierarchical -filter \
        {NAME =~ */geometry_data_sync1_reg*/D || \
         NAME =~ */geometry_toggle_sync1_reg/D}]

# The framebuffer control interface uses a bundled-data request/acknowledge
# CDC. Configuration registers are held unchanged while cfg_request_toggle
# differs from the returned acknowledgement.  The request passes through two
# UI-clock synchronizer stages, so keep an explicit 10 ns propagation budget
# for the bundled data rather than applying the unrelated 100 MHz to 300 MHz
# setup relationship.
set_false_path -to [get_pins -hierarchical -filter \
    {NAME =~ */u_video_framebuffer/u_manager/cfg_sync_1_reg/D}]
set_false_path -to [get_pins -hierarchical -filter \
    {NAME =~ */u_video_framebuffer/u_manager/select_sync_1_reg*/D || \
     NAME =~ */u_video_framebuffer/u_manager/mode_sync_1_reg/D}]
# Constrain only paths launched by the 100 MHz bundled configuration source
# and captured by the active configuration registers.  Some validation terms
# are implemented on FDRE R/S/CE pins rather than D, so naming only D pins
# leaves false inter-clock setup checks behind.  The source-qualified cell
# endpoints cover every implementation choice without excluding any ordinary
# 300 MHz path within the frame manager.
set_false_path \
    -from [get_clocks clk_100m_p] \
    -to [get_pins -hierarchical -regexp \
        {.*u_video_framebuffer/u_manager/active_(width|height|stride_bytes|buffer_count|slot_mask|slot_bases)_reg.*/(D|R|S|CE)}]

# OV7670 controller diagnostics are asynchronous snapshots transferred by
# u_ctrl_diag_cdc into the AXI-Lite clock domain. Physical optimization may
# replicate and rename the XPM stages, so constrain the source clock and the
# diagnostic readback endpoints instead of depending on generated cell names.
set_false_path \
    -from [get_clocks -of_objects [get_pins \
        u_camera_hdmi/u_camera_subsystem/u_camera_clocking/u_ov7670_clk_wiz/inst/mmcme4_adv_inst/CLKOUT0]] \
    -to [get_pins -hierarchical -filter \
        {NAME =~ */u_diagnostics/rdata_reg*/D}]
