###############################################################################

###############################################################################
# Board clock and reset
###############################################################################

create_clock -period 40.000 [get_ports clk_25m]

set_property IOSTANDARD LVCMOS18 [get_ports clk_25m]
set_property PACKAGE_PIN AM33 [get_ports clk_25m]

set_property IOSTANDARD LVCMOS18 [get_ports sys_rstn]
set_property PACKAGE_PIN AM24 [get_ports sys_rstn]

# set_property IOSTANDARD LVCMOS18 [get_ports conf_done1]
# set_property IOSTANDARD LVCMOS18 [get_ports conf_done2]
set_property IOSTANDARD LVCMOS18 [get_ports si5338_scl1]
set_property IOSTANDARD LVCMOS18 [get_ports si5338_scl2]
set_property IOSTANDARD LVCMOS18 [get_ports si5338_sda1]
set_property IOSTANDARD LVCMOS18 [get_ports si5338_sda2]

# set_property PACKAGE_PIN AL24 [get_ports conf_done1]
# set_property PACKAGE_PIN AL21 [get_ports conf_done2]
set_property PACKAGE_PIN AP38 [get_ports si5338_scl1]
set_property PACKAGE_PIN AT35 [get_ports si5338_scl2]
set_property PACKAGE_PIN AR38 [get_ports si5338_sda1]
set_property PACKAGE_PIN AT36 [get_ports si5338_sda2]

create_clock -period 10.000 -name clk_100m_p [get_ports clk_100m_p]

# P3 camera-video clock is generated by a dedicated BUFGCE_DIV from the MIG
# UI clock. Give it a stable name and preserve the real 2:1 relationship;
# do not declare the complete 300/150 MHz domains asynchronous.
create_generated_clock -name camera_video_clk -divide_by 2 \
    -source [get_pins u_ddr_memory/u_ddr_platform/u_camera_video_clk_div/I] \
    [get_pins u_ddr_memory/u_ddr_platform/u_camera_video_clk_div/O]

# Chipyard exposes its RISC-V JTAG TAP through Xilinx USER4 BSCAN.  The
# generated JTAGTUNNEL contains state and edge counters clocked directly from
# BSCANE2/INTERNAL_TCK, followed by a BUFGCE for the inner TAP.  Without a
# clock on this root Vivado leaves the complete tunnel untimed; a harmless
# full-design reroute can then create same-edge SHIFT-to-counter hold failures
# and corrupt DTMCS scans.  OpenOCD normally runs this tunnel at 15 MHz.
create_clock -name rocket_bscan_tck -period 66.667 \
    -waveform {0.000 33.333} \
    [get_pins -hierarchical -filter \
        {NAME =~ */inst_jtag_tunnel/bscane2/INTERNAL_TCK}]

# The Rocket debug transport crosses between JTAG TCK and the 100 MHz SoC
# clock through generated asynchronous queues and reset synchronizers.  Keep
# those CDC paths asynchronous while fully timing every path contained inside
# the BSCAN/JTAG domain itself.  Include clocks derived from clk_100m_p so the
# constraint remains correct if the SoC clock is divided again later.  Keep
# this as a direct XDC command: Vivado does not support Tcl "if" in XDC files.
set_clock_groups -asynchronous \
    -group [get_clocks -include_generated_clocks clk_100m_p] \
    -group [get_clocks -include_generated_clocks rocket_bscan_tck]

set_property PACKAGE_PIN AY24 [get_ports clk_100m_p]
set_property PACKAGE_PIN AY23 [get_ports clk_100m_n]
set_property IOSTANDARD LVDS [get_ports clk_100m_p]
set_property IOSTANDARD LVDS [get_ports clk_100m_n]

# Rocket UART, 115200 baud at the 100 MHz SoC clock.
set_property PACKAGE_PIN AJ31 [get_ports uart_rxd]
set_property PACKAGE_PIN AL31 [get_ports uart_txd]
set_property IOSTANDARD LVCMOS18 [get_ports {uart_rxd uart_txd}]

 # DDR calibration status crosses asynchronously into the 100 MHz SoC domain.
set_false_path -to [get_pins {u_control_soc/ddr_calib_sync_reg[0]/D}]

set_false_path -to [get_pins -hierarchical -filter \
    {NAME =~ u_video_pipeline/u_control_bridge/u_control/u_frame_csr/ack_sync_1_reg/D}]

# DDR UI reset is an asynchronous-assert/synchronous-release reset generated
# by ddr_reset_sync. The synchronizer clock and recovery/removal checks remain
# constrained; the old Q-origin exception was not a valid timing startpoint in
# this netlist and caused a misleading XDC critical warning.

# MIG calibration asserts the reset synchronizer asynchronously. The CLR pin
# intentionally has no recovery requirement against the calibration clock.
set_false_path -to [get_pins \
    {u_ddr_memory/u_ddr_platform/ddr_reset_sync_reg[0]/CLR}]
set_false_path -to [get_pins \
    {u_ddr_memory/u_ddr_platform/video_reset_sync_reg[0]/CLR}]

# The functional oversampling receiver treats every DVP signal, including
# PCLK, as asynchronous data into a 300 MHz IOB register.  Only the pad to the
# first IOB stage is excluded; all IOB-to-second-stage and 300 MHz functional
# paths remain fully timed.
set_false_path -to [get_pins -hierarchical -filter \
    {NAME =~ *dvp_data_iob_reg*/D || \
     NAME =~ *dvp_href_iob_reg/D || \
     NAME =~ *dvp_vsync_iob_reg/D || \
     NAME =~ *dvp_pclk_iob_reg/D}]

# The second sampling stage must remain physically close to the input IOB.
# This datapath-only budget expresses that requirement without hard-locking a
# complete SLR pblock; the following aligned pipe stage is free to absorb the
# SLR crossing selected by the placer.
set dvp_iob_cells [get_cells -hierarchical -filter \
    {NAME =~ *dvp_data_iob_reg* || \
     NAME =~ *dvp_href_iob_reg || \
     NAME =~ *dvp_vsync_iob_reg || \
     NAME =~ *dvp_pclk_iob_reg}]
set dvp_sync_cells [get_cells -hierarchical -filter \
    {NAME =~ *dvp_data_sync_reg* || \
     NAME =~ *dvp_href_sync_reg || \
     NAME =~ *dvp_vsync_sync_reg || \
     NAME =~ *dvp_pclk_sync_reg}]
set_max_delay 1.500 -datapath_only \
    -from $dvp_iob_cells -to $dvp_sync_cells

# The eight FMC camera inputs sit in two SLRs.  USER_SLR_ASSIGNMENT applies
# only to hierarchical cells and is ignored on these leaf registers, so use
# leaf-capable pblocks for the short, aligned crossing pipeline:
#   CH1..4: IOB(SLR3) -> sync(SLR3) -> pipe/recovery/event(SLR2)
#   CH5..8: IOB(SLR2) -> sync(SLR2) -> pipe(SLR1) -> recovery(SLR1)
# Guide the placer toward a local metastability-catching aperture and at most
# one following SLR hop, while leaving it free to violate the regions when a
# hard assignment would degrade overall timing.
# The P4 routed inventory shows each input pair sharing one physical clock
# region. Guide the metastability-catching registers to that exact region,
# instead of allowing an SLR-wide pblock to place them a region away from the
# corresponding BITSLICE. These remain soft placement guides; the 1.5 ns
# datapath constraint above is the actual acceptance criterion.
# Create SLR-wide parents before the contained clock-region guides.  Vivado
# otherwise re-parents the child pblocks while reading this XDC, which makes
# incremental placement depend on constraint processing order.
create_pblock pblock_dvp_bridge_slr2
resize_pblock [get_pblocks pblock_dvp_bridge_slr2] -add SLR2
set_property IS_SOFT true [get_pblocks pblock_dvp_bridge_slr2]

create_pblock pblock_dvp_pipe_slr1
resize_pblock [get_pblocks pblock_dvp_pipe_slr1] -add SLR1
set_property IS_SOFT true [get_pblocks pblock_dvp_pipe_slr1]

create_pblock pblock_dvp_sync_ch01
resize_pblock [get_pblocks pblock_dvp_sync_ch01] -add CLOCKREGION_X4Y13
set_property IS_SOFT true [get_pblocks pblock_dvp_sync_ch01]
add_cells_to_pblock [get_pblocks pblock_dvp_sync_ch01] \
    [get_cells -hierarchical -regexp \
        {.*g_camera_frontend\[[0-1]\]\.u_channel/u_frontend/u_input_sampler/dvp_(data|href|vsync|pclk)_sync_reg.*}]

create_pblock pblock_dvp_sync_ch23
resize_pblock [get_pblocks pblock_dvp_sync_ch23] -add CLOCKREGION_X4Y12
set_property IS_SOFT true [get_pblocks pblock_dvp_sync_ch23]
add_cells_to_pblock [get_pblocks pblock_dvp_sync_ch23] \
    [get_cells -hierarchical -regexp \
        {.*g_camera_frontend\[[2-3]\]\.u_channel/u_frontend/u_input_sampler/dvp_(data|href|vsync|pclk)_sync_reg.*}]

create_pblock pblock_dvp_sync_ch45
resize_pblock [get_pblocks pblock_dvp_sync_ch45] -add CLOCKREGION_X4Y9
set_property IS_SOFT true [get_pblocks pblock_dvp_sync_ch45]
add_cells_to_pblock [get_pblocks pblock_dvp_sync_ch45] \
    [get_cells -hierarchical -regexp \
        {.*g_camera_frontend\[[4-5]\]\.u_channel/u_frontend/u_input_sampler/dvp_(data|href|vsync|pclk)_sync_reg.*}]

create_pblock pblock_dvp_sync_ch67
resize_pblock [get_pblocks pblock_dvp_sync_ch67] -add CLOCKREGION_X4Y8
set_property IS_SOFT true [get_pblocks pblock_dvp_sync_ch67]
add_cells_to_pblock [get_pblocks pblock_dvp_sync_ch67] \
    [get_cells -hierarchical -regexp \
        {.*g_camera_frontend\[[6-7]\]\.u_channel/u_frontend/u_input_sampler/dvp_(data|href|vsync|pclk)_sync_reg.*}]

add_cells_to_pblock [get_pblocks pblock_dvp_bridge_slr2] \
    [get_cells -hierarchical -regexp \
        {.*g_camera_frontend\[[0-3]\]\.u_channel/u_frontend/u_input_sampler/sampled_(data|href|vsync|pclk)_reg.*}]

add_cells_to_pblock [get_pblocks pblock_dvp_pipe_slr1] \
    [get_cells -hierarchical -regexp \
        {.*g_camera_frontend\[[4-7]\]\.u_channel/u_frontend/u_input_sampler/sampled_(data|href|vsync|pclk)_reg.*}]

# Keep the recovery decision logic and event producer in their nearby SLR.
# Telemetry is a registered sink and may be placed independently. Do not add
# the recovery parent hierarchy to the pblock: that would pull telemetry in.
create_pblock pblock_camera_capture_slr2
resize_pblock [get_pblocks pblock_camera_capture_slr2] -add SLR2
set_property IS_SOFT true [get_pblocks pblock_camera_capture_slr2]
set capture_core_slr2 [get_cells -hierarchical -regexp \
    {.*g_camera_frontend\[[0-3]\]\.u_channel/u_frontend/u_pclk_recovery/.*}]
set capture_core_slr2 [filter $capture_core_slr2 \
    {NAME !~ *u_telemetry*}]
add_cells_to_pblock [get_pblocks pblock_camera_capture_slr2] \
    $capture_core_slr2
add_cells_to_pblock [get_pblocks pblock_camera_capture_slr2] \
    [get_cells -hierarchical -regexp \
        {.*g_camera_frontend\[[0-3]\]\.u_channel/u_event_bridge(/.*)?}]

create_pblock pblock_camera_capture_slr1
resize_pblock [get_pblocks pblock_camera_capture_slr1] -add SLR1
set_property IS_SOFT true [get_pblocks pblock_camera_capture_slr1]
set capture_core_slr1 [get_cells -hierarchical -regexp \
    {.*g_camera_frontend\[[4-7]\]\.u_channel/u_frontend/u_pclk_recovery/.*}]
set capture_core_slr1 [filter $capture_core_slr1 \
    {NAME !~ *u_telemetry*}]
add_cells_to_pblock [get_pblocks pblock_camera_capture_slr1] \
    $capture_core_slr1
add_cells_to_pblock [get_pblocks pblock_camera_capture_slr1] \
    [get_cells -hierarchical -regexp \
        {.*g_camera_frontend\[[4-7]\]\.u_channel/u_event_bridge(/.*)?}]

# Camera control and diagnostic requests cross into the 300 MHz capture domain
# through explicit two-stage synchronizers.  Only their first-stage D pins are
# asynchronous; the second stage remains normally timed so placement still
# maximizes synchronizer resolution time.  Keep these endpoint-specific rather
# than declaring the complete 24/100/300 MHz clock domains asynchronous.
set_false_path -to [get_pins -hierarchical -filter \
    {NAME =~ */capture_enable_sync1_reg/D || \
     NAME =~ */diag_clear_video_sync1_reg/D || \
     NAME =~ *u_camera_stream/diag_clear_sync1_reg/D}]

# Camera diagnostics cross as indexed, handshake-protected mailbox records.
# Cut only the asynchronous inputs of each first synchronizer stage; payload
# is held stable until the destination acknowledges the record.
set_false_path \
    -to [get_pins -hierarchical -filter \
        {NAME =~ */u_camera_telemetry/*/request_sync_reg[0]/D || \
         NAME =~ */u_camera_telemetry/*/payload_sync1_reg*/D || \
         NAME =~ */u_camera_telemetry/*/acknowledge_sync_reg[0]/D}]

# Framebuffer configuration, selection and mode are now captured by coherent
# mailboxes in video_control_bridge.  All signals downstream of that bridge,
# including the manager's legacy staging registers, are synchronous to the
# video clock and therefore need no CDC timing exception here.
# The mailbox inputs themselves are asynchronous first-stage samples.  Cut
# only those D pins; keep the second synchronizer stage and all destination
# payload consumers timed.  Without this exception the 100/150 MHz clocks are
# incorrectly compared at near-coincident edges, producing thousands of
# apparent setup violations on stable, handshake-protected payload bits.
set_false_path -to [get_pins -hierarchical -filter \
    {NAME =~ *u_video_pipeline/u_control_bridge/*/request_sync_reg[0]/D || \
     NAME =~ *u_video_pipeline/u_control_bridge/*/payload_sync1_reg*/D || \
     NAME =~ *u_video_pipeline/u_control_bridge/*/acknowledge_sync_reg[0]/D}]
