###############################################################################
# Eight OV7670 cameras on ATK-FMC-EXTIO.
# CAM0-CAM3 = FMC1 (A wiring); CAM4-CAM7 = FMC2.
# FMC2 CAM0-CAM2 use the HS/HREF <-> RESET B wiring for the A/B test.
# FMC2 CAM3 remains unchanged as the reference channel.
# Source: doc/VU13P_OV7670_8CH_FMC1_FMC2_Physical_Neat_Pin_Assignment.md
###############################################################################

# FMC1 CAM0 / camera 1
set_property PACKAGE_PIN F9 [get_ports {cam_data[0]}]
set_property PACKAGE_PIN F10 [get_ports {cam_data[1]}]
set_property PACKAGE_PIN C7 [get_ports {cam_data[2]}]
set_property PACKAGE_PIN D7 [get_ports {cam_data[3]}]
set_property PACKAGE_PIN C8 [get_ports {cam_data[4]}]
set_property PACKAGE_PIN C9 [get_ports {cam_data[5]}]
set_property PACKAGE_PIN E11 [get_ports {cam_data[6]}]
set_property PACKAGE_PIN F11 [get_ports {cam_data[7]}]
set_property PACKAGE_PIN H15 [get_ports {cam_vsync[0]}]
set_property PACKAGE_PIN H14 [get_ports {cam_href[0]}]
set_property PACKAGE_PIN E12 [get_ports {cam_pclk[0]}]
set_property PACKAGE_PIN D12 [get_ports {cam_xclk[0]}]
set_property PACKAGE_PIN B13 [get_ports {cam_scl[0]}]
set_property PACKAGE_PIN E13 [get_ports {cam_sda[0]}]
set_property PACKAGE_PIN C13 [get_ports {cam_rst_n[0]}]
set_property PACKAGE_PIN E9 [get_ports {cam_pwdn[0]}]

# FMC1 CAM1 / camera 2
set_property PACKAGE_PIN F15 [get_ports {cam_data[8]}]
set_property PACKAGE_PIN G15 [get_ports {cam_data[9]}]
set_property PACKAGE_PIN G12 [get_ports {cam_data[10]}]
set_property PACKAGE_PIN H12 [get_ports {cam_data[11]}]
set_property PACKAGE_PIN G10 [get_ports {cam_data[12]}]
set_property PACKAGE_PIN G11 [get_ports {cam_data[13]}]
set_property PACKAGE_PIN B7 [get_ports {cam_data[14]}]
set_property PACKAGE_PIN B8 [get_ports {cam_data[15]}]
set_property PACKAGE_PIN D11 [get_ports {cam_vsync[1]}]
set_property PACKAGE_PIN D10 [get_ports {cam_href[1]}]
set_property PACKAGE_PIN F13 [get_ports {cam_pclk[1]}]
set_property PACKAGE_PIN D9 [get_ports {cam_xclk[1]}]
set_property PACKAGE_PIN B12 [get_ports {cam_scl[1]}]
set_property PACKAGE_PIN E14 [get_ports {cam_sda[1]}]
set_property PACKAGE_PIN F14 [get_ports {cam_rst_n[1]}]
set_property PACKAGE_PIN C12 [get_ports {cam_pwdn[1]}]

# FMC1 CAM2 / camera 3
set_property PACKAGE_PIN W12 [get_ports {cam_data[16]}]
set_property PACKAGE_PIN V12 [get_ports {cam_data[17]}]
set_property PACKAGE_PIN V13 [get_ports {cam_data[18]}]
set_property PACKAGE_PIN U12 [get_ports {cam_data[19]}]
set_property PACKAGE_PIN R12 [get_ports {cam_data[20]}]
set_property PACKAGE_PIN P12 [get_ports {cam_data[21]}]
set_property PACKAGE_PIN R11 [get_ports {cam_data[22]}]
set_property PACKAGE_PIN P11 [get_ports {cam_data[23]}]
set_property PACKAGE_PIN V14 [get_ports {cam_vsync[2]}]
set_property PACKAGE_PIN W14 [get_ports {cam_href[2]}]
set_property PACKAGE_PIN R14 [get_ports {cam_pclk[2]}]
set_property PACKAGE_PIN AA12 [get_ports {cam_xclk[2]}]
set_property PACKAGE_PIN L13 [get_ports {cam_scl[2]}]
set_property PACKAGE_PIN M12 [get_ports {cam_sda[2]}]
set_property PACKAGE_PIN M13 [get_ports {cam_rst_n[2]}]
set_property PACKAGE_PIN L14 [get_ports {cam_pwdn[2]}]

# FMC1 CAM3 / camera 4
set_property PACKAGE_PIN T16 [get_ports {cam_data[24]}]
set_property PACKAGE_PIN T15 [get_ports {cam_data[25]}]
set_property PACKAGE_PIN AA14 [get_ports {cam_data[26]}]
set_property PACKAGE_PIN Y14 [get_ports {cam_data[27]}]
set_property PACKAGE_PIN M15 [get_ports {cam_data[28]}]
set_property PACKAGE_PIN L15 [get_ports {cam_data[29]}]
set_property PACKAGE_PIN P15 [get_ports {cam_data[30]}]
set_property PACKAGE_PIN N15 [get_ports {cam_data[31]}]
set_property PACKAGE_PIN V15 [get_ports {cam_vsync[3]}]
set_property PACKAGE_PIN AA13 [get_ports {cam_href[3]}]
set_property PACKAGE_PIN N14 [get_ports {cam_pclk[3]}]
set_property PACKAGE_PIN N13 [get_ports {cam_xclk[3]}]
set_property PACKAGE_PIN Y13 [get_ports {cam_scl[3]}]
set_property PACKAGE_PIN U15 [get_ports {cam_sda[3]}]
set_property PACKAGE_PIN P14 [get_ports {cam_rst_n[3]}]
set_property PACKAGE_PIN V16 [get_ports {cam_pwdn[3]}]

# FMC2 CAM0 / camera 5
# B variant: HS/HREF and RESET are exchanged at the package pins so VS is
# separated from the high-activity HS signal during the A/B test.
set_property PACKAGE_PIN F39 [get_ports {cam_data[32]}]
set_property PACKAGE_PIN F38 [get_ports {cam_data[33]}]
set_property PACKAGE_PIN A38 [get_ports {cam_data[34]}]
set_property PACKAGE_PIN B38 [get_ports {cam_data[35]}]
set_property PACKAGE_PIN J40 [get_ports {cam_data[36]}]
set_property PACKAGE_PIN J39 [get_ports {cam_data[37]}]
set_property PACKAGE_PIN F40 [get_ports {cam_data[38]}]
set_property PACKAGE_PIN G40 [get_ports {cam_data[39]}]
set_property PACKAGE_PIN C39 [get_ports {cam_vsync[4]}]
set_property PACKAGE_PIN A39 [get_ports {cam_href[4]}]
set_property PACKAGE_PIN G36 [get_ports {cam_pclk[4]}]
set_property PACKAGE_PIN G37 [get_ports {cam_xclk[4]}]
set_property PACKAGE_PIN A40 [get_ports {cam_scl[4]}]
set_property PACKAGE_PIN D39 [get_ports {cam_sda[4]}]
set_property PACKAGE_PIN B40 [get_ports {cam_rst_n[4]}]
set_property PACKAGE_PIN D40 [get_ports {cam_pwdn[4]}]

# FMC2 CAM1 / camera 6
# B variant: HS/HREF and RESET are exchanged at the package pins.
set_property PACKAGE_PIN E34 [get_ports {cam_data[40]}]
set_property PACKAGE_PIN F34 [get_ports {cam_data[41]}]
set_property PACKAGE_PIN H40 [get_ports {cam_data[42]}]
set_property PACKAGE_PIN H39 [get_ports {cam_data[43]}]
set_property PACKAGE_PIN C37 [get_ports {cam_data[44]}]
set_property PACKAGE_PIN D37 [get_ports {cam_data[45]}]
set_property PACKAGE_PIN G35 [get_ports {cam_data[46]}]
set_property PACKAGE_PIN H34 [get_ports {cam_data[47]}]
set_property PACKAGE_PIN K37 [get_ports {cam_vsync[5]}]
set_property PACKAGE_PIN H38 [get_ports {cam_href[5]}]
set_property PACKAGE_PIN E39 [get_ports {cam_pclk[5]}]
set_property PACKAGE_PIN C40 [get_ports {cam_xclk[5]}]
set_property PACKAGE_PIN H37 [get_ports {cam_scl[5]}]
set_property PACKAGE_PIN G38 [get_ports {cam_sda[5]}]
set_property PACKAGE_PIN J37 [get_ports {cam_rst_n[5]}]
set_property PACKAGE_PIN J36 [get_ports {cam_pwdn[5]}]

# FMC2 CAM2 / camera 7
# B variant: HS/HREF and RESET are exchanged at the package pins.
set_property PACKAGE_PIN R31 [get_ports {cam_data[48]}]
set_property PACKAGE_PIN P31 [get_ports {cam_data[49]}]
set_property PACKAGE_PIN Y31 [get_ports {cam_data[50]}]
set_property PACKAGE_PIN W31 [get_ports {cam_data[51]}]
set_property PACKAGE_PIN P37 [get_ports {cam_data[52]}]
set_property PACKAGE_PIN N37 [get_ports {cam_data[53]}]
set_property PACKAGE_PIN L34 [get_ports {cam_data[54]}]
set_property PACKAGE_PIN K34 [get_ports {cam_data[55]}]
set_property PACKAGE_PIN U32 [get_ports {cam_vsync[6]}]
set_property PACKAGE_PIN Y34 [get_ports {cam_href[6]}]
set_property PACKAGE_PIN R34 [get_ports {cam_pclk[6]}]
set_property PACKAGE_PIN N38 [get_ports {cam_xclk[6]}]
set_property PACKAGE_PIN L36 [get_ports {cam_scl[6]}]
set_property PACKAGE_PIN W34 [get_ports {cam_sda[6]}]
set_property PACKAGE_PIN U31 [get_ports {cam_rst_n[6]}]
set_property PACKAGE_PIN M36 [get_ports {cam_pwdn[6]}]

# FMC2 CAM3 / camera 8
set_property PACKAGE_PIN T34 [get_ports {cam_data[56]}]
set_property PACKAGE_PIN T35 [get_ports {cam_data[57]}]
set_property PACKAGE_PIN M37 [get_ports {cam_data[58]}]
set_property PACKAGE_PIN L38 [get_ports {cam_data[59]}]
set_property PACKAGE_PIN U35 [get_ports {cam_data[60]}]
set_property PACKAGE_PIN T36 [get_ports {cam_data[61]}]
set_property PACKAGE_PIN T30 [get_ports {cam_data[62]}]
set_property PACKAGE_PIN T31 [get_ports {cam_data[63]}]
set_property PACKAGE_PIN Y32 [get_ports {cam_vsync[7]}]
set_property PACKAGE_PIN V33 [get_ports {cam_href[7]}]
set_property PACKAGE_PIN T33 [get_ports {cam_pclk[7]}]
set_property PACKAGE_PIN R33 [get_ports {cam_xclk[7]}]
set_property PACKAGE_PIN V34 [get_ports {cam_scl[7]}]
set_property PACKAGE_PIN W32 [get_ports {cam_sda[7]}]
set_property PACKAGE_PIN P34 [get_ports {cam_rst_n[7]}]
set_property PACKAGE_PIN V32 [get_ports {cam_pwdn[7]}]

set_property IOSTANDARD LVCMOS18 [get_ports {
    cam_data[*] cam_vsync[*] cam_href[*] cam_pclk[*] cam_xclk[*]
    cam_scl[*] cam_sda[*] cam_rst_n[*] cam_pwdn[*]
}]
set_property DRIVE 8 [get_ports {cam_xclk[*] cam_scl[*] cam_rst_n[*] cam_pwdn[*]}]
set_property SLEW SLOW [get_ports {cam_xclk[*] cam_scl[*] cam_rst_n[*] cam_pwdn[*]}]
set_property PULLUP true [get_ports {cam_sda[*]}]

create_clock -name ov7670_pclk_1 -period 25.000 [get_ports {cam_pclk[0]}]
create_clock -name ov7670_pclk_2 -period 25.000 [get_ports {cam_pclk[1]}]
create_clock -name ov7670_pclk_3 -period 25.000 [get_ports {cam_pclk[2]}]
create_clock -name ov7670_pclk_4 -period 25.000 [get_ports {cam_pclk[3]}]
create_clock -name ov7670_pclk_5 -period 25.000 [get_ports {cam_pclk[4]}]
create_clock -name ov7670_pclk_6 -period 25.000 [get_ports {cam_pclk[5]}]
create_clock -name ov7670_pclk_7 -period 25.000 [get_ports {cam_pclk[6]}]
create_clock -name ov7670_pclk_8 -period 25.000 [get_ports {cam_pclk[7]}]

# Board outputs are 12 MHz. Declaring them documents the external interface;
# each camera returns an independent PCLK which is intentionally its own clock.
create_clock -name ov7670_xclk_1 -period 83.333 [get_ports {cam_xclk[0]}]
create_clock -name ov7670_xclk_2 -period 83.333 [get_ports {cam_xclk[1]}]
create_clock -name ov7670_xclk_3 -period 83.333 [get_ports {cam_xclk[2]}]
create_clock -name ov7670_xclk_4 -period 83.333 [get_ports {cam_xclk[3]}]
create_clock -name ov7670_xclk_5 -period 83.333 [get_ports {cam_xclk[4]}]
create_clock -name ov7670_xclk_6 -period 83.333 [get_ports {cam_xclk[5]}]
create_clock -name ov7670_xclk_7 -period 83.333 [get_ports {cam_xclk[6]}]
create_clock -name ov7670_xclk_8 -period 83.333 [get_ports {cam_xclk[7]}]
